import Foundation

// Interface text added in version 3 (Arabic first). Checked by
// Scripts/validate_strings.py with the other tables: no key may repeat.
enum StringsPro {
    static let table: [String: (ar: String, en: String)] = [
        "a11y.braille": ("صياغة مختصرة لشاشة برايل", "Short wording for braille displays"),
        "a11y.braille.footer": ("المختصر يقول «كابتشينو، قوي، 60 مل» بدل الجملة الكاملة، فيظهر في سطر برايل واحد. مستوى التفصيل يتحكم في كم يُقال أثناء التحضير.", "Brief wording says “Cappuccino, strong, 60 ml” instead of the full sentence, so it fits one braille line. Detail level controls how much is said while brewing."),
        "a11y.dripWait": ("نبّهني لانتظار آخر القطرات", "Remind me to wait for the last drops"),
        "a11y.gestures.footer": ("الهز يقول حالة الماكينة والمشروب والكافيين من أي شاشة. النقر بإصبعين مرتين في الرئيسية يحضّر مشروبك المعتاد، ويسأل أولًا إن كان التأكيد مفعّلًا.", "Shaking says the machine, drink and caffeine from any screen. A two-finger double-tap on Home makes your usual drink, asking first if confirmation is on."),
        "a11y.giant": ("شاشة تحضير عملاقة", "Giant brewing screen"),
        "a11y.haptic.try": ("المس مرتين للتجربة", "Double-tap to feel it"),
        "a11y.hapticOnly": ("الاهتزاز فقط لكل مرحلة", "Vibration only, for every phase"),
        "a11y.hapticOnly.footer": ("لكل مرحلة نمط اهتزاز خاص: الطحن نبضات سريعة، والصب نبضتان طويلتان، والحليب نبضتان أطول، والانتهاء أربع نبضات. يناسب من لا يرى الشاشة ولا يسمع الكلام.", "Each phase has its own rhythm: grinding is quick pulses, pouring two long ones, milk two longer ones, and finishing four. For people who can neither see the screen nor hear speech."),
        "a11y.magicTap": ("النقر بإصبعين مرتين يحضّر المعتاد", "Two-finger double-tap makes your usual"),
        "a11y.rate": ("سرعة الكلام", "Speaking rate"),
        "a11y.shake": ("هزّ الهاتف لسماع الحالة", "Shake to hear the status"),
        "a11y.ticks": ("نغمة تقدم كل 10 بالمئة", "A progress tone every 10 percent"),
        "a11y.verbosity": ("مستوى التفصيل", "Detail level"),
        "a11y.verbosity.0": ("مختصر", "Brief"),
        "a11y.verbosity.1": ("عادي", "Standard"),
        "a11y.verbosity.2": ("مفصّل", "Detailed"),
        "a11y.voice": ("الصوت", "Voice"),
        "a11y.voice.default": ("الصوت الافتراضي", "Default voice"),
        "a11y.voice.footer": ("يُستخدم عند تفعيل «النطق دون VoiceOver». مع VoiceOver يتكلم صوت VoiceOver نفسه. الأصوات المحسّنة تُنزّل من إعدادات iOS.", "Used when “Speak without VoiceOver” is on. With VoiceOver, VoiceOver's own voice speaks. Enhanced voices are downloaded in iOS Settings."),
        "a11y.voice.header": ("الصوت دون VoiceOver", "Voice without VoiceOver"),
        "a11y.voice.preview": ("استمع إلى الصوت", "Hear the voice"),
        "a11y.voice.sample": ("مرحبًا، هكذا سأخبرك عن قهوتك.", "Hello, this is how I will tell you about your coffee."),
        "academy.beans.p1": ("البن نوعان رئيسيان: أرابيكا الناعم، وروبوستا الأقوى الذي فيه كافيين أكثر. معظم الخلطات تمزج بينهما.", "There are two main kinds: smooth arabica, and stronger robusta with more caffeine. Most blends mix both."),
        "academy.beans.p2": ("التحميص يصنع النكهة: الفاتح فاكهي وحامض، والمتوسط متوازن، والغامق أثقل وبنكهة الشوكولاتة.", "Roasting makes the flavour: light is fruity and bright, medium balanced, dark heavier and chocolatey."),
        "academy.beans.p3": ("أفضل طعم بين أسبوع وشهر من التحميص. احفظ البن في وعاء محكم، لا في الثلاجة.", "It tastes best one week to a month after roasting. Keep beans airtight, not in the fridge."),
        "academy.beans.q1": ("أي بن فيه كافيين أكثر؟", "Which beans have more caffeine?"),
        "academy.beans.q1.a1": ("روبوستا", "Robusta"),
        "academy.beans.q1.a2": ("أرابيكا", "Arabica"),
        "academy.beans.q1.a3": ("كلاهما متساويان", "Both the same"),
        "academy.beans.q2": ("أين تحفظ البن؟", "Where should beans be kept?"),
        "academy.beans.q2.a1": ("في وعاء محكم بعيدًا عن الضوء", "Airtight, away from light"),
        "academy.beans.q2.a2": ("في الثلاجة", "In the fridge"),
        "academy.beans.q2.a3": ("في كيس مفتوح قرب الماكينة", "In an open bag by the machine"),
        "academy.beans.title": ("البن", "Beans"),
        "academy.care.p1": ("يوميًا: أفرغ حاوية البن المستعمل وصينية التنقيط، ونظّف إبريق الحليب.", "Daily: empty the grounds and drip tray, and clean the milk carafe."),
        "academy.care.p2": ("أسبوعيًا: أخرج وحدة التحضير واشطفها بالماء فقط ودعها تجف.", "Weekly: take out the brewing unit, rinse it with water only and let it dry."),
        "academy.care.p3": ("عندما تطلب الماكينة: أزل الترسبات بالمزيل المخصص، وبدّل الفلتر في موعده.", "When the machine asks: descale with the proper descaler, and change the filter on time."),
        "academy.care.q1": ("كيف تنظف وحدة التحضير؟", "How do you clean the brewing unit?"),
        "academy.care.q1.a1": ("بالماء فقط دون منظفات", "With water only, no detergent"),
        "academy.care.q1.a2": ("في غسالة الصحون", "In the dishwasher"),
        "academy.care.q1.a3": ("بالخل", "With vinegar"),
        "academy.care.q2": ("ماذا تفرغ يوميًا؟", "What do you empty daily?"),
        "academy.care.q2.a1": ("حاوية البن المستعمل وصينية التنقيط", "The grounds container and drip tray"),
        "academy.care.q2.a2": ("خزان البن", "The bean hopper"),
        "academy.care.q2.a3": ("لا شيء", "Nothing"),
        "academy.care.title": ("العناية", "Care"),
        "academy.done": ("منجز", "Done"),
        "academy.grind.p1": ("الطحن يحدد سرعة مرور الماء عبر البن، ومنه كم يُستخلص.", "The grind sets how fast water flows through the coffee, and so how much is extracted."),
        "academy.grind.p2": ("إن كان الطعم حامضًا وخفيفًا فاجعل الطحن أنعم درجة. وإن كان مرًا فاجعله أخشن.", "If it tastes sour and thin, grind one step finer. If it's bitter, grind coarser."),
        "academy.grind.p3": ("غيّر القرص والمطحنة تعمل فقط، وانتظر كوبين قبل الحكم، لأن البن القديم ما زال في المطحنة.", "Turn the dial only while the grinder runs, and wait two cups before judging, as old coffee is still inside."),
        "academy.grind.q1": ("القهوة حامضة. ماذا تفعل؟", "The coffee is sour. What do you do?"),
        "academy.grind.q1.a1": ("أجعل الطحن أنعم", "Grind finer"),
        "academy.grind.q1.a2": ("أجعل الطحن أخشن", "Grind coarser"),
        "academy.grind.q1.a3": ("أضيف ماءً أكثر", "Add more water"),
        "academy.grind.q2": ("متى تدير قرص الطحن؟", "When do you turn the grind dial?"),
        "academy.grind.q2.a1": ("والمطحنة تعمل", "While the grinder runs"),
        "academy.grind.q2.a2": ("والماكينة مطفأة", "With the machine off"),
        "academy.grind.q2.a3": ("في أي وقت", "Any time"),
        "academy.grind.title": ("الطحن", "Grinding"),
        "academy.lessonDone": ("أنهيت درس %@.", "You finished the %@ lesson."),
        "academy.milk.p1": ("الحليب البارد من الثلاجة يعطي رغوة أفضل. كامل الدسم ناعم وغني، والقليل الدسم رغوته كثيرة وأخف.", "Cold milk straight from the fridge foams best. Whole milk is rich and smooth; low-fat foams a lot but lighter."),
        "academy.milk.p2": ("مقبض الإبريق يحدد كثافة الرغوة: قليلة للاتيه، ومتوسطة للفلات وايت، وكثيرة للكابتشينو.", "The carafe dial sets the foam: little for a latte, medium for a flat white, lots for a cappuccino."),
        "academy.milk.p3": ("نظّف الإبريق بعد كل استخدام بوضع التنظيف، وأعد الحليب إلى الثلاجة فورًا.", "Clean the carafe after each use with the clean setting, and put the milk back in the fridge at once."),
        "academy.milk.q1": ("أي حليب يعطي أفضل رغوة؟", "Which milk foams best?"),
        "academy.milk.q1.a1": ("الحليب البارد من الثلاجة", "Cold milk from the fridge"),
        "academy.milk.q1.a2": ("الحليب الدافئ", "Warm milk"),
        "academy.milk.q1.a3": ("الحليب المتروك خارج الثلاجة", "Milk left out of the fridge"),
        "academy.milk.q2": ("الكابتشينو يحتاج رغوة…", "A cappuccino needs…"),
        "academy.milk.q2.a1": ("كثيرة", "Lots of foam"),
        "academy.milk.q2.a2": ("قليلة جدًا", "Very little foam"),
        "academy.milk.q2.a3": ("لا رغوة", "No foam"),
        "academy.milk.title": ("الحليب", "Milk"),
        "academy.progress": ("أنجزت %1$d من %2$d دروس.", "%1$d of %2$d lessons done."),
        "academy.right": ("إجابة صحيحة!", "Correct!"),
        "academy.strength.p1": ("القوة هي كمية البن، والكمية هي الماء. كوب أكبر بالقوة نفسها يكون أخف طعمًا.", "Strength is the amount of coffee; size is the water. A bigger cup at the same strength tastes lighter."),
        "academy.strength.p2": ("لكوب كبير قوي استخدم «جرعة إضافية» أو كوبًا مزدوجًا بدل إطالة الإسبريسو.", "For a big strong cup use an extra shot or a double rather than stretching an espresso."),
        "academy.strength.p3": ("الإسبريسو فيه كافيين أقل من كوب قهوة طويل كبير، رغم أنه أقوى طعمًا.", "An espresso has less caffeine than a big long coffee, even though it tastes stronger."),
        "academy.strength.q1": ("ما الذي تغيّره «القوة»؟", "What does “strength” change?"),
        "academy.strength.q1.a1": ("كمية البن", "The amount of coffee"),
        "academy.strength.q1.a2": ("كمية الماء", "The amount of water"),
        "academy.strength.q1.a3": ("حرارة الماء", "The water temperature"),
        "academy.strength.q2": ("أي كوب فيه كافيين أكثر عادة؟", "Which usually has more caffeine?"),
        "academy.strength.q2.a1": ("قهوة طويلة كبيرة", "A big long coffee"),
        "academy.strength.q2.a2": ("إسبريسو واحد", "A single espresso"),
        "academy.strength.q2.a3": ("ريستريتو", "A ristretto"),
        "academy.strength.title": ("القوة والكمية", "Strength and size"),
        "academy.water.p1": ("القهوة نحو 98 بالمئة ماء، فطعم الماء يصنع طعم القهوة. استخدم ماءً نظيفًا بلا رائحة.", "Coffee is about 98 percent water, so the water's taste is the coffee's taste. Use clean water with no smell."),
        "academy.water.p2": ("بدّل ماء الخزان يوميًا أو كل يومين؛ الماء الراكد يفقد الأكسجين ويصبح طعمه باهتًا.", "Change the tank water daily or every other day; standing water loses oxygen and tastes flat."),
        "academy.water.p3": ("الفلتر وقياس العسر يقللان الترسبات ويطيلان عمر الماكينة.", "A filter and the right hardness setting reduce scale and make the machine last longer."),
        "academy.water.q1": ("كم مرة تبدّل ماء الخزان؟", "How often should the tank water be changed?"),
        "academy.water.q1.a1": ("يوميًا أو كل يومين", "Daily or every other day"),
        "academy.water.q1.a2": ("مرة في الشهر", "Once a month"),
        "academy.water.q1.a3": ("فقط عندما يفرغ", "Only when it's empty"),
        "academy.water.q2": ("ما فائدة فلتر الماء؟", "What does the water filter do?"),
        "academy.water.q2.a1": ("يقلل الترسبات ويحسن الطعم", "Reduces scale and improves taste"),
        "academy.water.q2.a2": ("يزيد الكافيين", "Adds caffeine"),
        "academy.water.q2.a3": ("يسخّن الماء", "Heats the water"),
        "academy.water.title": ("الماء", "Water"),
        "academy.wrong": ("ليس تمامًا. الإجابة الصحيحة: %@", "Not quite. The right answer: %@"),
        "action.no": ("لا", "No"),
        "action.yes": ("نعم", "Yes"),
        "additions.footer": ("تُقال لك هذه الملاحظة عندما يجهز المشروب، لأن الماكينة لا تضيفها.", "This note is read out when the drink is ready, because the machine can't add it."),
        "additions.placeholder": ("مثلًا: ملعقة سكر ورشة قرفة", "For example: a spoon of sugar and a pinch of cinnamon"),
        "additions.remind": ("لا تنسَ: %@.", "Don't forget: %@."),
        "additions.title": ("بعد التحضير", "After brewing"),
        "alarmHistory.clear": ("امسح السجل", "Clear the history"),
        "alarmHistory.month": ("آخر 30 يومًا", "Last 30 days"),
        "alarmHistory.none": ("لا تنبيهات في آخر 30 يومًا.", "No alerts in the last 30 days."),
        "alarmHistory.recent": ("الأحدث", "Most recent"),
        "alarmHistory.times": ("%d مرة", "%d times"),
        "backup.confirm": ("الاستعادة تستبدل كل بياناتك الحالية", "Restoring replaces all your current data"),
        "backup.confirm.detail": ("نسخة من %1$@ (الإصدار %2$@).", "Backup from %1$@ (version %2$@)."),
        "backup.export": ("صدّر نسخة احتياطية", "Export a backup"),
        "backup.footer": ("ملف واحد فيه ملفاتك ومفضلاتك وسجلك والبن والعائلة والإعدادات. احفظه في «الملفات» أو أرسله لنفسك.", "One file with your profiles, favorites, history, beans, household and settings. Save it to Files or send it to yourself."),
        "backup.import": ("استعد من نسخة احتياطية", "Restore from a backup"),
        "backup.invalid": ("هذا الملف ليس نسخة احتياطية من قهوتي.", "This file isn't a Coffee backup."),
        "backup.restore": ("استعد", "Restore"),
        "backup.restored": ("استُعيدت النسخة الاحتياطية.", "The backup is restored."),
        "bag.noBean": ("اختر البن الموجود في الماكينة أولًا.", "Choose the beans in the machine first."),
        "bag.opened": ("سُجّل فتح كيس جديد من %@ اليوم.", "A new bag of %@ is logged as opened today."),
        "bag.openedButton": ("فتحت كيسًا جديدًا من البن الحالي", "I opened a new bag of these beans"),
        "barcode.known": ("عرفت هذا الكيس: %@. أكملت البيانات.", "I know this bag: %@. Details filled in."),
        "barcode.none": ("لم أجد باركود في الصورة. صوّره عن قرب وبإضاءة جيدة.", "No barcode found. Photograph it closer, in good light."),
        "barcode.read": ("قرأت الباركود %@.", "Barcode %@ read."),
        "barcode.scan": ("اقرأ الباركود بالكاميرا", "Read the barcode with the camera"),
        "beans.barcode": ("الباركود", "Barcode"),
        "beans.buyAgain": ("أشتريه مجددًا", "Buy again"),
        "beans.buyAgain.footer": ("ما تختار شراءه مجددًا يظهر في قائمة المشتريات حين يقترب الكيس من النفاد. الباركود يتعرّف على الكيس نفسه لاحقًا.", "Beans marked “buy again” join the shopping list when the bag runs low. The barcode recognises the same bag later."),
        "beans.decaf": ("منزوع الكافيين", "Decaf"),
        "beans.price": ("سعر الكيس", "Bag price"),
        "beans.price.footer": ("مع وزن الكيس يحسب التطبيق تكلفة الكوب. البن منزوع الكافيين لا يُحسب كافيينًا تقريبًا.", "With the bag weight the app works out the cost per cup. Decaf beans count as almost no caffeine."),
        "beans.rating": ("تقييمك", "Your rating"),
        "beans.rating.none": ("دون تقييم", "Not rated"),
        "beans.roastDate": ("تاريخ التحميص", "Roast date"),
        "caffeine.below50": ("ينخفض تحت 50 ملغ نحو %@.", "It drops under 50 mg around %@."),
        "caffeine.inBody": ("ما بقي في جسمك الآن", "Still in your body now"),
        "caffeine.inBody.footer": ("تقدير بنصف عمر خمس ساعات تقريبًا، ويختلف من شخص لآخر. أقل من 50 ملغ عند النوم يساعد كثيرين على نوم أفضل.", "An estimate using a half-life of about five hours, which varies by person. Under 50 mg at bedtime helps many people sleep better."),
        "child.blocked": ("ملف %@ ملف طفل: هذا المشروب فيه كافيين.", "%@'s profile is a child's: this drink has caffeine."),
        "children.footer": ("ملفات الأطفال لا تحضّر مشروبات فيها كافيين؛ المتاح: الحليب الساخن والبارد والبيبيتشينو والماء الساخن والأعشاب.", "Children's profiles can't make drinks with caffeine; they can have hot or cold milk, babyccino, hot water and herbal tea."),
        "combo.add": ("تشكيلة جديدة", "New combo"),
        "combo.addStep": ("أضف خطوة", "Add a step"),
        "combo.edit": ("التشكيلة", "Combo"),
        "combo.empty": ("لا تشكيلات بعد. مثال: إسبريسو ثم ماء ساخن في الكوب نفسه.", "No combos yet. Example: an espresso, then hot water in the same cup."),
        "combo.footer": ("التشكيلة تحضّر عدة مشروبات من الماكينة واحدًا بعد الآخر، وتنتظر تأكيدك قبل كل خطوة.", "A combo makes several machine drinks one after another, waiting for you before each step."),
        "combo.name": ("الاسم", "Name"),
        "combo.run": ("حضّرها", "Make it"),
        "combo.sameCup": ("اترك الكوب نفسه تحت الفوهة.", "Leave the same cup under the spout."),
        "combo.step": ("الخطوة %d", "Step %d"),
        "compareBeans.cups": ("أكواب حُضّرت به", "Cups made with it"),
        "compareBeans.needTwo": ("أضف نوعين من البن على الأقل للمقارنة.", "Add at least two beans to compare."),
        "cost.espresso": ("تكلفة الإسبريسو", "Cost of an espresso"),
        "cost.line": ("تكلفة الكوب في البيت: %@ تقريبًا.", "Cost at home: about %@."),
        "csv.export": ("صدّر السجل كجدول (CSV)", "Export history as a spreadsheet (CSV)"),
        "csv.footer": ("يُفتح في Numbers أو Excel: التاريخ والملف والمشروب والكميات والكافيين والتقييم.", "Opens in Numbers or Excel: date, profile, drink, amounts, caffeine and rating."),
        "cupCheck.intro": ("صوّر منطقة الفوهة والصينية، فيقول لك التطبيق إن كان يرى كوبًا هناك.", "Photograph the spout and tray, and the app says whether it sees a cup there."),
        "cupCheck.no": ("لا أرى كوبًا بوضوح. تحقق بيدك.", "I can't clearly see a cup. Check by hand."),
        "cupCheck.take": ("صوّر تحت الفوهة", "Photograph under the spout"),
        "cupCheck.unsure": ("تعذّر فحص الصورة. حاول مرة أخرى بإضاءة أفضل.", "The photo could not be checked. Try again with better light."),
        "cupCheck.yes": ("يبدو أن هناك كوبًا تحت الفوهة.", "There seems to be a cup under the spout."),
        "cups.add": ("إضافة كوب", "Add a cup"),
        "cups.capacity": ("السعة", "Capacity"),
        "cups.empty": ("لم تضف أكوابًا بعد.", "No cups added yet."),
        "cups.footer": ("أضف أكوابك وأحجامها، فيقول لك التطبيق أي كوب يناسب المشروب وينبهك قبل أن يفيض.", "Add your cups and their sizes, and the app says which cup suits a drink and warns before one overflows."),
        "cups.name": ("اسم الكوب (مثل: الكوب الأزرق)", "Cup name (e.g. the blue mug)"),
        "cups.saved": ("حُفظ %@.", "%@ saved."),
        "cups.tooBig": ("المشروب نحو %1$d مل، أكبر من أكبر أكوابك %2$@ (%3$d مل). اختر حجمًا أصغر.", "The drink is about %1$d ml, more than your largest cup, %2$@ (%3$d ml). Choose a smaller size."),
        "cups.useThis": ("استخدم %1$@ (المشروب نحو %2$d مل).", "Use %1$@ (the drink is about %2$d ml)."),
        "decaf.line": ("البن الحالي منزوع الكافيين.", "The beans in use are decaf."),
        "direction.down": ("الأسفل", "bottom"),
        "direction.left": ("اليسار", "left"),
        "direction.right": ("اليمين", "right"),
        "direction.up": ("الأعلى", "top"),
        "double.detail": ("ضع كوبين تحت الفوهة المزدوجة. كل كوب يأخذ الكمية المختارة.", "Put two cups under the double spout. Each cup gets the chosen amount."),
        "double.short": ("كوبان", "two cups"),
        "double.title": ("كوبان معًا (2x)", "Two cups at once (2x)"),
        "double.twoCups": ("ضع كوبين تحت الفوهة.", "Put two cups under the spout."),
        "drip.take": ("يمكنك أخذ الكوب الآن.", "You can take the cup now."),
        "drip.wait": ("انتظر قليلًا حتى تنزل آخر القطرات.", "Wait a moment for the last drops."),
        "experimental.footer": ("ميزة تجريبية: تعمل على جهازك دون إنترنت، وقد تخطئ. لا تعتمد عليها وحدها.", "Experimental: runs on your phone without internet and can be wrong. Don't rely on it alone."),
        "family.addGuest": ("أضف ضيفًا دائمًا", "Add a regular guest"),
        "family.caffeine": ("كافيين اليوم لكل شخص", "Today's caffeine per person"),
        "family.guestName": ("%@ (ضيف)", "%@ (guest)"),
        "family.isGuest": ("ضيف دائم", "Regular guest"),
        "family.lactoseFree": ("يحتاج حليبًا خاليًا من اللاكتوز", "Needs lactose-free milk"),
        "follow.profile": ("اختير ملف %@ على الماكينة.", "%@'s profile was chosen on the machine."),
        "freshness.fading": ("بدأ يفقد نكهته", "Losing its flavour"),
        "freshness.fading.detail": ("قد تحتاج طحنًا أنعم قليلًا. استهلكه قريبًا.", "It may need a slightly finer grind. Use it soon."),
        "freshness.good": ("جيد", "Good"),
        "freshness.good.detail": ("ما زال جيدًا؛ احفظه في وعاء محكم بعيدًا عن الضوء والحرارة.", "Still good; keep it airtight, away from light and heat."),
        "freshness.header": ("الطزاجة", "Freshness"),
        "freshness.peak": ("في أفضل حالاته", "At its best"),
        "freshness.peak.detail": ("بين أسبوع وشهر من التحميص: أفضل وقت للنكهة.", "One week to a month after roasting: the best time for flavour."),
        "freshness.resting": ("يرتاح بعد التحميص", "Resting after roasting"),
        "freshness.resting.detail": ("البن المحمّص حديثًا يطلق غازات؛ أفضل طعمه يبدأ بعد نحو أربعة أيام.", "Freshly roasted beans release gas; they taste best from about four days on."),
        "freshness.stale": ("قديم", "Stale"),
        "freshness.stale.detail": ("فُتح منذ أكثر من ستة أسابيع أو حُمّص منذ أكثر من ثلاثة أشهر؛ الطعم سيكون باهتًا.", "Opened over six weeks ago or roasted over three months ago; the taste will be flat."),
        "freshness.title": ("الطزاجة", "Freshness"),
        "freshness.unknown": ("غير معروفة", "Unknown"),
        "freshness.unknown.detail": ("أدخل تاريخ التحميص أو تاريخ الفتح لمعرفة الطزاجة.", "Enter the roast or opening date to see freshness."),
        "globalSearch.hint": ("يبحث في المشروبات والمفضلة والبن وأدلة العناية والقاموس والشاشات", "Searches drinks, favorites, beans, care guides, the glossary and screens"),
        "globalSearch.prompt": ("مشروب، بن، تنظيف، كلمة…", "Drink, beans, cleaning, a word…"),
        "globalSearch.title": ("ابحث في كل شيء", "Search everything"),
        "glossary.arabica.body": ("أشهر أنواع البن: نكهة ناعمة وحموضة لطيفة وكافيين أقل.", "The most common coffee: smooth flavour, gentle acidity and less caffeine."),
        "glossary.arabica.title": ("أرابيكا", "Arabica"),
        "glossary.aroma.body": ("كمية البن المطحون لكل كوب. القوة الأعلى تعني بنًا أكثر لا ماءً أقل.", "How much ground coffee goes into a cup. Stronger means more coffee, not less water."),
        "glossary.aroma.title": ("القوة (الأروما)", "Strength (aroma)"),
        "glossary.beanAdapt.body": ("ملف لكل نوع بن يضبط القوة والحرارة ويقترح درجة الطحن المناسبة له.", "A profile for each kind of beans that sets strength and temperature and suggests the right grind."),
        "glossary.beanAdapt.title": ("ملفات البن", "Bean profiles"),
        "glossary.bloom.body": ("انتفاخ البن الطازج حين يلمسه الماء الساخن لخروج الغازات؛ علامة على الطزاجة.", "Fresh coffee swelling as hot water releases its gases; a sign of freshness."),
        "glossary.bloom.title": ("التنفس", "Bloom"),
        "glossary.brewingUnit.body": ("القطعة التي تضغط البن ويمر فيها الماء. تُخرج وتُشطف بالماء أسبوعيًا دون منظفات.", "The part that presses the coffee and lets water through. Take it out and rinse it weekly, without detergent."),
        "glossary.brewingUnit.title": ("وحدة التحضير", "Brewing unit"),
        "glossary.coldBrew.body": ("قهوة تُستخلص بماء بارد ببطء، فتصبح ناعمة قليلة الحموضة.", "Coffee extracted slowly with cold water, making it smooth and low in acidity."),
        "glossary.coldBrew.title": ("القهوة الباردة المنقوعة", "Cold brew"),
        "glossary.crema.body": ("الطبقة الذهبية الرغوية فوق الإسبريسو، من زيوت البن وغازاته. كثيفة مع البن الطازج، وخفيفة مع البن القديم.", "The golden foam on an espresso, from the coffee's oils and gases. Thick with fresh beans, thin with old ones."),
        "glossary.crema.title": ("الكريما", "Crema"),
        "glossary.decaf.body": ("بن أزيل منه نحو 97 بالمئة من الكافيين. يبقى فيه قليل جدًا.", "Beans with about 97 percent of the caffeine removed. A very little remains."),
        "glossary.decaf.title": ("منزوع الكافيين", "Decaf"),
        "glossary.descaling.body": ("إذابة الكلس المتراكم من الماء داخل الماكينة بمزيل خاص. يحمي السخان ويحفظ حرارة القهوة.", "Dissolving the limescale water leaves inside the machine with a special descaler. It protects the heater and keeps coffee hot."),
        "glossary.descaling.title": ("إزالة الترسبات", "Descaling"),
        "glossary.doppio.body": ("إسبريسو مزدوج: ضعف كمية البن والماء في كوب واحد.", "A double espresso: twice the coffee and water in one cup."),
        "glossary.doppio.title": ("دوبيو", "Doppio"),
        "glossary.extraction.body": ("ما يذيبه الماء من البن. القليل يعطي طعمًا حامضًا، والكثير يعطي مرارة؛ المتوازن بينهما.", "What the water dissolves from the coffee. Too little tastes sour, too much bitter; balance is in between."),
        "glossary.extraction.title": ("الاستخلاص", "Extraction"),
        "glossary.grind.body": ("مدى نعومة البن. الأنعم يستخلص أكثر (أقوى وقد يصبح مرًا)، والأخشن أقل (أخف وقد يصبح حامضًا). تُغيَّر والمطحنة تعمل فقط.", "How fine the coffee is. Finer extracts more (stronger, may turn bitter); coarser extracts less (lighter, may turn sour). Change it only while the grinder runs."),
        "glossary.grind.title": ("درجة الطحن", "Grind setting"),
        "glossary.latteArt.body": ("رسوم على سطح القهوة بصب الرغوة الناعمة. يحتاج حليبًا مخفوقًا يدويًا عادة.", "Patterns poured with microfoam on top of coffee. It usually needs hand-frothed milk."),
        "glossary.latteArt.title": ("فن اللاتيه", "Latte art"),
        "glossary.lungo.body": ("إسبريسو طويل يمر فيه ماء أكثر عبر البن نفسه، فيصبح أخف وأكثر مرارة قليلًا.", "A long espresso: more water through the same coffee, lighter and slightly more bitter."),
        "glossary.lungo.title": ("لونغو", "Lungo"),
        "glossary.microfoam.body": ("حليب مخفوق بفقاعات صغيرة جدًا يبدو لامعًا كالحرير، كما في الفلات وايت.", "Milk frothed into tiny bubbles that look glossy like silk, as in a flat white."),
        "glossary.microfoam.title": ("الرغوة الناعمة", "Microfoam"),
        "glossary.ristretto.body": ("إسبريسو قصير بماء أقل: أكثر تركيزًا وحلاوة وأقل مرارة.", "A short espresso with less water: more concentrated and sweet, less bitter."),
        "glossary.ristretto.title": ("ريستريتو", "Ristretto"),
        "glossary.roast.body": ("الفاتح أكثر حموضة وفاكهية، والغامق أثقل وأكثر شوكولاتة ومرارة.", "Light roasts are brighter and fruitier; dark roasts heavier, more chocolatey and bitter."),
        "glossary.roast.title": ("التحميص", "Roast"),
        "glossary.robusta.body": ("بن أقوى وأمرّ وفيه كافيين أكثر تقريبًا بالضعف، ويعطي كريما كثيفة.", "Stronger, more bitter beans with roughly twice the caffeine, giving thick crema."),
        "glossary.robusta.title": ("روبوستا", "Robusta"),
        "glossary.tamping.body": ("ضغط البن قبل مرور الماء. الماكينة الأوتوماتيكية تفعله بنفسها في وحدة التحضير.", "Pressing the coffee before water flows. An automatic machine does it itself in the brewing unit."),
        "glossary.tamping.title": ("الكبس", "Tamping"),
        "glossary.waterHardness.body": ("كمية الكلس في الماء. الماء العسر يزيد الترسبات، فتحتاج الماكينة إزالة ترسبات أكثر.", "How much lime is in the water. Hard water builds more scale, so the machine needs descaling more often."),
        "glossary.waterHardness.title": ("عسر الماء", "Water hardness"),
        "grindCoach.now": ("المطحنة: أدر قرص الطحن إلى %d الآن وهي تعمل.", "Grinder: turn the dial to %d now, while it grinds."),
        "grindNote.add": ("سجّل هذه التجربة", "Save this try"),
        "grindNote.added": ("سُجّل: الطحن %1$d، التقييم %2$d من 5.", "Saved: grind %1$d, rated %2$d of 5."),
        "grindNote.best": ("أفضل طحن جربته مع هذا البن: %d", "Best grind you tried with these beans: %d"),
        "grindNote.footer": ("سجّل كل درجة طحن جربتها وكيف كان الطعم، ليتذكر التطبيق الأفضل لهذا الكيس.", "Note each grind you tried and how it tasted, so the app remembers the best for this bag."),
        "grindNote.row": ("الطحن %d", "Grind %d"),
        "grindNote.taste": ("الطعم", "Taste"),
        "grindNote.title": ("تجارب الطحن", "Grind notes"),
        "guestMenu.footer": ("أرسل أرقام ما تريد، مثلًا: 1، 3", "Reply with the numbers you'd like, e.g. 1, 3"),
        "guestMenu.footer.app": ("أرسل القائمة لضيوفك، ثم الصق ردودهم بالأسفل لتصبح طابور تحضير مرتبًا.", "Send the menu to your guests, then paste their replies below to make an ordered queue."),
        "guestMenu.found": ("وجدت %d طلبات.", "Found %d orders."),
        "guestMenu.guest": ("الضيف %d", "Guest %d"),
        "guestMenu.header": ("قائمة القهوة عند %@ ☕", "Coffee menu at %@'s ☕"),
        "guestMenu.noNumbers": ("لم أجد أرقامًا من القائمة.", "No menu numbers found."),
        "guestMenu.read": ("اقرأ الأرقام", "Read the numbers"),
        "guestMenu.replies": ("ردود الضيوف", "Guests' replies"),
        "guestMenu.reply": ("الصق الردود هنا", "Paste the replies here"),
        "guestMenu.replyFooter": ("يقبل الأرقام العربية والإنجليزية، مثل «١ و٣» أو «2,2,5».", "Arabic and Western digits both work, e.g. “١ و٣” or “2,2,5”."),
        "guestMenu.send": ("أرسل القائمة", "Send the menu"),
        "guestMenu.toQueue": ("ابدأ طابور %d مشروبات", "Start a queue of %d drinks"),
        "guestMenu.whatsapp": ("أرسلها عبر واتساب", "Send with WhatsApp"),
        "guide.preGround.intro": ("لكوب منزوع الكافيين أو بن مختلف دون تغيير بن الحاوية. ملعقة واحدة مستوية فقط في كل مرة.", "For a decaf cup or different coffee without changing the hopper. One level scoop only, each time."),
        "guide.preGround.step.1": ("شغّل الماكينة وانتظر حتى تصبح جاهزة.", "Turn the machine on and wait until it's ready."),
        "guide.preGround.step.2": ("افتح غطاء فتحة البن المطحون أعلى الماكينة.", "Open the lid of the pre-ground funnel on top."),
        "guide.preGround.step.3": ("ضع ملعقة واحدة مستوية من البن المطحون، لا أكثر؛ الزيادة تسد القمع.", "Add one level scoop of ground coffee, no more; extra clogs the funnel."),
        "guide.preGround.step.4": ("من شاشة الماكينة اختر «بن مطحون» أو رمز الملعقة، ثم اختر المشروب.", "On the machine's screen choose pre-ground (the scoop symbol), then the drink."),
        "guide.preGround.step.5": ("ضع الكوب وابدأ؛ تحضّر الماكينة كوبًا واحدًا فقط من كل ملعقة.", "Place the cup and start; each scoop makes one cup only."),
        "guide.preGround.step.6": ("لا تضع البن المطحون والماكينة مطفأة، ولا تستخدم بنًا سريع الذوبان.", "Never add ground coffee while it's off, and never use instant coffee."),
        "guide.preGround.title": ("قهوة مطحونة مسبقًا", "Pre-ground coffee"),
        "haptic.attention": ("تنبيه أو تقدم", "Alert or progress"),
        "haptic.finished": ("المشروب جاهز", "Drink ready"),
        "haptic.grinding": ("الطحن", "Grinding"),
        "haptic.milk": ("الحليب", "Milk"),
        "haptic.pouring": ("صب القهوة أو الماء", "Pouring coffee or water"),
        "haptic.problem": ("مشكلة", "A problem"),
        "haptic.started": ("بدأ التحضير", "Drink started"),
        "help.button": ("مساعدة هذه الشاشة", "Help for this screen"),
        "help.voice": ("مساعدة", "Help"),
        "helpTopic.beans.body": ("اختر البن الموجود في الماكينة ليضبط القوة والحرارة ويخبرك بالطحن. أدخل تاريخ التحميص والسعر لمعرفة الطزاجة والتكلفة.", "Choose the beans in the machine to set strength and temperature and hear the grind. Add the roast date and price to see freshness and cost."),
        "helpTopic.beans.title": ("البن", "Beans"),
        "helpTopic.brewing.body": ("زر الإيقاف دائمًا ظاهر، والنقر بإصبعين مرتين يوقف فورًا. في التشكيلات اضغط «تابع» بعد تجهيز الكوب.", "Stop is always visible, and a two-finger double-tap stops at once. In combos, press Continue once the cup is ready."),
        "helpTopic.brewing.title": ("أثناء التحضير", "While brewing"),
        "helpTopic.caffeine.body": ("كل الأرقام تقديرية. اختر حدًا موصى به، أو ابدأ خطة تخفيف تدريجي، وراقب ما بقي في جسمك قبل النوم.", "All figures are estimates. Pick a recommended limit or start a gradual plan, and watch what's left before bed."),
        "helpTopic.caffeine.title": ("الكافيين", "Caffeine"),
        "helpTopic.care.body": ("كل دليل خطوة بخطوة، والخطوات التي فيها انتظار لها مؤقت يرن حتى والهاتف مقفل.", "Every guide goes step by step, and waiting steps have a timer that rings even when the phone is locked."),
        "helpTopic.care.title": ("العناية", "Care"),
        "helpTopic.drink.body": ("كل عنصر تحكم قابل للتعديل بالتمرير لأعلى ولأسفل. الملخص يقول الوصفة كاملة مع السعرات والتكلفة والكوب المناسب.", "Every control adjusts by swiping up or down. The summary says the full recipe with calories, cost and the cup that fits."),
        "helpTopic.drink.title": ("صفحة المشروب", "Drink page"),
        "helpTopic.home.body": ("المعتاد بلمسة، وأزرار «هذه المرة فقط» لتعديله دون حفظ. النقر بإصبعين مرتين يحضّر المعتاد. الشكل بجانب الحالة: دائرة جاهزة، مثلث يحتاج انتباهًا، مربع متوقفة. زر العدسة الثاني يبحث في كل شيء.", "Your usual in one tap, with “this time only” buttons to change it without saving. A two-finger double-tap makes it. The shape by the status: circle ready, triangle needs attention, square stopped. The second search button searches everything."),
        "helpTopic.home.title": ("الرئيسية", "Home"),
        "helpTopic.hosting.body": ("أرسل القائمة المرقمة لضيوفك، ثم الصق ردودهم: يقرأ التطبيق الأرقام ويبني الطابور ويحسب البن والحليب والوقت.", "Send the numbered menu to your guests, then paste their replies: the app reads the numbers, builds the queue and works out beans, milk and time."),
        "helpTopic.hosting.title": ("الضيوف", "Guests"),
        "helpTopic.household.body": ("أضف كل شخص ومشروبه، ومن يحتاج حليبًا بلا لاكتوز. الطابور يحضّر للجميع بالترتيب الأفضل ويقول متى يجهز كل كوب.", "Add each person and their drink, and who needs lactose-free milk. The queue makes everyone's drink in the best order and says when each is ready."),
        "helpTopic.household.title": ("العائلة", "Household"),
        "helpTopic.machine.body": ("الحالة والتنبيهات والعناية القادمة. في الأدوات: سجل التنبيهات، تقرير الصيانة، المستلزمات، الحليب والماء، ودليل الشاشة بالكاميرا.", "Status, alerts and upcoming care. In tools: alert history, service report, supplies, milk and water, and the camera screen guide."),
        "helpTopic.machine.title": ("الماكينة", "Machine"),
        "helpTopic.settings.body": ("هنا الإتاحة الإضافية والتصرفات الذكية وبياناتك. يمكن قفل الإعدادات ببصمة الوجه حتى لا يغيّرها الأطفال.", "Here are more accessibility, smart behaviour and your data. Settings can be locked with Face ID so children can't change them."),
        "helpTopic.settings.title": ("الإعدادات", "Settings"),
        "history.empty": ("لا أكواب في السجل.", "No cups in the history."),
        "history.footer": ("احذف كوبًا سُجّل خطأً، أو علّمه «انسكب» فيبقى في السجل ولا يُحسب كافيينًا.", "Delete a cup logged by mistake, or mark it spilled so it stays in the history but doesn't count as caffeine."),
        "history.notFinished": ("لم يكتمل", "Not finished"),
        "history.spill": ("انسكب أو لم يُشرب", "Spilled or not drunk"),
        "history.spilled": ("انسكب", "Spilled"),
        "history.spilledName": ("%@ (انسكب)", "%@ (spilled)"),
        "history.unspill": ("شُرب فعلًا", "Was drunk"),
        "hosting.beans": ("البن", "Beans"),
        "hosting.cups": ("الأكواب", "Cups"),
        "hosting.drinks": ("كم من كل مشروب؟", "How many of each?"),
        "hosting.grounds": ("وستفرغ حاوية البن المستعمل %d مرة", "and empty the grounds %d times"),
        "hosting.groundsEmpties": ("مرات إفراغ حاوية البن المستعمل", "Grounds container empties"),
        "hosting.milk": ("نحو %d مل حليب", "about %d ml of milk"),
        "hosting.milkAmount": ("الحليب", "Milk"),
        "hosting.minutes": ("نحو %d دقيقة", "About %d min"),
        "hosting.plan": ("ما ستحتاجه", "What you'll need"),
        "hosting.refills": ("مرات تعبئة الخزان", "Tank refills"),
        "hosting.summary": ("%1$d أكواب، نحو %2$d غرام بن، ونحو %3$d دقيقة", "%1$d cups, about %2$d g of beans and about %3$d minutes"),
        "hosting.tankOK": ("خزان ممتلئ يكفي", "one full tank is enough"),
        "hosting.tankRefills": ("ستملأ الخزان %d مرة أثناء التحضير", "you'll refill the tank %d times"),
        "hosting.time": ("الوقت", "Time"),
        "hosting.water": ("الماء", "Water"),
        "hourly.at": ("الساعة %d", "%d o'clock"),
        "hourly.cups": ("الأكواب", "Cups"),
        "hourly.cupsValue": ("%d أكواب", "%d cups"),
        "hourly.hour": ("الساعة", "Hour"),
        "hourly.intro": ("متى تشرب قهوتك خلال اليوم، من آخر 30 يومًا. مع VoiceOver استخدم «الرسم البياني الصوتي» من الدوّار لسماعه.", "When you have coffee across the day, from the last 30 days. With VoiceOver, use the Audio Graph in the rotor to hear it."),
        "hourly.peak": ("أكثر ساعة: %1$d:00 (%2$d أكواب).", "Busiest hour: %1$d:00 (%2$d cups)."),
        "intent.caffeine": ("كافيين اليوم نحو %1$d من %2$d ملغ، وما زال في جسمك نحو %3$d ملغ.", "Today's caffeine is about %1$d of %2$d mg, with about %3$d mg still in your body."),
        "intent.noProfile": ("لا يوجد ملف باسم %@.", "There's no profile called %@."),
        "leftOn.body": ("لم يُحضَّر مشروب منذ ساعة. أطفئها لتوفير الطاقة.", "No drink for an hour. Turn it off to save energy."),
        "leftOn.title": ("هل ما زالت الماكينة تعمل؟", "Is the machine still on?"),
        "leftOn.turnOff": ("أطفئ الماكينة", "Turn it off"),
        "lighter.button": ("حضّر نسخة أخف", "Make a lighter version"),
        "lighter.name": ("%@ أخف", "Lighter %@"),
        "limit.adult.source": ("الهيئة الأوروبية لسلامة الغذاء وإدارة الغذاء والدواء الأمريكية: حتى 400 ملغ يوميًا.", "EFSA and the US FDA: up to 400 mg a day."),
        "limit.adult.title": ("بالغ سليم", "Healthy adult"),
        "limit.footer": ("أرقام عامة من جهات صحية، وليست نصيحة طبية. استشر طبيبك إن كانت لديك حالة صحية.", "General figures from health bodies, not medical advice. Ask your doctor if you have a health condition."),
        "limit.pregnancy.source": ("الهيئة الأوروبية لسلامة الغذاء والكلية الأمريكية لأطباء النساء: حتى 200 ملغ يوميًا.", "EFSA and ACOG: up to 200 mg a day."),
        "limit.pregnancy.title": ("الحمل والرضاعة", "Pregnancy and breastfeeding"),
        "limit.presets": ("حدود موصى بها", "Recommended limits"),
        "limit.row": ("%1$@: %2$d ملغ", "%1$@: %2$d mg"),
        "limit.set": ("صار حدّك اليومي %d ملغ.", "Your daily limit is now %d mg."),
        "limit.teen.source": ("الأكاديمية الأمريكية لطب الأطفال: لا تزيد على 100 ملغ يوميًا للمراهقين.", "American Academy of Pediatrics: no more than 100 mg a day for teenagers."),
        "limit.teen.title": ("المراهقون", "Teenagers"),
        "location.clear": ("احذف موقع الماكينة", "Delete the machine's place"),
        "location.denied": ("لم يُسمح بالموقع. فعّله لقهوتي من إعدادات iOS.", "Location wasn't allowed. Turn it on for Coffee in iOS Settings."),
        "location.done": ("حُفظ موقع الماكينة.", "The machine's place is saved."),
        "location.footer": ("مع «التبديل حسب المكان» يختار التطبيق عند فتحه الماكينة الأقرب (ضمن 200 متر). يُحفظ المكان على جهازك فقط.", "With “switch by place” on, opening the app picks the nearest machine (within 200 m). The place is kept on your phone only."),
        "location.reading": ("جارٍ تحديد الموقع…", "Finding the location…"),
        "location.saved": ("موقع هذه الماكينة محفوظ.", "This machine's place is saved."),
        "location.switched": ("أنت قرب %@؛ بدّلت إليها.", "You're near %@; switched to it."),
        "location.useHere": ("هذه الماكينة هنا: احفظ موقعي الحالي", "This machine is here: save my location"),
        "milk.almond": ("حليب اللوز", "Almond drink"),
        "milk.days": ("%d أيام", "%d days"),
        "milk.daysLeft": ("صالح لنحو %d يوم", "Good for about %d more days"),
        "milk.expired": ("الحليب المفتوح تجاوز مدته. تأكد منه قبل استخدامه.", "The opened milk is past its days. Check it before use."),
        "milk.expiry.title": ("الحليب المفتوح", "The opened milk"),
        "milk.footer": ("يُستخدم سعر الحليب في تكلفة الكوب. معظم الحليب الطازج يبقى 3–5 أيام بعد الفتح، وطويل الأجل نحو أسبوع؛ اتبع ما على العلبة.", "The milk price is used for the cost per cup. Most fresh milk keeps 3–5 days once opened, long-life about a week; follow the carton."),
        "milk.lactoseFree": ("حليب خالٍ من اللاكتوز", "Lactose-free milk"),
        "milk.lastDay": ("اليوم آخر يوم للحليب المفتوح.", "Today is the opened milk's last day."),
        "milk.lowFat": ("حليب قليل الدسم", "Low-fat milk"),
        "milk.oat": ("حليب الشوفان", "Oat drink"),
        "milk.opened.done": ("سُجّل. سأذكّرك بعد %d أيام.", "Saved. I'll remind you in %d days."),
        "milk.openedOn": ("فُتحت العلبة", "Carton opened"),
        "milk.openedToday": ("فتحت علبة حليب جديدة اليوم", "I opened new milk today"),
        "milk.price": ("سعر لتر الحليب", "Price of a litre of milk"),
        "milk.profileDefault": ("حليبي المعتاد", "My usual milk"),
        "milk.shelf": ("مدة الحليب بعد الفتح", "Milk keeps after opening"),
        "milk.soy": ("حليب الصويا", "Soy drink"),
        "milk.tip.lowFat": ("القليل الدسم يعطي رغوة كثيرة لكنها أخف قوامًا.", "Low-fat milk gives plenty of foam, but lighter."),
        "milk.tip.plant": ("الحليب النباتي المخصص للباريستا يعطي رغوة أفضل؛ العادي يعطي رغوة أقل.", "Barista plant drinks foam best; ordinary ones foam less."),
        "milk.title": ("الحليب", "Milk"),
        "milk.use": ("ضع %@ في الإبريق.", "Put %@ in the carafe."),
        "milk.whole": ("حليب كامل الدسم", "Whole milk"),
        "milkFridge.body": ("هل أعدت الحليب إلى الثلاجة؟ الحليب خارجها يفسد سريعًا.", "Did you put the milk back in the fridge? It spoils quickly outside."),
        "milkFridge.title": ("الحليب إلى الثلاجة", "Milk back in the fridge"),
        "milkFridge.toggle": ("ذكّرني بإعادة الحليب إلى الثلاجة", "Remind me to put the milk away"),
        "monthly.alarms": ("التنبيهات", "Alerts"),
        "monthly.beans": ("البن المستخدم", "Beans used"),
        "monthly.cafePrice": ("سعر القهوة في المقهى", "Café price for a coffee"),
        "monthly.caffeine": ("متوسط الكافيين اليومي", "Average daily caffeine"),
        "monthly.care": ("أعمال العناية المسجلة", "Care jobs logged"),
        "monthly.cost": ("تكلفة القهوة في البيت", "Coffee at home cost"),
        "monthly.cups": ("الأكواب", "Cups"),
        "monthly.electricityPrice": ("سعر الكيلوواط ساعة", "Price per kWh"),
        "monthly.energy": ("استهلاك تقريبي", "Approximate use"),
        "monthly.energy.footer": ("تقدير عام: التسخين والمشروبات والاستعداد. فعّل توفير الطاقة والإطفاء التلقائي لتقليله.", "A rough estimate: heating up, drinks and standby. Energy saving and auto-off reduce it."),
        "monthly.energyCost": ("التكلفة التقريبية", "Approximate cost"),
        "monthly.energyHeader": ("الكهرباء", "Electricity"),
        "monthly.kwh": ("%.1f كيلوواط ساعة", "%.1f kWh"),
        "monthly.money": ("المال", "Money"),
        "monthly.money.footer": ("التوفير = عدد الأكواب × سعر المقهى − تكلفة البن والحليب في البيت.", "Savings = cups × café price − the cost of beans and milk at home."),
        "monthly.noPrice": ("أدخل سعر الكيس ووزنه في البن لحساب التكلفة.", "Enter the bag price and weight in Beans to see the cost."),
        "monthly.savings": ("وفّرت مقارنة بالمقهى", "Saved compared with a café"),
        "monthly.top": ("الأكثر", "Most made"),
        "needs.alarms": ("تحتاج الماكينة: %@.", "The machine needs: %@."),
        "needs.nextCare": ("العناية القادمة: %1$@ بعد نحو %2$d يوم.", "Next care: %1$@ in about %2$d days."),
        "needs.nothing": ("لا تحتاج الماكينة شيئًا الآن.", "The machine needs nothing right now."),
        "notify.again": ("حضّره مرة أخرى", "Make it again"),
        "nutrition.calories": ("السعرات", "Calories"),
        "nutrition.kcal": ("نحو %d سعرة", "About %d kcal"),
        "nutrition.line": ("السعرات: نحو %d (تقدير من الحليب).", "Calories: about %d (an estimate from the milk)."),
        "offer.notNow": ("ليس الآن", "Not now"),
        "offer.title": ("مشروبك", "Your drink"),
        "office.addCup": ("أضف كوبًا لـ %@", "Add a cup for %@"),
        "office.cups": ("%1$@: %2$d أكواب", "%1$@: %2$d cups"),
        "office.footer": ("سجّل كوبًا لكل شخص بلمسة، ثم شارك الحساب في نهاية الشهر.", "Add a cup per person with one tap, then share the bill at the end of the month."),
        "office.name": ("اسم الشخص", "Person's name"),
        "office.owes": ("%1$d أكواب، عليه %2$@", "%1$d cups, owes %2$@"),
        "office.price": ("سعر الكوب", "Price per cup"),
        "office.removeCup": ("أنقص كوبًا من %@", "Remove a cup from %@"),
        "office.reset": ("ابدأ شهرًا جديدًا", "Start a new month"),
        "office.share": ("شارك الحساب", "Share the bill"),
        "office.share.header": ("حساب القهوة منذ %@:", "Coffee bill since %@:"),
        "office.share.line": ("• %1$@: %2$d أكواب = %3$@", "• %1$@: %2$d cups = %3$@"),
        "office.share.total": ("المجموع: %1$d أكواب = %2$@", "Total: %1$d cups = %2$@"),
        "office.total": ("المجموع", "Total"),
        "office.totalValue": ("%1$d أكواب = %2$@", "%1$d cups = %2$@"),
        "offline.offer": ("اتصلت الماكينة. أحضّر %@ الذي طلبته؟", "The machine is connected. Make the %@ you asked for?"),
        "offline.saved": ("الماكينة غير متصلة. حفظت %@ وسأعرضه عليك عند الاتصال.", "The machine isn't connected. I saved %@ and will offer it when it connects."),
        "offline.waiting": ("بانتظار الاتصال: %@", "Waiting to connect: %@"),
        "organizer.allTags": ("كل المفضلات", "All favorites"),
        "organizer.copyName": ("%@ (نسخة)", "%@ (copy)"),
        "organizer.duplicate": ("تكرار", "Duplicate"),
        "organizer.duplicated": ("أُضيفت %@ إلى المفضلة.", "%@ added to favorites."),
        "organizer.filter": ("تصفية", "Filter"),
        "organizer.footer": ("المس مفضلة لتضيف وسومًا (مثل: صباح، ضيوف) واختيار الحليب وملاحظة الإضافات، أو لترجع إلى نسخة سابقة. اسحب يمينًا أو استخدم الإجراءات للتكرار.", "Tap a favorite to add tags (e.g. morning, guests), choose the milk, add a note, or go back to an earlier version. Swipe or use actions to duplicate."),
        "organizer.newTag": ("وسم جديد", "New tag"),
        "organizer.tag": ("الوسم", "Tag"),
        "organizer.tagAdded": ("أُضيف الوسم %@.", "Tag %@ added."),
        "organizer.tags": ("الوسوم", "Tags"),
        "prewarm.button": ("سخّن الكوب أولًا", "Warm the cup first"),
        "prewarm.empty": ("أفرغ الماء من الكوب وأعده تحت الفوهة.", "Empty the water from the cup and put it back under the spout."),
        "prewarm.step": ("تسخين الكوب", "Warming the cup"),
        "privacy.beans": ("أنواع بن", "Beans"),
        "privacy.camera": ("الكاميرا", "Camera"),
        "privacy.cameraValue": ("تُحلَّل الصور على الجهاز ولا تُحفظ", "Analysed on the phone, never kept"),
        "privacy.confirm": ("لا يمكن التراجع عن الحذف", "Deleting can't be undone"),
        "privacy.cups": ("أكواب في السجل", "Cups in the history"),
        "privacy.delete": ("احذف", "Delete"),
        "privacy.deleted": ("حُذفت البيانات.", "Data deleted."),
        "privacy.favorites": ("مفضلات", "Favorites"),
        "privacy.health": ("الكافيين في «صحتي»", "Caffeine in Health"),
        "privacy.household": ("أفراد العائلة والضيوف", "Household and guests"),
        "privacy.icloud": ("مزامنة iCloud", "iCloud sync"),
        "privacy.location": ("الموقع", "Location"),
        "privacy.locationOn": ("مفعّل، %d أماكن محفوظة", "On, %d places saved"),
        "privacy.notes": ("ملاحظات تذوق", "Tasting notes"),
        "privacy.off": ("متوقف", "Off"),
        "privacy.on": ("مفعّل", "On"),
        "privacy.onDevice": ("على جهازك فقط", "On your phone only"),
        "privacy.onDevice.footer": ("تُحفظ مشفرة بحماية iOS ما دام الجهاز مقفلًا.", "Stored with iOS data protection while the phone is locked."),
        "privacy.servers": ("خوادم", "Servers"),
        "privacy.serversValue": ("لا يوجد — لا حساب ولا تتبع", "None — no account, no tracking"),
        "privacy.sharing": ("ما يغادر جهازك", "What leaves your phone"),
        "privacy.sharing.footer": ("iCloud وصحتي يعملان فقط إن فعّلتهما، ويستخدمان حسابك عند Apple. لا يرسل التطبيق شيئًا إلى أي خادم آخر.", "iCloud and Health work only if you turn them on, through your own Apple account. The app sends nothing to any other server."),
        "privacy.wipeAll": ("احذف كل البيانات", "Delete all data"),
        "privacy.wipeHistory": ("احذف السجل والتقييمات", "Delete history and ratings"),
        "privacy.wipeLocation": ("احذف أماكن الماكينات", "Delete machine places"),
        "profileNames.app": ("الملف %1$d في التطبيق: %2$@", "Profile %1$d in the app: %2$@"),
        "profileNames.differs": ("الاسمان مختلفان.", "The names differ."),
        "profileNames.done": ("قُرئت الأسماء من الماكينة.", "Names read from the machine."),
        "profileNames.howTo": ("لتغيير اسم على الماكينة: من شاشتها افتح الملفات الشخصية، اختر الملف ثم «تعديل الاسم». لا يرسل التطبيق الأسماء إلى الماكينة لأن هذا الأمر غير موثق ولم يُختبر.", "To rename on the machine: on its screen open the profiles, choose one, then Edit name. The app doesn't send names to the machine, because that command is undocumented and untested."),
        "profileNames.machine": ("على الماكينة: %@", "On the machine: %@"),
        "profileNames.none": ("لم تُرسل الماكينة أسماء.", "The machine sent no names."),
        "profileNames.read": ("اقرأ الأسماء من الماكينة", "Read the names from the machine"),
        "profileNames.reading": ("جارٍ القراءة…", "Reading…"),
        "profileNames.unknown": ("على الماكينة: لم يُقرأ بعد", "On the machine: not read yet"),
        "profileNames.useMachine": ("استخدم أسماء الماكينة في التطبيق", "Use the machine's names in the app"),
        "purchases.add": ("سجّل شراءً", "Log a purchase"),
        "purchases.count": ("عدد الأكياس المسجلة", "Bags logged"),
        "purchases.date": ("تاريخ الشراء", "Purchase date"),
        "purchases.empty": ("لا مشتريات مسجلة بعد.", "No purchases logged yet."),
        "purchases.footer": ("يُسجَّل كيس تلقائيًا كلما قلت إنك فتحت كيسًا جديدًا.", "A bag is logged automatically whenever you say you opened a new one."),
        "purchases.month": ("أنفقت في آخر 30 يومًا", "Spent in the last 30 days"),
        "purchases.subtitle": ("ما اشتريت وكم أنفقت", "What you bought and spent"),
        "queue.lactose": ("انتبه: %@ يحتاج حليبًا خاليًا من اللاكتوز.", "Note: %@ needs lactose-free milk."),
        "queue.plan": ("الخطة", "The plan"),
        "queue.refill": ("املأ خزان الماء قبل المشروب رقم %d.", "Refill the water tank before drink %d."),
        "queue.smartOrder": ("أفضل ترتيب (القهوة السوداء ثم الحليب الساخن ثم البارد)", "Best order (black, then hot milk, then cold)"),
        "queue.tankOK": ("ماء الخزان يكفي الجميع إن كان ممتلئًا.", "A full tank is enough for everyone."),
        "queue.wait": ("%1$@: %2$@ جاهز بعد نحو %3$d دقيقة", "%1$@: %2$@ ready in about %3$d min"),
        "ramadan.advice": ("في رمضان: اشرب القهوة بعد الإفطار بوقت، وقلّلها عند السحور لأنها تزيد العطش، واشرب الماء.", "In Ramadan: have coffee a while after iftar, keep it light at suhoor since it adds thirst, and drink water."),
        "ramadan.auto": ("تلقائي في رمضان", "Automatic in Ramadan"),
        "ramadan.chip": ("رمضان كريم: قهوتك بعد الإفطار، وخفيفة عند السحور.", "Ramadan Kareem: coffee after iftar, light at suhoor."),
        "ramadan.footer": ("في رمضان يتوقف تنبيه «تأخر الوقت» لأن القهوة تنتقل إلى المساء.", "In Ramadan the “too late” note is off, since coffee moves to the evening."),
        "ramadan.mode": ("وضع رمضان", "Ramadan mode"),
        "ramadan.off": ("متوقف", "Off"),
        "ramadan.on": ("مفعّل دائمًا", "Always on"),
        "reduction.finished": ("أتممت الخطة. حدّك الآن %d ملغ.", "Plan complete. Your limit is now %d mg."),
        "reduction.footer": ("التخفيف التدريجي يقلل الصداع والتعب. ينخفض الحد كل أسبوع حتى الهدف، وتستخدمه تنبيهات الكافيين.", "Cutting down gradually reduces headaches and tiredness. The limit drops each week until the target, and caffeine notes use it."),
        "reduction.start": ("ابدأ الخطة", "Start the plan"),
        "reduction.started": ("بدأت الخطة: من %1$d إلى %2$d ملغ خلال %3$d أسابيع.", "Plan started: from %1$d to %2$d mg over %3$d weeks."),
        "reduction.stop": ("أوقف الخطة", "Stop the plan"),
        "reduction.target": ("الهدف اليومي", "Daily target"),
        "reduction.thisWeek": ("حد هذا الأسبوع", "This week's limit"),
        "reduction.title": ("خطة تخفيف تدريجي", "Gradual cut-down plan"),
        "reduction.week": ("الأسبوع", "Week"),
        "reduction.weekOf": ("%1$d من %2$d", "%1$d of %2$d"),
        "reduction.weeks": ("عدد الأسابيع", "Weeks"),
        "report.alarms": ("التنبيهات في آخر 30 يومًا:", "Alerts in the last 30 days:"),
        "report.bought": ("تاريخ الشراء: %@", "Bought on: %@"),
        "report.care": ("آخر عناية:", "Last care:"),
        "report.counter.coffee": ("مشروبات القهوة: %d", "Coffee drinks: %d"),
        "report.counter.descale": ("مرات إزالة الترسبات: %d", "Descalings: %d"),
        "report.counter.filter": ("مرات تغيير الفلتر: %d", "Filter changes: %d"),
        "report.counter.milk": ("مشروبات الحليب: %d", "Milk drinks: %d"),
        "report.counter.water": ("الماء المستخدم: نحو %d لتر", "Water used: about %d litres"),
        "report.counters": ("عدادات الماكينة:", "Machine counters:"),
        "report.footer": ("أُعدّ بتطبيق قهوتي %@. العدادات من الماكينة؛ باقي البيانات من سجل التطبيق.", "Made with Coffee %@. Counters come from the machine; the rest from the app's log."),
        "report.intro": ("أرسل هذا التقرير إلى مركز الصيانة أو احتفظ به. يُعدّ على جهازك ولا يُرسل إلا حين تشاركه أنت.", "Send this to a service centre or keep it. It is made on your phone and sent only when you share it."),
        "report.machine": ("الماكينة: %1$@ (%2$@)", "Machine: %1$@ (%2$@)"),
        "report.never": ("لم تُسجّل", "Not logged"),
        "report.none": ("لا شيء", "None"),
        "report.serial": ("الرقم التسلسلي: %@", "Serial number: %@"),
        "report.share": ("شارك التقرير", "Share the report"),
        "report.title": ("تقرير صيانة — قهوتي", "Service report — Coffee"),
        "report.warranty": ("ينتهي الضمان: %@", "Warranty ends: %@"),
        "reportProblem.footer": ("يضم البلاغ معلومات تقنية فقط (الإصدار، الاتصال، التنبيهات). أنت تختار أين ترسله؛ لا يُرسل شيء تلقائيًا.", "The report holds technical details only (version, connection, alerts). You choose where to send it; nothing is sent automatically."),
        "reportProblem.header": ("بلاغ مشكلة في تطبيق قهوتي:", "Problem report for the Coffee app:"),
        "reportProblem.placeholder": ("صف المشكلة بكلماتك", "Describe the problem in your words"),
        "reportProblem.share": ("أرسل البلاغ", "Send the report"),
        "reportProblem.what": ("ماذا حدث؟", "What happened?"),
        "resume.offer": ("تم إصلاح المشكلة. أحضّر %@ مرة أخرى؟", "The problem is fixed. Make the %@ again?"),
        "resume.saved": ("توقف المشروب بسبب تنبيه. أصلحه وسأعرض عليك إكماله.", "The drink stopped because of an alert. Fix it and I'll offer to make it again."),
        "screen.academy": ("أكاديمية الباريستا", "Barista academy"),
        "screen.accessibility3": ("إتاحة إضافية", "More accessibility"),
        "screen.alarmHistory": ("سجل التنبيهات", "Alert history"),
        "screen.backup": ("النسخ الاحتياطي والتصدير", "Backup and export"),
        "screen.children": ("ملفات الأطفال والقفل", "Children and lock"),
        "screen.combos": ("تشكيلاتي", "My combos"),
        "screen.compareBeans": ("قارن البن", "Compare beans"),
        "screen.cupCheck": ("هل الكوب في مكانه؟", "Is the cup in place?"),
        "screen.cups": ("أكوابي", "My cups"),
        "screen.glossary": ("قاموس القهوة", "Coffee glossary"),
        "screen.guestMenu": ("قائمة الضيوف", "Guest menu"),
        "screen.historyEditor": ("تعديل السجل", "Edit history"),
        "screen.hosting": ("مخطط الاستضافة", "Hosting planner"),
        "screen.hourly": ("قهوتك خلال اليوم", "Your coffee by hour"),
        "screen.milk": ("الحليب والماء", "Milk and water"),
        "screen.monthly": ("تقرير الشهر", "Monthly report"),
        "screen.office": ("حساب المكتب", "Office tally"),
        "screen.organizer": ("تنظيم المفضلة", "Organize favorites"),
        "screen.privacy": ("لوحة الخصوصية", "Privacy dashboard"),
        "screen.profileNames": ("أسماء الملفات على الماكينة", "Profile names on the machine"),
        "screen.purchases": ("مشتريات البن", "Bean purchases"),
        "screen.reduction": ("خطة تخفيف الكافيين", "Caffeine cut-down plan"),
        "screen.report": ("أبلغ عن مشكلة", "Report a problem"),
        "screen.serviceReport": ("تقرير الصيانة", "Service report"),
        "screen.supplies": ("المستلزمات", "Supplies"),
        "screen.teaTimer": ("مؤقت الشاي", "Tea timer"),
        "screen.touchGuide": ("دليل لمس الشاشة بالكاميرا", "Touch screen guide (camera)"),
        "screen.travel": ("قبل السفر أو النقل", "Before travel or moving"),
        "screen.voPractice": ("تدرّب على إيماءات VoiceOver", "Practise VoiceOver gestures"),
        "screen.whatsNew": ("الجديد في قهوتي 3", "What's new in Coffee 3"),
        "search.kind.bean": ("بن", "Beans"),
        "search.kind.drink": ("مشروب", "Drink"),
        "search.kind.favorite": ("مفضلة", "Favorite"),
        "search.kind.glossary": ("قاموس", "Glossary"),
        "search.kind.guide": ("دليل عناية", "Care guide"),
        "search.kind.screen": ("شاشة", "Screen"),
        "search.kind.signature": ("وصفة مميزة", "Signature recipe"),
        "search.nothing": ("لا نتائج.", "No results."),
        "search.results": ("%d نتيجة", "%d results"),
        "sequence.cancel": ("ألغِ بقية الخطوات", "Cancel the remaining steps"),
        "sequence.continue": ("تابع: %@", "Continue: %@"),
        "sequence.next": ("%1$@ التالي: %2$@. اضغط «تابع» عندما تكون جاهزًا.", "%1$@ Next: %2$@. Press Continue when ready."),
        "settings.cupPrewarm": ("اعرض «سخّن الكوب أولًا»", "Offer “warm the cup first”"),
        "settings.followProfile": ("اتبع الملف المختار على الماكينة", "Follow the profile chosen on the machine"),
        "settings.leftOn": ("ذكّرني إن بقيت الماكينة تعمل ساعة دون مشروب", "Remind me if the machine stays on an hour without a drink"),
        "settings.locationSwitch": ("بدّل الماكينة حسب المكان", "Switch machine by place"),
        "settings.offlineQueue": ("احفظ الطلب إن لم تكن الماكينة متصلة", "Keep the order if the machine isn't connected"),
        "settings.quietReconnect": ("إعادة اتصال هادئة", "Quiet reconnect"),
        "settings.v3.accessibility": ("إتاحة إضافية", "More accessibility"),
        "settings.v3.data": ("بياناتك", "Your data"),
        "settings.v3.learn": ("تعلّم ومساعدة", "Learn and help"),
        "settings.v3.smart": ("تصرفات ذكية", "Smart behaviour"),
        "settings.v3.smart.footer": ("الطابور دون اتصال يحفظ مشروبك إن لم تكن الماكينة متصلة ويعرضه عند الاتصال. إعادة الاتصال الهادئة لا تعلن انقطاعًا قصيرًا. متابعة ملف الماكينة تعمل فقط حين تُرسل الماكينة رقم الملف.", "The offline queue keeps your drink if the machine isn't connected and offers it on connect. Quiet reconnect doesn't announce short drops. Following the machine's profile works only when the machine reports it."),
        "settings.waterReminder": ("ذكّرني بالماء بعد القهوة", "Remind me to drink water after coffee"),
        "settingsLock.body": ("افتحها ببصمة الوجه أو اللمس أو رمز الجهاز.", "Unlock with Face ID, Touch ID or the device passcode."),
        "settingsLock.failed": ("لم يُفتح القفل. حاول مرة أخرى.", "Not unlocked. Try again."),
        "settingsLock.footer": ("يمنع الأطفال من تغيير الملفات أو إلغاء قيود الكافيين.", "Stops children changing profiles or removing caffeine limits."),
        "settingsLock.reason": ("لفتح إعدادات قهوتي", "To open Coffee's settings"),
        "settingsLock.title": ("الإعدادات مقفلة", "Settings are locked"),
        "settingsLock.toggle": ("اقفل الإعدادات ببصمة الوجه أو الرمز", "Lock settings with Face ID or passcode"),
        "settingsLock.unlock": ("افتح الإعدادات", "Unlock settings"),
        "shape.attention": ("مثلث: تحتاج انتباهًا", "Triangle: needs attention"),
        "shape.ready": ("دائرة: جاهزة", "Circle: ready"),
        "shape.stopped": ("مربع: متوقفة حتى تُصلح المشكلة", "Square: stopped until the problem is fixed"),
        "shape.unknown": ("معيّن: الحالة غير معروفة", "Diamond: status unknown"),
        "shopping.buyAgain": ("تحب هذا البن؛ بقي نحو %d كوب", "You like these; about %d cups left"),
        "shopping.milkCleaner": ("منظف دورة الحليب", "Milk circuit cleaner"),
        "shopping.noneLeft": ("لم يبقَ شيء", "None left"),
        "signal.dbm": ("%d ديسيبل ميلي واط", "%d dBm"),
        "signal.strength.advice": ("اقترب من الماكينة أو أبعد العوائق المعدنية لاتصال أثبت.", "Move closer to the machine or away from metal for a steadier link."),
        "signal.strength.fair": ("متوسطة", "Fair"),
        "signal.strength.label": ("إشارة البلوتوث: %@", "Bluetooth signal: %@"),
        "signal.strength.strong": ("قوية", "Strong"),
        "signal.strength.weak": ("ضعيفة", "Weak"),
        "stars.value": ("%d من 5", "%d of 5"),
        "status.brewing": ("يُحضَّر %1$@، %2$d%%", "Making %1$@, %2$d%%"),
        "stepTimer.done": ("انتهى وقت الخطوة", "Step time is up"),
        "stepTimer.start": ("مؤقت %d دقيقة لهذه الخطوة", "%d-minute timer for this step"),
        "stepTimer.started": ("بدأ مؤقت الخطوة: %d دقيقة.", "Step timer started: %d minutes."),
        "supplies.descaler": ("عبوات مزيل الترسبات", "Descaler bottles"),
        "supplies.filters": ("فلاتر الماء", "Water filters"),
        "supplies.footer": ("عندما تسجل إزالة الترسبات أو تغيير الفلتر يُنقص التطبيق واحدًا تلقائيًا، وما ينفد يظهر في قائمة المشتريات.", "Logging descaling or a filter change subtracts one automatically, and anything that runs out joins the shopping list."),
        "supplies.milkCleaner": ("منظف دورة الحليب", "Milk circuit cleaner"),
        "tank.filledNow": ("ملأت الخزان بماء جديد الآن", "I just filled the tank with fresh water"),
        "tank.filledOn": ("آخر تعبئة للخزان", "Tank last filled"),
        "tank.reminder": ("نبّهني إن بقي الماء في الخزان أكثر من يومين", "Remind me if the tank water is over two days old"),
        "tank.stale": ("الماء في الخزان منذ %d أيام؛ بدّله بماء جديد لطعم أفضل.", "The tank water is %d days old; refresh it for better taste."),
        "tea.advice.black": ("ثلاث إلى خمس دقائق بماء مغلي تقريبًا.", "Three to five minutes in nearly boiling water."),
        "tea.advice.green": ("دقيقتان إلى ثلاث، بماء أقل حرارة؛ النقع الطويل يجعله مرًا.", "Two to three minutes, with cooler water; longer makes it bitter."),
        "tea.advice.herbal": ("خمس إلى سبع دقائق؛ لا يصبح مرًا بسهولة.", "Five to seven minutes; it rarely turns bitter."),
        "tea.advice.rooibos": ("خمس إلى سبع دقائق؛ خالٍ من الكافيين.", "Five to seven minutes; caffeine-free."),
        "tea.advice.white": ("ثلاث دقائق تقريبًا بماء دافئ لا مغلٍ.", "About three minutes in hot, not boiling, water."),
        "tea.black": ("شاي أسود", "Black tea"),
        "tea.done.body": ("أخرج كيس %@ الآن.", "Take the %@ out now."),
        "tea.done.title": ("الشاي جاهز", "Your tea is ready"),
        "tea.green": ("شاي أخضر", "Green tea"),
        "tea.herbal": ("أعشاب", "Herbal"),
        "tea.kind": ("نوع الشاي", "Kind of tea"),
        "tea.minutesLeft": ("بقيت %d دقيقة.", "%d minutes left."),
        "tea.rooibos": ("رويبوس", "Rooibos"),
        "tea.start": ("ابدأ مؤقت %d دقائق", "Start a %d-minute timer"),
        "tea.started": ("بدأ المؤقت: %d دقائق.", "Timer started: %d minutes."),
        "tea.stop": ("أوقف المؤقت", "Stop the timer"),
        "tea.white": ("شاي أبيض", "White tea"),
        "touchGuide.failed": ("تعذّر تحليل الصورة. حاول مرة أخرى.", "The photo could not be read. Try again."),
        "touchGuide.intro": ("ضع إصبعك قرب زر على شاشة الماكينة دون أن تضغط، ثم صوّر. يقول لك التطبيق الكلمة التي تحت إصبعك وما حولها.", "Hold a finger near a button on the machine's screen without pressing, then take a photo. The app says which word is under your finger and what is around it."),
        "touchGuide.neighbour": ("%1$@ إلى %2$@", "%1$@ to the %2$@"),
        "touchGuide.noFinger": ("لم أجد إصبعًا. الكلمات على الشاشة: %@", "No finger found. Words on the screen: %@"),
        "touchGuide.noText": ("لم أجد نصًا على الشاشة. صوّرها مباشرة وبإضاءة أقل انعكاسًا.", "No text found. Photograph the screen straight on, with less glare."),
        "touchGuide.take": ("صوّر الشاشة وإصبعك", "Photograph the screen and your finger"),
        "touchGuide.under": ("إصبعك على: %@", "Your finger is on: %@"),
        "travel.footer": ("أنجزت %1$d من %2$d.", "%1$d of %2$d done."),
        "travel.item.1": ("أفرغ خزان الماء وجففه.", "Empty and dry the water tank."),
        "travel.item.2": ("أفرغ حاوية البن المستعمل وصينية التنقيط ونظفهما.", "Empty and clean the grounds container and the drip tray."),
        "travel.item.3": ("نظّف إبريق الحليب وفكّه واحفظه جافًا.", "Clean the milk carafe, take it apart and store it dry."),
        "travel.item.4": ("أخرج وحدة التحضير واشطفها ودعها تجف.", "Take out the brewing unit, rinse it and let it dry."),
        "travel.item.5": ("استهلك البن أو أفرغ الحاوية إن ستغيب أكثر من أسبوعين.", "Use up or empty the beans if you'll be away more than two weeks."),
        "travel.item.6": ("أطفئ الماكينة وافصل القابس.", "Turn the machine off and unplug it."),
        "travel.item.7": ("لا تتركها في مكان قد يتجمد فيه الماء؛ الماء المتجمد يتلف الدوائر. اسأل الصيانة إن لزم تفريغها.", "Don't leave it where water could freeze; frozen water damages the circuits. Ask a service centre if it needs draining."),
        "travel.item.8": ("انقلها في علبتها الأصلية أو بحماية جيدة، واقفة دائمًا.", "Move it in its original box or well padded, always upright."),
        "tweak.bigger": ("أكبر", "Bigger"),
        "tweak.hotter": ("أسخن", "Hotter"),
        "tweak.label": ("%1$@ هذه المرة: %2$@", "%1$@ this time: %2$@"),
        "tweak.milder": ("أخف", "Milder"),
        "tweak.stronger": ("أقوى", "Stronger"),
        "tweak.title": ("هذه المرة فقط", "This time only"),
        "versions.footer": ("المس نسخة لترجع إليها؛ تُحفظ الحالية كنسخة فلا يضيع شيء.", "Tap a version to go back to it; the current one is kept as a version, so nothing is lost."),
        "versions.none": ("لا نسخ سابقة بعد. تُحفظ نسخة كلما عدّلت هذه المفضلة.", "No earlier versions yet. One is kept each time you change this favorite."),
        "versions.restore.hint": ("يرجع المفضلة إلى هذه الإعدادات", "Puts the favorite back to these settings"),
        "versions.restored": ("رجعت %@ إلى النسخة المختارة.", "%@ is back to the chosen version."),
        "versions.title": ("النسخ السابقة", "Earlier versions"),
        "vo.allDone": ("أحسنت! أتقنت كل الإيماءات.", "Well done! You know every gesture."),
        "vo.intro": ("تدرّب على الإيماءات التي يستخدمها التطبيق. كل تمرين يُعلن عند نجاحه.", "Practise the gestures the app uses. Each exercise announces when you get it."),
        "vo.lesson.0.body": ("حرّك التركيز إلى الزر ثم انقر مرتين في أي مكان على الشاشة.", "Move focus to the button, then double-tap anywhere on the screen."),
        "vo.lesson.0.button": ("انقر هنا مرتين", "Double-tap here"),
        "vo.lesson.0.title": ("النقر المزدوج", "Double-tap"),
        "vo.lesson.1.body": ("ركّز على القوة واسحب بإصبع واحد لأعلى حتى تصل إلى 5. هكذا تغيّر الكميات في صفحة المشروب.", "Focus the strength and swipe up with one finger until it reaches 5. That's how amounts change on a drink page."),
        "vo.lesson.1.title": ("التعديل لأعلى ولأسفل", "Adjust up and down"),
        "vo.lesson.2.body": ("انقر بإصبعين مرتين. في الرئيسية يحضّر المعتاد، وأثناء التحضير يوقف المشروب.", "Double-tap with two fingers. On Home it makes your usual; while brewing it stops the drink."),
        "vo.lesson.2.title": ("النقر بإصبعين مرتين", "Two-finger double-tap"),
        "vo.lesson.2.try": ("جرّب الآن بإصبعين", "Try it now with two fingers"),
        "vo.lesson.3.body": ("ارسم حرف Z بإصبعين لتغلق نافذة أو ترجع.", "Draw a Z with two fingers to close a sheet or go back."),
        "vo.lesson.3.title": ("إيماءة الرجوع", "The escape gesture"),
        "vo.lesson.3.try": ("جرّب إيماءة Z الآن", "Try the Z gesture now"),
        "vo.lesson.4.action": ("تجربة إجراء", "Try an action"),
        "vo.lesson.4.body": ("على هذا العنصر اسحب لأعلى أو لأسفل لتسمع الإجراءات، ثم انقر مرتين على «تجربة إجراء».", "On this item, swipe up or down to hear the actions, then double-tap “Try an action”."),
        "vo.lesson.4.item": ("عنصر بإجراءات", "An item with actions"),
        "vo.lesson.4.title": ("الإجراءات", "Actions"),
        "vo.passed": ("صحيح!", "Correct!"),
        "vo.progress": ("التقدم", "Progress"),
        "vo.progress.value": ("%1$d من %2$d", "%1$d of %2$d"),
        "vo.strength": ("القوة %d", "Strength %d"),
        "voice.next": ("التالي", "Next"),
        "voice.ready": ("الكوب جاهز", "Cup ready"),
        "voice.search": ("بحث", "Search"),
        "voice.stop": ("أوقف", "Stop"),
        "voice.usual": ("المعتاد", "Usual"),
        "warranty.notify.body": ("إن كانت هناك مشكلة فاطلب الصيانة قبل انتهاء الضمان. تقرير الصيانة جاهز في تبويب الماكينة.", "If anything is wrong, ask for service before the warranty ends. The service report is in the Machine tab."),
        "warranty.notify.title": ("ضمان %@ ينتهي بعد شهر", "%@'s warranty ends in a month"),
        "water.bottled": ("ماء معبأ", "Bottled water"),
        "water.footer": ("الماء الألطف يؤخر الترسبات، فيعدّل التطبيق موعد إزالتها. ماء الخزان الذي بقي أيامًا يفقد طعمه؛ بدّله بماء جديد.", "Softer water slows scale, so the app adjusts when descaling is due. Water left in the tank for days tastes flat; replace it."),
        "water.jugFilter": ("إبريق ترشيح", "Filter jug"),
        "water.reminder": ("اشرب كوب ماء مع قهوتك.", "Have a glass of water with your coffee."),
        "water.reminderToggle": ("ذكّرني بكوب ماء بعد القهوة", "Remind me to drink water after coffee"),
        "water.softened": ("ماء منقّى بجهاز تحلية", "Softened water"),
        "water.source": ("مصدر الماء", "Water source"),
        "water.tap": ("ماء الصنبور", "Tap water"),
        "water.title": ("الماء", "Water"),
        "whatsNew.1.body": ("اهتزاز لكل مرحلة، صياغة لبرايل، اختيار الصوت وسرعته، هزّ الهاتف لسماع الحالة، وشاشة تحضير عملاقة.", "Vibration for every phase, braille wording, voice and rate, shake for status and a giant brewing screen."),
        "whatsNew.1.title": ("إتاحة أعمق", "Deeper accessibility"),
        "whatsNew.2.body": ("حضّر كوبين بالفوهة المزدوجة، وسجّل أكوابك ليقول لك أيها يناسب المشروب.", "Make two cups from the double spout, and save your cups to hear which one fits."),
        "whatsNew.2.title": ("كوبان معًا وأكوابك", "Two cups and your cups"),
        "whatsNew.3.body": ("إن توقف المشروب لنفاد الماء أو البن، يعرض إكماله بعد الإصلاح؛ وإن لم تكن الماكينة متصلة يحفظ الطلب.", "If a drink stops for water or beans, it offers to finish once fixed; if the machine isn't connected, it keeps the order."),
        "whatsNew.3.title": ("يكمل ما بدأ", "Picks up where it stopped"),
        "whatsNew.4.body": ("الطزاجة، التكلفة لكل كوب، منزوع الكافيين، الباركود، تجارب الطحن، المشتريات ومقارنة الأكياس.", "Freshness, cost per cup, decaf, barcode, grind notes, purchases and comparing bags."),
        "whatsNew.4.title": ("بن أذكى", "Smarter beans"),
        "whatsNew.5.body": ("قائمة ترسلها لضيوفك وتقرأ ردودهم، مخطط استضافة، حساب المكتب، وترتيب أذكى للطابور.", "A menu to send guests that reads their replies, a hosting planner, an office tally and a smarter queue."),
        "whatsNew.5.title": ("الضيوف والمكتب", "Guests and the office"),
        "whatsNew.6.body": ("ما بقي في جسمك، حدود موصى بها، خطة تخفيف تدريجي، وضع رمضان، ورسم بياني صوتي لساعات اليوم.", "What's still in your body, recommended limits, a cut-down plan, Ramadan mode and an audio graph of your day."),
        "whatsNew.6.title": ("كافيين أوضح", "Clearer caffeine"),
        "whatsNew.7.body": ("سجل التنبيهات، تقرير صيانة، مخزون المستلزمات، تذكير الحليب وماء الخزان، ومؤقتات داخل الأدلة.", "Alert history, a service report, supplies, milk and tank-water reminders, and timers inside the guides."),
        "whatsNew.7.title": ("العناية بالماكينة", "Machine care"),
        "whatsNew.8.body": ("نسخة احتياطية، تصدير جدول، تعديل السجل، لوحة الخصوصية، قفل الإعدادات وملفات الأطفال.", "Backup, spreadsheet export, history editing, a privacy dashboard, a settings lock and children's profiles."),
        "whatsNew.8.title": ("بياناتك بيدك", "Your data, yours"),
        "whatsNew.continue": ("ابدأ", "Get started"),
        "whichBean.footer": ("نفد البن وأعدت تعبئته. اختر البن الذي وضعته ليضبط التطبيق الطحن والقوة.", "The beans ran out and you refilled. Choose the beans you added so the app sets grind and strength."),
        "whichBean.newBag": ("كيس جديد من البن نفسه", "A new bag of the same beans"),
        "whichBean.same": ("البن نفسه، دون تغيير", "The same beans, no change"),
        "whichBean.title": ("أي بن وضعت؟", "Which beans did you add?"),
    ]
}
