import Foundation

// Interface text, Arabic first. Keys are checked by Scripts/validate_strings.py:
// every key used in code must exist here, with both languages and matching
// format specifiers.
enum Strings {
    static let table: [String: (ar: String, en: String)] = [
        // MARK: Tabs and common
        "tab.home": ("الرئيسية", "Home"),
        "tab.drinks": ("المشروبات", "Drinks"),
        "tab.machine": ("الماكينة", "Machine"),
        "tab.settings": ("الإعدادات", "Settings"),
        "list.separator": ("، ", ", "),
        "sentence.separator": (". ", ". "),
        "alert.title": ("تنبيه", "Notice"),
        "action.ok": ("حسنًا", "OK"),
        "action.cancel": ("إلغاء", "Cancel"),
        "action.save": ("حفظ", "Save"),
        "action.done": ("تم", "Done"),
        "action.edit": ("تعديل", "Edit"),
        "action.delete": ("حذف", "Delete"),
        "action.stop": ("إيقاف", "Stop"),
        "action.tryAgain": ("حاول مرة أخرى", "Try again"),
        "action.brewNow": ("حضّر الآن", "Make it now"),
        "action.addFavorite": ("أضف إلى المفضلة", "Add to favorites"),
        "action.alreadyFavorite": ("موجود في المفضلة، أضف نسخة أخرى", "Already a favorite, add another copy"),
        "action.connect": ("اتصل بالماكينة", "Connect to the machine"),
        "action.reconnect": ("أعد الاتصال", "Reconnect"),
        "action.turnOn": ("شغّل الماكينة", "Turn the machine on"),
        "action.howToFix": ("كيف أعالج: %@", "How to fix: %@"),
        "action.openGuide": ("افتح دليل: %@", "Open guide: %@"),

        // MARK: Units and controls
        "unit.ml": ("%d مل", "%d ml"),
        "unit.seconds": ("%d ثانية", "%d seconds"),
        "unit.percent": ("%d%%", "%d%%"),
        "control.increase": ("زيادة %@", "Increase %@"),
        "control.decrease": ("إنقاص %@", "Decrease %@"),
        "control.adjustHint": ("اسحب لأعلى أو لأسفل للتغيير. الإعدادات السريعة في قائمة الإجراءات.", "Swipe up or down to change. Quick presets are in the Actions rotor."),
        "control.levelValue": ("%1$@، المستوى %2$d من %3$d", "%1$@, level %2$d of %3$d"),
        "preset.small": ("صغير", "Small"),
        "preset.standard": ("عادي", "Standard"),
        "preset.large": ("كبير", "Large"),

        // MARK: Parameters
        "param.coffee": ("كمية القهوة", "Coffee amount"),
        "param.water": ("كمية الماء الساخن", "Hot water amount"),
        "param.milk": ("كمية الحليب", "Milk amount"),
        "param.aroma": ("قوة القهوة", "Strength"),
        "param.temperature": ("حرارة القهوة", "Coffee temperature"),
        "param.milkFirst": ("الحليب أولًا", "Milk first"),
        "param.milkFirst.detail": ("يُصب الحليب في الكوب قبل القهوة.", "Pours the milk into the cup before the coffee."),
        "aroma.extraMild": ("خفيفة جدًا", "Extra mild"),
        "aroma.mild": ("خفيفة", "Mild"),
        "aroma.normal": ("متوسطة", "Medium"),
        "aroma.strong": ("قوية", "Strong"),
        "aroma.extraStrong": ("قوية جدًا", "Extra strong"),
        "temperature.low": ("منخفضة", "Low"),
        "temperature.medium": ("متوسطة", "Medium"),
        "temperature.high": ("عالية", "High"),
        "temperature.veryHigh": ("عالية جدًا", "Very high"),
        "summary.coffee": ("قهوة %d مل", "%d ml coffee"),
        "summary.water": ("ماء ساخن %d مل", "%d ml hot water"),
        "summary.milk": ("حليب %d ثانية", "%d seconds of milk"),
        "summary.temperature": ("حرارة %@", "%@ temperature"),
        "summary.milkFirst": ("الحليب أولًا", "milk first"),
        "summary.format": ("%1$@: %2$@", "%1$@: %2$@"),

        // MARK: Categories and drinks
        "category.coffee": ("قهوة", "Coffee"),
        "category.milk": ("بالحليب", "With milk"),
        "category.cold": ("مشروبات باردة", "Cold drinks"),
        "category.other": ("مشروبات أخرى", "Other drinks"),
        "drink.espresso.name": ("إسبريسو", "Espresso"),
        "drink.espresso.summary": ("قهوة مركزة صغيرة بطبقة كريما ذهبية.", "A short, concentrated coffee with golden crema."),
        "drink.ristretto.name": ("ريستريتو", "Ristretto"),
        "drink.ristretto.summary": ("إسبريسو أقصر وأكثف بطعم أقوى.", "A shorter, more intense espresso."),
        "drink.espressoDouble.name": ("إسبريسو مزدوج", "Double espresso"),
        "drink.espressoDouble.summary": ("جرعتا إسبريسو في كوب واحد.", "Two espresso shots in one cup."),
        "drink.doppioPlus.name": ("دوبيو بلس", "Doppio+"),
        "drink.doppioPlus.summary": ("قهوة مزدوجة قوية جدًا بكمية أكبر من البن.", "An extra-strong double coffee with more ground coffee."),
        "drink.coffee.name": ("قهوة", "Coffee"),
        "drink.coffee.summary": ("كوب قهوة متوسط الحجم بطعم متوازن.", "A medium cup of balanced coffee."),
        "drink.longCoffee.name": ("قهوة طويلة", "Long coffee"),
        "drink.longCoffee.summary": ("كوب قهوة كبير يُستخلص ببطء.", "A large cup of slowly extracted coffee."),
        "drink.americano.name": ("أمريكانو", "Americano"),
        "drink.americano.summary": ("إسبريسو مع ماء ساخن.", "Espresso with hot water."),
        "drink.longBlack.name": ("لونغ بلاك", "Long black"),
        "drink.longBlack.summary": ("ماء ساخن أولًا ثم إسبريسو مزدوج فوقه.", "Hot water first, then a double espresso on top."),
        "drink.travelMug.name": ("كوب السفر", "Travel mug"),
        "drink.travelMug.summary": ("قهوة بكمية كبيرة لكوب السفر.", "A large coffee for your travel mug."),
        "drink.cappuccino.name": ("كابتشينو", "Cappuccino"),
        "drink.cappuccino.summary": ("إسبريسو مع حليب مرغّى ورغوة كثيفة.", "Espresso with frothed milk and thick foam."),
        "drink.cappuccinoPlus.name": ("كابتشينو بلس", "Cappuccino+"),
        "drink.cappuccinoPlus.summary": ("كابتشينو بقهوة أكثر وطعم أقوى.", "A cappuccino with more coffee and a stronger taste."),
        "drink.cappuccinoMix.name": ("كابتشينو ميكس", "Cappuccino mix"),
        "drink.cappuccinoMix.summary": ("الحليب أولًا ثم القهوة، فيمتزجان في الكوب.", "Milk first, then coffee, blended in the cup."),
        "drink.latteMacchiato.name": ("لاتيه ماكياتو", "Latte macchiato"),
        "drink.latteMacchiato.summary": ("حليب ساخن ورغوة تعلوهما طبقة إسبريسو.", "Hot milk and foam topped with espresso."),
        "drink.caffeLatte.name": ("كافيه لاتيه", "Caffè latte"),
        "drink.caffeLatte.summary": ("إسبريسو مع كمية كبيرة من الحليب الساخن.", "Espresso with plenty of hot milk."),
        "drink.flatWhite.name": ("فلات وايت", "Flat white"),
        "drink.flatWhite.summary": ("إسبريسو مع حليب ناعم ورغوة خفيفة.", "Espresso with silky milk and light foam."),
        "drink.espressoMacchiato.name": ("إسبريسو ماكياتو", "Espresso macchiato"),
        "drink.espressoMacchiato.summary": ("إسبريسو مع لمسة من رغوة الحليب.", "Espresso with a touch of milk foam."),
        "drink.cortado.name": ("كورتادو", "Cortado"),
        "drink.cortado.summary": ("إسبريسو مع مقدار مساوٍ من الحليب الدافئ.", "Espresso cut with an equal amount of warm milk."),
        "drink.hotMilk.name": ("حليب ساخن", "Hot milk"),
        "drink.hotMilk.summary": ("حليب مرغّى ساخن بلا قهوة.", "Hot frothed milk, no coffee."),
        "drink.overIce.name": ("قهوة على الثلج", "Coffee over ice"),
        "drink.overIce.summary": ("قهوة قوية تُصب فوق مكعبات الثلج.", "Strong coffee poured over ice cubes."),
        "drink.icedCappuccino.name": ("كابتشينو مثلج", "Iced cappuccino"),
        "drink.icedCappuccino.summary": ("إسبريسو وحليب بارد مرغّى فوق الثلج.", "Espresso and cold frothed milk over ice."),
        "drink.icedLatteMacchiato.name": ("لاتيه ماكياتو مثلج", "Iced latte macchiato"),
        "drink.icedLatteMacchiato.summary": ("حليب بارد ورغوة باردة وإسبريسو فوق الثلج.", "Cold milk, cold foam and espresso over ice."),
        "drink.coldMilk.name": ("حليب بارد مرغّى", "Cold frothed milk"),
        "drink.coldMilk.summary": ("رغوة حليب باردة بلا قهوة.", "Cold milk foam, no coffee."),
        "drink.hotWater.name": ("ماء ساخن", "Hot water"),
        "drink.hotWater.summary": ("ماء ساخن للشاي أو الأعشاب.", "Hot water for tea or infusions."),
        "drink.tea.name": ("شاي", "Tea"),
        "drink.tea.summary": ("ماء بحرارة مناسبة لنوع الشاي الذي تختاره.", "Water at the right temperature for your tea."),
        "drink.personalBadge": ("إعدادك الخاص", "Your settings"),
        "drink.personalized": ("بإعداداتك: %@", "Your settings: %@"),
        "drink.summary.title": ("ملخص المشروب", "Drink summary"),
        "drink.summary.time": ("المدة التقريبية: %d ثانية", "About %d seconds"),
        "drink.makeDefault": ("اجعلها إعدادي لهذا المشروب", "Make these my settings for this drink"),
        "drink.makeDefault.hint": ("تُستخدم في كل مرة يختار فيها %@ هذا المشروب.", "Used every time %@ picks this drink."),
        "drink.reset": ("استعد الإعدادات القياسية", "Restore standard settings"),
        "drink.reset.title": ("استعادة الإعدادات القياسية لهذا المشروب؟", "Restore the standard settings for this drink?"),
        "drink.reset.confirm": ("استعد", "Restore"),
        "drink.bluetoothUnsupported": ("هذا المشروب متاح في وضع التجربة فقط حتى نتأكد من رمزه في ماكينتك.", "This drink works in demo mode only until its code is confirmed on your machine."),
        "drinks.search": ("ابحث عن مشروب", "Search drinks"),
        "drinks.noResults": ("لا توجد مشروبات بهذا الاسم.", "No drinks match."),
        "drinks.card.hint": ("اضغط مرتين للتخصيص. للتحضير مباشرة استخدم قائمة الإجراءات.", "Double-tap to customize. To make it straight away, use the Actions rotor."),

        // MARK: Home
        "home.greeting.morning": ("صباح الخير، %@", "Good morning, %@"),
        "home.greeting.afternoon": ("مساء الخير، %@", "Good afternoon, %@"),
        "home.greeting.evening": ("مساء الخير، %@", "Good evening, %@"),
        "home.favorites": ("مفضلتي", "My favorites"),
        "home.favorites.empty": ("لا توجد مشروبات مفضلة بعد. افتح أي مشروب، خصّصه، ثم اختر «أضف إلى المفضلة».", "No favorites yet. Open any drink, customize it, then choose Add to favorites."),
        "home.favorite.hint": ("اضغط مرتين للتحضير. للتعديل أو الحذف استخدم قائمة الإجراءات.", "Double-tap to make it. Edit or delete from the Actions rotor."),
        "home.frequent": ("الأكثر تحضيرًا", "Most made"),
        "home.quick": ("مشروبات سريعة", "Quick drinks"),
        "home.allDrinks": ("كل المشروبات", "All drinks"),
        "profile.switch": ("تبديل الملف الشخصي", "Switch profile"),
        "profile.default.name": ("الملف %d", "Profile %d"),

        // MARK: Favorites
        "favorite.name.title": ("اسم المشروب المفضل", "Favorite name"),
        "favorite.name.placeholder": ("مثلًا: قهوة الصباح", "For example: Morning coffee"),
        "favorite.name.message": ("اتركه فارغًا لاستخدام اسم المشروب.", "Leave empty to use the drink's name."),
        "favorite.saveChanges": ("احفظ التعديلات", "Save changes"),

        // MARK: Brewing
        "brew.confirm.title": ("تحضير %@؟", "Make %@?"),
        "brew.preparing": ("جارٍ تحضير %@", "Making %@"),
        "brew.finished": ("%@ جاهز. بالهناء!", "Your %@ is ready. Enjoy!"),
        "brew.stopped": ("أوقفت التحضير", "Stopped"),
        "brew.failed": ("لم يكتمل التحضير: %@", "Not finished: %@"),
        "brew.progress": ("التقدّم", "Progress"),
        "brew.stop.hint": ("يوقف المشروب فورًا.", "Stops the drink immediately."),
        "brew.saveFavorite": ("احفظ هذا المشروب في المفضلة", "Save this drink to favorites"),
        "brew.error.busy": ("هناك مشروب قيد التحضير. انتظر حتى ينتهي أو أوقفه.", "A drink is already being made. Wait for it or stop it."),
        "brew.error.didNotStart": ("لم تبدأ الماكينة التحضير", "The machine did not start"),

        // MARK: Announcements
        "announce.turningOn": ("جارٍ تشغيل الماكينة وتسخينها.", "Turning the machine on and heating up."),
        "announce.ready": ("الماكينة جاهزة.", "The machine is ready."),
        "announce.connected": ("تم الاتصال بـ %@.", "Connected to %@."),
        "announce.disconnected": ("انقطع الاتصال بالماكينة.", "Disconnected from the machine."),
        "announce.alarm": ("تنبيه: %@", "Alert: %@"),
        "announce.alarmsCleared": ("زالت التنبيهات، الماكينة جاهزة.", "Alerts cleared, the machine is ready."),
        "announce.brewStarted": ("بدأ تحضير %@.", "Making %@."),
        "announce.brewFinished": ("%@ جاهز. بالهناء!", "Your %@ is ready. Enjoy!"),
        "announce.brewStopped": ("أُوقف التحضير.", "Stopped."),
        "announce.brewFailed": ("لم يكتمل التحضير: %@", "Not finished: %@"),
        "announce.progress": ("%d بالمئة", "%d percent"),
        "announce.profileSelected": ("الملف الشخصي: %@", "Profile: %@"),
        "announce.favoriteSaved": ("أُضيف %@ إلى المفضلة.", "%@ added to favorites."),
        "announce.favoriteExists": ("هذا المشروب بنفس الإعدادات موجود في المفضلة.", "This drink with these settings is already a favorite."),
        "announce.favoriteUpdated": ("حُفظت تعديلات %@.", "Saved changes to %@."),
        "announce.favoriteDeleted": ("حُذف %@ من المفضلة.", "Removed %@ from favorites."),
        "announce.defaultSaved": ("صار %1$@ بإعداداتك في ملف %2$@.", "%1$@ now uses your settings in %2$@'s profile."),
        "announce.resetDone": ("استُعيدت الإعدادات القياسية.", "Standard settings restored."),
        "announce.saved": ("تم الحفظ.", "Saved."),

        // MARK: Errors
        "error.notConnected": ("الماكينة غير متصلة. تأكد أنها قريبة وأن البلوتوث يعمل.", "The machine is not connected. Make sure it is nearby and Bluetooth is on."),
        "error.machineOff": ("الماكينة مطفأة أو ما زالت تسخن. شغّلها وانتظر حتى تصبح جاهزة.", "The machine is off or still heating. Turn it on and wait until it is ready."),
        "error.notReady": ("لا يمكن التحضير الآن: %@", "Can't make a drink now: %@"),
        "error.unsupportedBluetooth": ("%@ غير مدعوم عبر البلوتوث بعد.", "%@ is not supported over Bluetooth yet."),
        "error.noResponse": ("لم تردّ الماكينة. حاول مرة أخرى.", "The machine did not respond. Try again."),
        "error.saveFailed": ("تعذّر حفظ بياناتك على الجهاز.", "Could not save your data on this device."),

        // MARK: Machine status
        "status.machine": ("حالة الماكينة", "Machine status"),
        "status.alsoAlarms": ("وأيضًا: %@", "Also: %@"),
        "power.off": ("الماكينة مطفأة", "The machine is off"),
        "power.turningOn": ("جارٍ التسخين", "Heating up"),
        "power.shuttingDown": ("جارٍ الإطفاء", "Shutting down"),
        "power.ready": ("الماكينة جاهزة", "Ready"),
        "power.busy": ("الماكينة تعمل", "Working"),
        "power.descaling": ("جارٍ إزالة الترسبات", "Descaling"),
        "power.rinsing": ("جارٍ الشطف", "Rinsing"),
        "power.unknown": ("جارٍ قراءة الحالة", "Reading status"),
        "activity.idle": ("في الانتظار", "Idle"),
        "activity.grinding": ("جارٍ طحن البن", "Grinding the beans"),
        "activity.brewingCoffee": ("جارٍ تحضير القهوة", "Brewing the coffee"),
        "activity.dispensingMilk": ("جارٍ صب الحليب", "Pouring the milk"),
        "activity.dispensingWater": ("جارٍ صب الماء الساخن", "Pouring hot water"),
        "activity.steaming": ("جارٍ إخراج البخار", "Steaming"),
        "activity.rinsing": ("جارٍ الشطف", "Rinsing"),
        "activity.cleaningMilk": ("جارٍ تنظيف دورة الحليب", "Cleaning the milk circuit"),
        "activity.descaling": ("جارٍ إزالة الترسبات", "Descaling"),
        "activity.heating": ("جارٍ التسخين", "Heating up"),
        "activity.changingFilter": ("جارٍ تفعيل فلتر الماء", "Activating the water filter"),
        "accessory.none": ("لا يوجد ملحق", "No accessory"),
        "accessory.carafe": ("إبريق الحليب مركّب", "Milk carafe attached"),
        "accessory.carafeCleaning": ("إبريق الحليب على وضع التنظيف", "Milk carafe in cleaning position"),
        "accessory.hotWaterSpout": ("فوهة الماء الساخن مركّبة", "Hot water spout attached"),
        "accessory.unknown": ("ملحق غير معروف", "Unknown accessory"),
        "connection.disconnected": ("غير متصل", "Not connected"),
        "connection.searching": ("جارٍ البحث عن الماكينة", "Looking for the machine"),
        "connection.connecting": ("جارٍ الاتصال بـ %@", "Connecting to %@"),
        "connection.connected": ("متصل بـ %@", "Connected to %@"),
        "connection.failed": ("تعذّر الاتصال: %@", "Could not connect: %@"),
        "link.bluetooth.title": ("ماكينتي عبر البلوتوث", "My machine over Bluetooth"),
        "link.bluetooth.detail": ("يتصل بماكينة De'Longhi القريبة منك مباشرة، بلا حساب ولا إنترنت.", "Connects directly to your nearby De'Longhi machine, with no account or internet."),
        "link.demo.title": ("وضع التجربة", "Demo mode"),
        "link.demo.detail": ("ماكينة افتراضية لتجربة كل شيء وتعلّم التطبيق بأمان.", "A virtual machine to try everything and learn the app safely."),
        "demo.machine.name": ("ماكينة التجربة", "Demo machine"),
        "machine.generic.name": ("ماكينة القهوة", "Coffee machine"),
        "bluetooth.off": ("البلوتوث مطفأ. شغّله من مركز التحكم.", "Bluetooth is off. Turn it on in Control Center."),
        "bluetooth.unauthorized": ("لم يُسمح للتطبيق باستخدام البلوتوث. اسمح به من الإعدادات.", "The app is not allowed to use Bluetooth. Allow it in Settings."),
        "bluetooth.unsupported": ("هذا الجهاز لا يدعم البلوتوث منخفض الطاقة.", "This device does not support Bluetooth Low Energy."),
        "bluetooth.connect.failed": ("تعذّر الاتصال بالماكينة.", "Could not connect to the machine."),
        "bluetooth.no.ecam.service": ("الجهاز لا يستخدم بروتوكول ماكينات De'Longhi المعروف. شغّل «فحص الماكينة» وأرسل التقرير.", "The device does not use the known De'Longhi protocol. Run Machine check and send the report."),

        // MARK: Alarms
        "alarm.waterTankMissing.title": ("خزان الماء غير موجود", "Water tank missing"),
        "alarm.waterTankMissing.advice": ("ضع خزان الماء في مكانه واضغطه حتى يثبت.", "Put the water tank back and push it until it sits firmly."),
        "alarm.waterTankEmpty.title": ("خزان الماء فارغ", "Water tank empty"),
        "alarm.waterTankEmpty.advice": ("املأ الخزان بماء شرب بارد حتى خط الامتلاء ثم أعده إلى مكانه.", "Fill the tank with cold drinking water up to the MAX line and put it back."),
        "alarm.wasteContainerMissing.title": ("حاوية البن المستعمل غير موجودة", "Grounds container missing"),
        "alarm.wasteContainerMissing.advice": ("أعد حاوية البن المستعمل وصينية التقطير إلى مكانهما بالكامل.", "Put the grounds container and drip tray fully back in place."),
        "alarm.wasteContainerFull.title": ("حاوية البن المستعمل ممتلئة", "Grounds container full"),
        "alarm.wasteContainerFull.advice": ("أفرغ حاوية البن المستعمل وصينية التقطير ثم أعدهما.", "Empty the grounds container and drip tray, then put them back."),
        "alarm.dripTrayMissing.title": ("صينية التقطير غير موجودة", "Drip tray missing"),
        "alarm.dripTrayMissing.advice": ("أدخل صينية التقطير في مقدمة الماكينة حتى النهاية.", "Slide the drip tray all the way into the front of the machine."),
        "alarm.beansEmpty.title": ("حبوب البن نفدت", "Out of coffee beans"),
        "alarm.beansEmpty.advice": ("أضف حبوب بن محمصة إلى الحاوية العلوية ثم أغلق الغطاء.", "Add roasted coffee beans to the container on top, then close the lid."),
        "alarm.beanHopperMissing.title": ("حاوية البن غير مركّبة", "Bean container not in place"),
        "alarm.beanHopperMissing.advice": ("تأكد أن حاوية البن وغطاءها في مكانهما.", "Make sure the bean container and its lid are in place."),
        "alarm.groundTooFine.title": ("الطحن ناعم جدًا", "Grind too fine"),
        "alarm.groundTooFine.advice": ("اضبط درجة الطحن خطوة واحدة نحو الخشن أثناء عمل المطحنة فقط، ثم حضّر مشروبًا جديدًا.", "Turn the grind setting one step coarser, only while the grinder is running, then make a new drink."),
        "alarm.doorOpen.title": ("باب الصيانة مفتوح", "Service door open"),
        "alarm.doorOpen.advice": ("أغلق الباب الجانبي للماكينة بعد التأكد من تركيب وحدة التحضير.", "Close the side door after checking the brewing unit is in place."),
        "alarm.descaleNeeded.title": ("حان وقت إزالة الترسبات", "Descaling needed"),
        "alarm.descaleNeeded.advice": ("يمكنك الاستمرار في التحضير، لكن أزل الترسبات قريبًا لحماية الماكينة.", "You can keep making drinks, but descale soon to protect the machine."),
        "alarm.replaceFilter.title": ("حان وقت تغيير فلتر الماء", "Replace the water filter"),
        "alarm.replaceFilter.advice": ("ركّب فلترًا جديدًا أو أزل القديم وأبلغ الماكينة بذلك.", "Fit a new filter, or remove the old one and tell the machine."),
        "alarm.milkCarafeNeedsCleaning.title": ("إبريق الحليب يحتاج تنظيفًا", "Milk carafe needs cleaning"),
        "alarm.milkCarafeNeedsCleaning.advice": ("شغّل تنظيف إبريق الحليب بعد مشروبات الحليب، ثم ضع الحليب المتبقي في الثلاجة.", "Run the milk carafe clean after milk drinks, then put the leftover milk in the fridge."),
        "alarm.serviceNeeded.title": ("الماكينة تحتاج صيانة", "Service needed"),
        "alarm.serviceNeeded.advice": ("تواصل مع خدمة عملاء De'Longhi أو مركز صيانة معتمد.", "Contact De'Longhi customer service or an authorised service centre."),
        "alarm.hardwareFault.title": ("عطل في الماكينة", "Machine fault"),
        "alarm.hardwareFault.advice": ("أطفئ الماكينة وانتظر دقيقة ثم شغّلها. إن تكرر العطل فتواصل مع الصيانة.", "Turn the machine off, wait a minute and turn it on. If it happens again, contact service."),

        // MARK: Machine screen
        "machine.alarms": ("التنبيهات", "Alerts"),
        "machine.levels": ("مستويات الماكينة", "Machine levels"),
        "machine.demo.note": ("هذه مستويات ماكينة التجربة. استخدم الأزرار لمحاكاة ملء الماء والبن وإفراغ الحاوية.", "These are the demo machine's levels. Use the buttons to simulate refilling and emptying."),
        "machine.maintenance": ("الصيانة والتنظيف", "Care and cleaning"),
        "machine.statistics": ("إحصائياتي", "My statistics"),
        "machine.tools": ("أدوات", "Tools"),
        "level.water": ("خزان الماء", "Water tank"),
        "level.beans": ("حبوب البن", "Coffee beans"),
        "level.grounds": ("حاوية البن المستعمل", "Grounds container"),
        "demo.turnOff": ("أطفئ ماكينة التجربة", "Turn the demo machine off"),
        "demo.refillWater": ("املأ خزان الماء", "Refill the water tank"),
        "demo.refillBeans": ("املأ حبوب البن", "Refill the beans"),
        "demo.emptyGrounds": ("أفرغ حاوية البن المستعمل", "Empty the grounds container"),
        "demo.cleanCarafe": ("نظّف إبريق الحليب", "Clean the milk carafe"),
        "demo.descale": ("أتمم إزالة الترسبات", "Finish descaling"),
        "stats.total": ("حضّرت %d مشروبًا", "%d drinks made"),
        "stats.totalLabel": ("كل المشروبات", "All drinks"),
        "stats.last": ("آخر مشروب: %1$@، %2$@", "Last drink: %1$@, %2$@"),
        "stats.byDrink": ("حسب المشروب", "By drink"),
        "stats.cups": ("%d مرة", "%d times"),
        "stats.empty": ("لا توجد مشروبات بعد.", "No drinks yet."),
        "stats.recent": ("آخر المشروبات", "Recent drinks"),
        "stats.completed": ("اكتمل", "Finished"),
        "stats.notCompleted": ("لم يكتمل", "Not finished"),

        // MARK: Maintenance guides
        "guide.duration": ("نحو %1$d دقيقة، %2$d خطوات", "About %1$d min, %2$d steps"),
        "guide.mode": ("طريقة العرض", "View"),
        "guide.mode.steps": ("خطوة بخطوة", "Step by step"),
        "guide.mode.all": ("كل الخطوات", "All steps"),
        "guide.stepOf": ("الخطوة %1$d من %2$d", "Step %1$d of %2$d"),
        "guide.previous": ("السابق", "Previous"),
        "guide.next": ("التالي", "Next"),
        "guide.finish": ("انتهيت", "Finished"),
        "guide.finished": ("أحسنت، أنهيت: %@", "Well done, you finished: %@"),

        "guide.fillWater.title": ("ملء خزان الماء", "Fill the water tank"),
        "guide.fillWater.intro": ("استخدم ماء شرب باردًا ونظيفًا فقط.", "Use only fresh, cold drinking water."),
        "guide.fillWater.step.1": ("اسحب خزان الماء من الماكينة برفق.", "Gently pull the water tank out of the machine."),
        "guide.fillWater.step.2": ("اشطفه ثم املأه بماء شرب بارد حتى خط الامتلاء. لا تستخدم ماءً غازيًا أو أي سائل آخر.", "Rinse it and fill it with cold drinking water up to the MAX line. Never use sparkling water or any other liquid."),
        "guide.fillWater.step.3": ("أعد الخزان إلى مكانه واضغطه حتى يثبت تمامًا.", "Put the tank back and push it until it sits firmly."),
        "guide.fillWater.step.4": ("يزول التنبيه وحده عندما تتعرف الماكينة على الخزان. إن لم يزل فتأكد أنه مدفوع للنهاية.", "The alert clears by itself once the machine detects the tank. If it doesn't, check the tank is pushed all the way in."),

        "guide.fillBeans.title": ("إضافة حبوب البن", "Add coffee beans"),
        "guide.fillBeans.intro": ("الحاوية في أعلى الماكينة، ولها غطاء يُفتح للأعلى.", "The container is on top of the machine, with a lid that opens upward."),
        "guide.fillBeans.step.1": ("افتح غطاء حاوية البن في أعلى الماكينة.", "Open the bean container lid on top of the machine."),
        "guide.fillBeans.step.2": ("صب حبوب بن محمصة. لا تضع بنًا مطحونًا ولا حبوبًا منكّهة أو مكرملة أو زيتية في هذه الحاوية.", "Pour in roasted coffee beans. Never put ground coffee or flavoured, caramelised or oily beans in this container."),
        "guide.fillBeans.step.3": ("أغلق الغطاء جيدًا ليحفظ النكهة.", "Close the lid well to keep the aroma."),
        "guide.fillBeans.step.4": ("حضّر مشروبك من جديد. قد يكون أول كوب بعد الملء أخف قليلًا.", "Make your drink again. The first cup after refilling may be slightly milder."),

        "guide.emptyContainers.title": ("إفراغ الحاوية وصينية التقطير", "Empty the grounds and drip tray"),
        "guide.emptyContainers.intro": ("الصينية والحاوية في مقدمة الماكينة أسفل فوهة القهوة.", "The drip tray and grounds container are at the front, below the coffee spout."),
        "guide.emptyContainers.step.1": ("اسحب صينية التقطير من مقدمة الماكينة ببطء، فقد تحتوي على ماء.", "Slowly pull the drip tray out of the front of the machine; it may hold water."),
        "guide.emptyContainers.step.2": ("أخرج حاوية البن المستعمل وأفرغها في سلة المهملات.", "Take out the grounds container and empty it into the bin."),
        "guide.emptyContainers.step.3": ("أفرغ صينية التقطير واشطفها بالماء.", "Empty the drip tray and rinse it with water."),
        "guide.emptyContainers.step.4": ("أعد الحاوية ثم الصينية إلى مكانهما حتى النهاية.", "Put the container back, then slide the tray all the way in."),
        "guide.emptyContainers.step.5": ("أفرغ الحاوية دائمًا عندما تطلب الماكينة ذلك؛ إعادتها دون إفراغ تجعل العدّ خاطئًا.", "Always empty the container when asked; putting it back full makes the machine's count wrong."),

        "guide.milkCarafe.title": ("تنظيف إبريق الحليب", "Clean the milk carafe"),
        "guide.milkCarafe.intro": ("نظّف دورة الحليب بعد كل مشروب بالحليب، وفكّ الإبريق للغسل مرة يوميًا.", "Flush the milk circuit after every milk drink, and take the carafe apart to wash it once a day."),
        "guide.milkCarafe.step.1": ("بعد مشروب الحليب اترك الإبريق مركّبًا، وعندما تطلب الماكينة التنظيف أدر مقبض الرغوة إلى وضع التنظيف أو أكّد على الشاشة.", "After a milk drink, leave the carafe attached. When the machine asks, turn the froth knob to the clean position or confirm on the screen."),
        "guide.milkCarafe.step.2": ("ضع كوبًا تحت فوهة الحليب؛ يخرج ماء ساخن وبخار لتنظيف الدورة.", "Place a cup under the milk spout; hot water and steam flush the circuit."),
        "guide.milkCarafe.step.3": ("افصل الإبريق وضع الحليب المتبقي في الثلاجة.", "Detach the carafe and put the leftover milk in the fridge."),
        "guide.milkCarafe.step.4": ("مرة يوميًا: فكّ الغطاء والفوهة وأنبوب السحب ومقبض الرغوة.", "Once a day: take off the lid, the spout, the intake tube and the froth knob."),
        "guide.milkCarafe.step.5": ("اغسل الأجزاء بماء دافئ ومنظف خفيف، واشطفها جيدًا.", "Wash the parts in warm water with mild detergent and rinse well."),
        "guide.milkCarafe.step.6": ("أعد تركيب كل الأجزاء قبل الاستخدام؛ التركيب الناقص يسبب تسربًا أو رغوة ضعيفة.", "Reassemble every part before use; a missing part causes leaks or poor froth."),

        "guide.brewingUnit.title": ("تنظيف وحدة التحضير", "Clean the brewing unit"),
        "guide.brewingUnit.intro": ("مرة أسبوعيًا تقريبًا. لا تُخرج الوحدة والماكينة تعمل.", "About once a week. Never remove the unit while the machine is on."),
        "guide.brewingUnit.step.1": ("أطفئ الماكينة بزر التشغيل وانتظر حتى تنطفئ تمامًا.", "Turn the machine off with the power button and wait until it is completely off."),
        "guide.brewingUnit.step.2": ("افتح باب الصيانة على جانب الماكينة.", "Open the service door on the side of the machine."),
        "guide.brewingUnit.step.3": ("اضغط زري التحرير الملونين في الوحدة معًا واسحبها للخارج.", "Press the two coloured release buttons on the unit together and pull it out."),
        "guide.brewingUnit.step.4": ("اشطفها بماء فاتر جارٍ فقط، بلا منظفات وبلا غسالة صحون.", "Rinse it under lukewarm running water only, with no detergent and no dishwasher."),
        "guide.brewingUnit.step.5": ("نظّف مكان الوحدة داخل الماكينة من بقايا البن بفرشاة ناعمة.", "Brush away coffee residue from the unit's compartment."),
        "guide.brewingUnit.step.6": ("اتركها تجف، ثم أدخلها حتى تسمع نقرة دون الضغط على زري التحرير.", "Let it dry, then slide it in until it clicks, without pressing the release buttons."),
        "guide.brewingUnit.step.7": ("أغلق باب الصيانة. لن تعمل الماكينة إن كان الباب مفتوحًا أو الوحدة غير مثبتة.", "Close the service door. The machine won't start if the door is open or the unit is loose."),

        "guide.waterFilter.title": ("تركيب فلتر الماء", "Fit the water filter"),
        "guide.waterFilter.intro": ("الفلتر يقلل الترسبات. غيّره كل شهرين تقريبًا أو عندما تطلب الماكينة.", "The filter reduces scale. Replace it about every two months, or when the machine asks."),
        "guide.waterFilter.step.1": ("أخرج الفلتر الجديد من غلافه، وأدر قرص التاريخ إلى موعد التغيير القادم.", "Unwrap the new filter and turn its date dial to the next change date."),
        "guide.waterFilter.step.2": ("مرّر ماء الصنبور في فتحته الوسطى حتى يخرج من الفتحات الجانبية، نحو دقيقة.", "Run tap water into its centre opening until it flows out of the side openings, about a minute."),
        "guide.waterFilter.step.3": ("أخرج خزان الماء، وضع الفلتر في مكانه داخله واضغطه للأسفل حتى يثبت.", "Take out the water tank, place the filter in its seat inside, and press it down."),
        "guide.waterFilter.step.4": ("املأ الخزان بالماء وأعده إلى الماكينة.", "Fill the tank with water and put it back."),
        "guide.waterFilter.step.5": ("من قائمة الماكينة أكّد تركيب الفلتر. ضع وعاءً سعته نصف لتر على الأقل تحت الفوهة لأن الماكينة ستصب ماءً لتفعيله.", "Confirm the filter in the machine's menu. Put a container of at least half a litre under the spout; the machine pours water to activate it."),
        "guide.waterFilter.step.6": ("أفرغ الوعاء بعد انتهاء التفعيل. الفلتر جاهز.", "Empty the container when activation ends. The filter is ready."),

        "guide.descaling.title": ("إزالة الترسبات", "Descaling"),
        "guide.descaling.intro": ("تستغرق نحو 45 دقيقة. تحتاج مزيل ترسبات De'Longhi ووعاءً سعته لتران على الأقل. يبدأ البرنامج من قائمة الماكينة نفسها، ولا يستطيع التطبيق بدأه.", "Takes about 45 minutes. You need De'Longhi descaler and a container of at least 2 litres. The programme starts from the machine's own menu; the app cannot start it."),
        "guide.descaling.step.1": ("جهّز مزيل الترسبات ووعاءً كبيرًا وماءً نظيفًا. لا تستخدم الخل أبدًا.", "Get the descaler, a large container and fresh water ready. Never use vinegar."),
        "guide.descaling.step.2": ("إن كان فلتر الماء مركّبًا فأخرجه من الخزان.", "If a water filter is fitted, take it out of the tank."),
        "guide.descaling.step.3": ("أفرغ صينية التقطير وحاوية البن المستعمل ثم أعدهما.", "Empty the drip tray and grounds container, then put them back."),
        "guide.descaling.step.4": ("صب مزيل الترسبات في الخزان حتى العلامة المحددة، ثم أضف الماء حتى العلامة التالية كما توضح الماكينة.", "Pour the descaler into the tank up to its mark, then add water up to the next mark, as the machine shows."),
        "guide.descaling.step.5": ("ضع الوعاء الكبير تحت فوهات القهوة والماء والحليب.", "Put the large container under the coffee, water and milk spouts."),
        "guide.descaling.step.6": ("ابدأ برنامج إزالة الترسبات من قائمة الصيانة في الماكينة وأكّد. يخرج المحلول على دفعات؛ انتظر.", "Start descaling from the machine's maintenance menu and confirm. The solution comes out in bursts; wait."),
        "guide.descaling.step.7": ("عندما تطلب الماكينة، اشطف الخزان واملأه بماء نظيف حتى خط الامتلاء، وأفرغ الوعاء وأعده.", "When asked, rinse the tank and fill it with fresh water to MAX, then empty the container and put it back."),
        "guide.descaling.step.8": ("تبدأ دورة الشطف. بعد انتهائها أفرغ الوعاء وصينية التقطير.", "The rinse cycle runs. When it ends, empty the container and the drip tray."),
        "guide.descaling.step.9": ("أعد فلتر الماء إن كنت تستخدمه، وامسح أي رذاذ من المحلول. احفظ المحلول بعيدًا عن الأطفال.", "Refit the water filter if you use one and wipe any splashes. Keep the descaler away from children."),

        // MARK: Diagnostics
        "diagnostics.title": ("فحص الماكينة", "Machine check"),
        "diagnostics.hint": ("يبحث عن ماكينتك ويختبر طريقة اتصالها، ثم يعطيك تقريرًا ترسله.", "Finds your machine, tests how it talks, and gives you a report to send."),
        "diagnostics.intro": ("قرّب الهاتف من الماكينة وشغّلها. ابدأ البحث، ثم اختر الجهاز الذي يبدو أنه ماكينتك ليُفحص. في النهاية شارك التقرير.", "Keep your phone near the machine and turn it on. Start the scan, then pick the device that looks like your machine. Finally, share the report."),
        "diagnostics.scan": ("ابدأ البحث", "Start scan"),
        "diagnostics.scanning": ("جارٍ البحث…", "Scanning…"),
        "diagnostics.inspecting": ("جارٍ فحص %@…", "Checking %@…"),
        "diagnostics.result": ("النتيجة", "Result"),
        "diagnostics.devices": ("الأجهزة القريبة", "Nearby devices"),
        "diagnostics.services": ("الخدمات التي وُجدت", "Services found"),
        "diagnostics.traffic": ("آخر الرسائل مع الماكينة", "Recent machine messages"),
        "diagnostics.share": ("شارك التقرير", "Share report"),
        "diagnostics.copy": ("انسخ التقرير", "Copy report"),
        "diagnostics.copied": ("نُسخ التقرير.", "Report copied."),
        "diagnostics.inspect.hint": ("اضغط مرتين لفحص هذا الجهاز.", "Double-tap to check this device."),
        "diagnostics.signal": ("قوة الإشارة %d", "Signal %d"),
        "diagnostics.ecamAdvertised": ("يعلن خدمة ماكينات De'Longhi", "Advertises the De'Longhi service"),
        "diagnostics.likelyMachine": ("يبدو أنه ماكينة De'Longhi", "Looks like a De'Longhi machine"),
        "diagnostics.ecamService": ("خدمة ماكينات De'Longhi (ECAM)", "De'Longhi machine service (ECAM)"),
        "diagnostics.unnamed": ("جهاز بلا اسم", "Unnamed device"),
        "diagnostics.foundMachine": ("وُجد جهاز يبدو أنه ماكينتك: %@", "Found a device that looks like your machine: %@"),
        "diagnostics.timeout": ("انتهت مهلة الفحص.", "The check timed out."),
        "diagnostics.done": ("انتهى الفحص.", "Check finished."),
        "diagnostics.verdict.ecamWorks": ("ممتاز: ماكينتك تفهم بروتوكول البلوتوث المعروف، ويمكن التحكم بها من التطبيق.", "Great: your machine speaks the known Bluetooth protocol and can be controlled from the app."),
        "diagnostics.verdict.ecamSilent": ("وُجدت خدمة ماكينات De'Longhi لكن الماكينة لم تردّ. شغّلها وأعد الفحص، ثم أرسل التقرير.", "The De'Longhi service is there but the machine did not answer. Turn it on, check again, then send the report."),
        "diagnostics.verdict.noEcam": ("هذا الجهاز لا يستخدم البروتوكول المعروف. أرسل التقرير لنعرف طريقة اتصاله.", "This device does not use the known protocol. Send the report so we can learn how it talks."),
        "diagnostics.verdict.nothingFound": ("لم يُعثر على أي جهاز. تأكد أن البلوتوث يعمل وأن الماكينة قريبة ومشغّلة.", "Nothing found. Check Bluetooth is on and the machine is nearby and on."),
        "diagnostics.verdict.noMachineName": ("وُجدت أجهزة لكن لا يبدو أي منها ماكينة De'Longhi. جرّب فحص الأقرب إشارة، وأرسل التقرير.", "Devices found, but none looks like a De'Longhi machine. Try checking the strongest one and send the report."),

        // MARK: Settings
        "settings.machine": ("الماكينة", "Machine"),
        "settings.connection": ("طريقة الاتصال", "Connection"),
        "settings.status": ("الحالة", "Status"),
        "settings.forgetMachine": ("انسَ هذه الماكينة", "Forget this machine"),
        "settings.forgetMachine.confirm": ("نسيان الماكينة والبحث عنها من جديد؟", "Forget the machine and search again?"),
        "settings.profiles": ("الملفات الشخصية", "Profiles"),
        "settings.profile.active": ("الحالي", "Current"),
        "settings.brewing": ("التحضير", "Brewing"),
        "settings.confirm": ("اسألني قبل التحضير", "Ask before making a drink"),
        "settings.feedback": ("الإعلانات الصوتية والاهتزاز", "Spoken updates and haptics"),
        "settings.announcePhases": ("أعلن مراحل التحضير", "Announce brewing steps"),
        "settings.announceProgress": ("أعلن نسبة التقدّم", "Announce progress"),
        "settings.announceAlarms": ("أعلن تنبيهات الماكينة", "Announce machine alerts"),
        "settings.haptics": ("الاهتزاز", "Haptics"),
        "settings.speakWithoutVoiceOver": ("انطق الإعلانات دون VoiceOver", "Speak updates without VoiceOver"),
        "settings.feedback.footer": ("مع VoiceOver تُقرأ الإعلانات بصوته. الخيار الأخير لضعاف البصر الذين لا يستخدمون VoiceOver.", "With VoiceOver, updates are read by VoiceOver. The last option is for low-vision users who don't use VoiceOver."),
        "settings.language": ("لغة التطبيق", "App language"),
        "settings.language.footer": ("يتبع التطبيق لغة جهازك. لتغييرها لهذا التطبيق فقط افتح الإعدادات ثم اختر اللغة.", "The app follows your device language. To change it for this app only, open Settings and choose Language."),
        "settings.about": ("حول", "About"),
        "profile.name": ("الاسم", "Name"),
        "profile.color": ("اللون", "Colour"),
        "profile.color.0": ("نحاسي", "Copper"),
        "profile.color.1": ("أخضر مزرق", "Teal"),
        "profile.color.2": ("بنفسجي", "Purple"),
        "profile.color.3": ("أزرق", "Blue"),
        "profile.makeActive": ("اجعله الملف الحالي", "Make current profile"),
        "profile.favoritesCount": ("المفضلة", "Favorites"),
        "profile.customCount": ("مشروبات بإعدادات خاصة", "Drinks with personal settings"),

        // MARK: Onboarding
        "onboarding.welcome.title": ("أهلًا بك في قهوتي", "Welcome to Coffee Access"),
        "onboarding.welcome.body": ("تطبيق مستقل لماكينة القهوة الأوتوماتيكية، صُمّم أولًا لمستخدمي VoiceOver.", "An independent app for your bean-to-cup machine, designed first for VoiceOver users."),
        "onboarding.feature.1": ("كل المشروبات بقائمة واضحة مقسّمة بعناوين.", "Every drink in a clear menu with headings."),
        "onboarding.feature.2": ("تخصيص القوة والكمية والحرارة بالسحب لأعلى ولأسفل.", "Set strength, amount and temperature by swiping up and down."),
        "onboarding.feature.3": ("إعلانات صوتية لكل مرحلة وتنبيه.", "Spoken updates for every step and alert."),
        "onboarding.feature.4": ("اطلب قهوتك من Siri.", "Ask Siri for your coffee."),
        "onboarding.connection.title": ("كيف نصل إلى ماكينتك؟", "How should we reach your machine?"),
        "onboarding.connection.body": ("اختر الاتصال بماكينتك عبر البلوتوث، أو ابدأ بوضع التجربة لتتعلّم التطبيق أولًا. يمكنك التغيير لاحقًا من الإعدادات.", "Connect to your machine over Bluetooth, or start in demo mode to learn the app first. You can change this later in Settings."),
        "onboarding.connection.note": ("إن لم تتصل ماكينتك، افتح «فحص الماكينة» من تبويب الماكينة وأرسل التقرير.", "If your machine doesn't connect, open Machine check from the Machine tab and send the report."),
        "onboarding.profile.title": ("ما اسمك؟", "What's your name?"),
        "onboarding.profile.body": ("يُستخدم للترحيب ولاسم ملفك الشخصي. للماكينة أربعة ملفات لكل منها مفضلته.", "Used for greetings and your profile name. The machine has four profiles, each with its own favorites."),
        "onboarding.start": ("ابدأ", "Get started"),

        // MARK: Siri
        "intent.brewing": ("جارٍ التحضير: %@", "Making: %@"),
        "intent.failed": ("تعذّر بدء التحضير.", "Could not start the drink."),
        "intent.noFavorite": ("لا يوجد مشروب مفضل في ملفك بعد.", "There is no favorite in your profile yet."),

        // MARK: About, accessibility and help
        "about.title": ("حول التطبيق", "About"),
        "about.1.heading": ("ما هذا التطبيق؟", "What is this app?"),
        "about.1.body": ("«قهوتي» تطبيق مستقل يتيح لك تحضير مشروباتك ومتابعة ماكينة القهوة الأوتوماتيكية والعناية بها، وقد صُمّم من البداية ليعمل بالكامل مع VoiceOver وتكبير الخط والتحكم الصوتي.", "Coffee Access is an independent app to make drinks on, follow and care for your bean-to-cup machine. It was designed from the start to work fully with VoiceOver, larger text and Voice Control."),
        "about.2.heading": ("تطبيق غير رسمي", "Unofficial app"),
        "about.2.body": ("التطبيق غير تابع لشركة De'Longhi ولا معتمد منها. اسما De'Longhi وEletta علامتان تجاريتان لأصحابهما، ويُذكران هنا لبيان التوافق فقط. كل الرسومات والتصميم أصلية.", "This app is not made, endorsed or supported by De'Longhi. De'Longhi and Eletta are trademarks of their owners and are mentioned only to describe compatibility. All graphics and design are original."),
        "about.3.heading": ("الخصوصية", "Privacy"),
        "about.3.body": ("لا حساب ولا خوادم ولا تتبع. ملفاتك ومفضلتك وسجلك محفوظة على هاتفك فقط، والبلوتوث يُستخدم للتحدث مع الماكينة فقط.", "No account, no servers, no tracking. Your profiles, favorites and history stay on your phone, and Bluetooth is used only to talk to the machine."),
        "about.4.heading": ("التوافق وشكر", "Compatibility and thanks"),
        "about.4.body": ("يستخدم التطبيق بروتوكول البلوتوث الذي وثّقه مجتمع المصادر المفتوحة (مشروعا barista بترخيص MIT وhome_assistant_delonghi_primadonna بترخيص Apache 2.0). دعم Eletta Ultra يُتحقق منه عبر «فحص الماكينة». اتبع دائمًا تعليمات السلامة في دليل ماكينتك.", "The app uses the Bluetooth protocol documented by the open-source community (barista, MIT licence, and home_assistant_delonghi_primadonna, Apache 2.0). Eletta Ultra support is confirmed with Machine check. Always follow the safety instructions in your machine's manual."),

        "accessibility.title": ("بيان إمكانية الوصول", "Accessibility statement"),
        "accessibility.1.heading": ("التزامنا", "Our commitment"),
        "accessibility.1.body": ("صُمّم التطبيق أولًا للمكفوفين وضعاف البصر، ثم لكل من يريد تحكمًا أسهل بماكينته.", "The app is designed first for blind and low-vision people, then for anyone who wants easier control of their machine."),
        "accessibility.2.heading": ("VoiceOver", "VoiceOver"),
        "accessibility.2.body": ("كل زر له اسم واضح. كل إعداد في المشروب عنصر واحد قابل للتعديل بالسحب لأعلى ولأسفل، والأحجام السريعة في قائمة الإجراءات. الأقسام عناوين للتنقل السريع، ومراحل التحضير والتقدّم والتنبيهات تُعلن تلقائيًا.", "Every button has a clear name. Each drink setting is a single adjustable element you change by swiping up or down, with quick sizes in the Actions rotor. Sections are headings, and brewing steps, progress and alerts are announced automatically."),
        "accessibility.3.heading": ("الرؤية", "Vision"),
        "accessibility.3.body": ("يدعم أكبر أحجام الخط وتتحول الشبكات إلى قوائم عندها. الألوان تحقق تباين WCAG AA وتزداد مع «زيادة التباين»، ولا يُعتمد على اللون وحده، و«تقليل الحركة» يوقف حركة البخار.", "Supports the largest text sizes, where grids become lists. Colours meet WCAG AA contrast and get stronger with Increase Contrast, colour is never the only cue, and Reduce Motion stops the steam animation."),
        "accessibility.4.heading": ("الحركة والصوت", "Motor and voice"),
        "accessibility.4.body": ("أزرار + و− ظاهرة بأسماء واضحة للتحكم الصوتي والتحكم بالمفاتيح، وأهداف اللمس لا تقل عن 44 نقطة، ويمكن طلب المشروبات من Siri.", "Visible + and − buttons with clear names work with Voice Control and Switch Control, touch targets are at least 44 points, and drinks can be ordered with Siri."),
        "accessibility.5.heading": ("الاهتزاز والنطق", "Haptics and speech"),
        "accessibility.5.body": ("اهتزاز خفيف مع كل تغيير، واهتزاز نجاح أو تحذير عند الانتهاء أو التنبيه، وخيار لنطق الإعلانات دون VoiceOver.", "A light tap with every change, success or warning haptics when a drink finishes or an alert appears, and an option to speak updates without VoiceOver."),
        "accessibility.6.heading": ("حدود معروفة", "Known limits"),
        "accessibility.6.body": ("شاشة اللمس في الماكينة نفسها ليست متاحة، وبعض المهام مثل بدء إزالة الترسبات تُبدأ منها. نعمل على تغطية أكبر قدر من المهام من التطبيق. أرسل ملاحظاتك مع تقرير «فحص الماكينة».", "The machine's own touchscreen is not accessible, and some tasks such as starting descaling begin there. We are working to cover as much as possible from the app. Send feedback with a Machine check report."),

        "help.title": ("دليل الاستخدام", "User guide"),
        "help.1.heading": ("البداية", "Getting started"),
        "help.1.body": ("شغّل الماكينة وقرّب هاتفك منها. في تبويب الماكينة ترى حالة الاتصال. إن لم تتصل، شغّل «فحص الماكينة». وضع التجربة متاح دائمًا لتتعلم التطبيق.", "Turn the machine on and keep your phone nearby. The Machine tab shows the connection. If it doesn't connect, run Machine check. Demo mode is always there to learn the app."),
        "help.2.heading": ("تخصيص المشروب مع VoiceOver", "Customizing a drink with VoiceOver"),
        "help.2.body": ("افتح المشروب، ثم مرّر إلى «كمية القهوة» أو «قوة القهوة» أو «الحرارة» واسحب بإصبع واحد لأعلى للزيادة ولأسفل للإنقاص. لاختيار حجم سريع أدر الدوّار إلى «الإجراءات». «ملخص المشروب» يقرأ الوصفة كاملة.", "Open a drink, move to Coffee amount, Strength or Temperature and swipe up with one finger to increase or down to decrease. For a quick size, turn the rotor to Actions. Drink summary reads the whole recipe."),
        "help.3.heading": ("المفضلة والملفات", "Favorites and profiles"),
        "help.3.body": ("احفظ أي مشروب باسم خاص في المفضلة ليظهر أولًا في الرئيسية. «اجعلها إعدادي» تغيّر إعدادات المشروب لملفك فقط. بدّل الملف من الزر أعلى الرئيسية.", "Save any drink with your own name to favorites; they appear first on Home. Make these my settings changes a drink for your profile only. Switch profiles with the button at the top of Home."),
        "help.4.heading": ("التحضير والإيقاف", "Making and stopping"),
        "help.4.body": ("اضغط «حضّر الآن» واسمع الملخص ثم أكّد. تفتح شاشة التحضير وتعلن المراحل والنسبة، وزر «إيقاف» الكبير متاح دائمًا. عند الانتهاء تسمع «جاهز» مع اهتزاز.", "Choose Make it now, listen to the summary and confirm. The brewing screen announces each step and the percentage, and the large Stop button is always there. When it's done you hear Ready with a haptic."),
        "help.5.heading": ("التنبيهات والصيانة", "Alerts and care"),
        "help.5.body": ("تُعلن تنبيهات الماكينة فور ظهورها، ولكل تنبيه نصيحة ودليل خطوة بخطوة في تبويب الماكينة: الماء والبن والحاوية وإبريق الحليب ووحدة التحضير والفلتر وإزالة الترسبات.", "Machine alerts are announced as they appear. Each has advice and a step-by-step guide in the Machine tab: water, beans, grounds, milk carafe, brewing unit, filter and descaling."),
        "help.6.heading": ("Siri", "Siri"),
        "help.6.body": ("قل مثلًا: «حضّر كابتشينو في قهوتي» أو «حضّر مشروبي المفضل في قهوتي» أو «حالة الماكينة في قهوتي» أو «شغّل الماكينة في قهوتي». تجدها أيضًا في تطبيق الاختصارات.", "Say for example: Make cappuccino with Coffee Access, Make my favorite with Coffee Access, What is the machine status in Coffee Access, or Turn on the machine with Coffee Access. They're also in the Shortcuts app."),
        "help.7.heading": ("فحص الماكينة", "Machine check"),
        "help.7.body": ("من تبويب الماكينة افتح «فحص الماكينة» وابدأ البحث، ثم اختر ماكينتك ليُفحص اتصالها. اضغط «شارك التقرير» وأرسله؛ لا يحتوي التقرير على أي بيانات شخصية.", "In the Machine tab open Machine check, start the scan and pick your machine. Then choose Share report and send it; the report contains no personal data."),
    ]
}
