import Foundation

// Interface text added in version 2 (Arabic first), kept apart from the
// original table so each stays readable. Checked by Scripts/validate_strings.py
// together with Strings.swift: no key may appear in both.
enum StringsLife {
    static let table: [String: (ar: String, en: String)] = [
        "bagscan.button": ("اقرأ الكيس بالكاميرا", "Read the bag with the camera"),
        "bagscan.found": ("قرأت من الكيس: %@. راجع الحقول ثم احفظ.", "Read from the bag: %@. Check the fields, then save."),
        "bagscan.nothing": ("لم أجد نصًا واضحًا على الكيس. اكتب البيانات بنفسك.", "No clear text found on the bag. Type the details yourself."),
        "bagscan.reading": ("صوّر واجهة الكيس حيث الاسم والتحميص.", "Photograph the front of the bag, where the name and roast are."),
        "bean.settle.announce": ("بدّلت البن. أول ثلاثة أكواب قد يختلف طعمها حتى يخرج البن القديم من المطحنة.", "You changed beans. The first three cups may taste different until the old beans leave the grinder."),
        "bean.settle.tip": ("بن جديد: الأكواب الباقية حتى يستقر الطعم: %d", "New beans: cups left until the taste settles: %d"),
        "beans.bag": ("وزن الكيس", "Bag weight"),
        "beans.bag.footer": ("يقدّر التطبيق المتبقي من عدد الأكواب منذ فتح الكيس. قد يختلف عن الواقع قليلًا.", "The app estimates what is left from the cups made since the bag was opened. It may differ a little."),
        "beans.bagSection": ("الكيس", "The bag"),
        "beans.notes": ("ملاحظات التذوق", "Tasting notes"),
        "beans.notes.placeholder": ("مثلًا: نكهة شوكولاتة، حموضة خفيفة", "For example: chocolate, light acidity"),
        "beans.opened": ("تاريخ الفتح", "Opened on"),
        "beans.openedToday": ("فتحت كيسًا جديدًا اليوم", "I opened a new bag today"),
        "beans.openedToday.done": ("سُجّل تاريخ فتح الكيس اليوم.", "Today is saved as the opening date."),
        "beans.origin": ("المنشأ (مثل: إثيوبيا)", "Origin (e.g. Ethiopia)"),
        "beans.roaster": ("المحمصة", "Roaster"),
        "caffeine.cups": ("أكواب اليوم", "Today's cups"),
        "caffeine.cutoff": ("لا كافيين بعد", "No caffeine after"),
        "caffeine.cutoff.hour": ("الساعة %d:00", "%d:00"),
        "caffeine.cutoff.off": ("دون تذكير", "No reminder"),
        "caffeine.estimate": ("نحو %d ملغ (تقدير)", "About %d mg (estimate)"),
        "caffeine.footer": ("الأرقام تقديرية من وصفة كل مشروب، وتختلف حسب البن. لا يمنعك التطبيق من التحضير، بل ينبهك فقط.", "Figures are estimates from each recipe and vary with the beans. The app never stops you; it only reminds you."),
        "caffeine.health": ("اكتب الكافيين في تطبيق «صحتي»", "Write caffeine to the Health app"),
        "caffeine.health.denied": ("لم يُسمح بالكتابة في «صحتي»، أو أن هذه النسخة موقّعة دون صلاحية «صحتي».", "Writing to Health was not allowed, or this copy was signed without Health access."),
        "caffeine.health.footer": ("يكتب التطبيق تقدير الكافيين لكل مشروب مكتمل فقط، ولا يقرأ أي بيانات صحية.", "The app writes only the caffeine estimate of each finished drink and never reads health data."),
        "caffeine.health.on": ("سيُكتب الكافيين في «صحتي» بعد كل مشروب.", "Caffeine will be written to Health after each drink."),
        "caffeine.hint": ("يفتح تفاصيل الكافيين وحدّك اليومي", "Opens caffeine details and your daily limit"),
        "caffeine.late": ("تنبيه: الساعة تجاوزت %d:00، وقد يؤثر الكافيين على نومك.", "Note: it is past %d:00 and caffeine may affect your sleep."),
        "caffeine.limit": ("حدّك اليومي", "Daily limit"),
        "caffeine.mg": ("%d ملغ", "%d mg"),
        "caffeine.none": ("لا أكواب اليوم بعد.", "No cups today yet."),
        "caffeine.overLimit": ("تنبيه: سيصل كافيين اليوم إلى نحو %1$d ملغ، فوق حدّك %2$d ملغ.", "Note: today's caffeine would reach about %1$d mg, above your %2$d mg limit."),
        "caffeine.spoken": ("%1$d ملغ من %2$d ملغ اليوم", "%1$d mg of %2$d mg today"),
        "caffeine.title": ("الكافيين", "Caffeine"),
        "caffeine.today": ("اليوم حتى الآن", "Today so far"),
        "caffeine.value": ("%1$d / %2$d ملغ", "%1$d / %2$d mg"),
        "calibration.advise": ("ماذا أغيّر؟", "What should I change?"),
        "calibration.apply": ("طبّق وانتقل للجولة التالية", "Apply and go to the next round"),
        "calibration.balanced": ("الطعم متوازن. لا حاجة لتغيير.", "The taste is balanced. Nothing to change."),
        "calibration.body": ("القوام", "Body"),
        "calibration.body.heavy": ("ثقيل جدًا", "Too heavy"),
        "calibration.body.right": ("مناسب", "Just right"),
        "calibration.body.thin": ("مائي خفيف", "Thin, watery"),
        "calibration.brewTest": ("حضّر إسبريسو للتجربة", "Make a test espresso"),
        "calibration.cooler": ("اخفض الحرارة درجة واحدة.", "Lower the temperature one step."),
        "calibration.done": ("انتهت المعايرة. درجة الطحن المقترحة %d.", "Calibration done. Suggested grind: %d."),
        "calibration.finish": ("أنهِ المعايرة", "Finish calibration"),
        "calibration.grindCoarser": ("اجعل الطحن أخشن إلى الدرجة %d أثناء عمل المطحنة.", "Grind coarser, to %d, while the grinder runs."),
        "calibration.grindFiner": ("اجعل الطحن أنعم إلى الدرجة %d أثناء عمل المطحنة.", "Grind finer, to %d, while the grinder runs."),
        "calibration.hotter": ("ارفع الحرارة درجة واحدة.", "Raise the temperature one step."),
        "calibration.intro": ("ثلاث جولات تذوق: حضّر إسبريسو، صف طعمه، ثم طبّق التعديل. الحموضة تعني طحنًا أنعم، والمرارة تعني طحنًا أخشن.", "Three tasting rounds: make an espresso, describe it, then apply the change. Sour means grind finer; bitter means grind coarser."),
        "calibration.milder": ("خفّف القوة درجة واحدة.", "Make it one step milder."),
        "calibration.next": ("الجولة %1$d. الطحن الآن %2$d. حضّر إسبريسو جديدًا بعد كوب واحد على الأقل.", "Round %1$d. Grind is now %2$d. Make a new espresso after at least one cup."),
        "calibration.round": ("الجولة %1$d من %2$d", "Round %1$d of %2$d"),
        "calibration.step1": ("١. حضّر", "1. Make"),
        "calibration.step2": ("٢. تذوّق وصف", "2. Taste and describe"),
        "calibration.step3": ("٣. التعديل المقترح", "3. Suggested change"),
        "calibration.stronger": ("زد القوة درجة واحدة.", "Make it one step stronger."),
        "calibration.subtitle": ("اضبط الطحن والحرارة بالتذوق", "Tune grind and temperature by taste"),
        "calibration.taste": ("الطعم", "Taste"),
        "calibration.taste.balanced": ("متوازن", "Balanced"),
        "calibration.taste.bitter": ("مر أو محروق", "Bitter or burnt"),
        "calibration.taste.sour": ("حامض أو لاذع", "Sour or sharp"),
        "calibration.title": ("معايرة البن بالتذوق", "Calibrate by tasting"),
        "carafe.after": ("نظّف أنبوب الحليب الآن: أدر المقبض إلى CLEAN.", "Clean the milk tube now: turn the dial to CLEAN."),
        "carafe.cleaned": ("نظّفته", "Cleaned"),
        "carafe.done": ("أُحسن. إبريق الحليب نظيف.", "Well done. The milk carafe is clean."),
        "carafe.notify.body": ("أدر مقبض الإبريق إلى CLEAN، ثم ضع الحليب في الثلاجة.", "Turn the carafe dial to CLEAN, then put the milk in the fridge."),
        "carafe.notify.title": ("نظّف إبريق الحليب", "Rinse the milk carafe"),
        "carafe.pending": ("إبريق الحليب لم يُنظّف بعد آخر مشروب.", "The milk carafe was not cleaned after the last drink."),
        "care.brewingUnit": ("غسل وحدة التحضير", "Rinsing the brewing unit"),
        "care.descaling": ("إزالة الترسبات", "Descaling"),
        "care.emptyContainers": ("إفراغ الحاويات", "Emptying the containers"),
        "care.milkCarafe": ("تنظيف إبريق الحليب", "Cleaning the milk carafe"),
        "care.waterFilter": ("فلتر الماء", "Water filter"),
        "care.waterHardness": ("اختبار قساوة الماء", "Water hardness test"),
        "compare.cold": ("بارد", "Cold"),
        "compare.first": ("المشروب الأول", "First drink"),
        "compare.hot": ("ساخن", "Hot"),
        "compare.none": ("لا يوجد", "None"),
        "compare.result": ("المقارنة", "Comparison"),
        "compare.second": ("المشروب الثاني", "Second drink"),
        "compare.spoken": ("%1$@: %2$@. %3$@: %4$@", "%1$@: %2$@. %3$@: %4$@"),
        "compare.temperature": ("يُقدّم", "Served"),
        "compare.title": ("قارن مشروبين", "Compare two drinks"),
        "compare.volume": ("الحجم في الكوب", "Volume in the cup"),
        "descale.begin": ("ابدأ إزالة الترسبات", "Start descaling"),
        "descale.cancel": ("إلغاء التشغيل", "Cancel the run"),
        "descale.complete": ("انتهت إزالة الترسبات", "Descaling finished"),
        "descale.finished": ("انتهت إزالة الترسبات وسُجّلت في سجل العناية.", "Descaling is finished and saved in the care log."),
        "descale.left": ("%1$d د %2$d ث", "%1$d min %2$d s"),
        "descale.left.spoken": ("باقٍ نحو %d دقيقة", "About %d minutes left"),
        "descale.nextStage": ("انتهت هذه المرحلة، التالي", "This stage is done, next"),
        "descale.notify.title": ("إزالة الترسبات", "Descaling"),
        "descale.run.intro": ("يرافقك التطبيق في برنامج إزالة الترسبات: ماذا تفعل في كل مرحلة، ومؤقت يرن عند انتهائها حتى والهاتف مقفل. ابدأ البرنامج من قائمة الماكينة نفسها.", "The app walks you through the machine's descaling programme: what to do at each stage, with a timer that rings when it ends, even when the phone is locked. Start the programme from the machine's own menu."),
        "descale.run.subtitle": ("خطوة بخطوة مع مؤقت لكل مرحلة", "Step by step, with a timer for each stage"),
        "descale.run.title": ("إزالة الترسبات بمؤقت", "Descaling with a timer"),
        "descale.stage.finish": ("أفرغ الوعاء وصينية التقطير، واملأ الخزان بماء نظيف. الماكينة جاهزة.", "Empty the bowl and drip tray and refill the tank with clean water. The machine is ready."),
        "descale.stage.finish.title": ("الإنهاء", "Finishing"),
        "descale.stage.prepare": ("أفرغ صينية التقطير وحاوية البن المستعمل، وأزل فلتر الماء إن وجد. صب محلول إزالة الترسبات في الخزان واملأه بالماء حتى العلامة، وضع وعاءً كبيرًا تحت الصنابير.", "Empty the drip tray and grounds container and remove the water filter if fitted. Pour the descaler into the tank, add water up to the mark, and put a large bowl under the spouts."),
        "descale.stage.prepare.title": ("التجهيز", "Preparation"),
        "descale.stage.rinse": ("تشطف الماكينة الدوائر بالماء النظيف. انتظر حتى تتوقف.", "The machine rinses its circuits with clean water. Wait until it stops."),
        "descale.stage.rinse.title": ("الشطف", "Rinsing"),
        "descale.stage.rinseFill": ("عند طلب الماكينة: أفرغ الوعاء، اشطف الخزان واملأه بماء نظيف حتى MAX، وأعد الفلتر إن كان لديك.", "When the machine asks: empty the bowl, rinse the tank and fill it with clean water to MAX, and refit the filter if you use one."),
        "descale.stage.rinseFill.title": ("تعبئة الشطف", "Fill for rinsing"),
        "descale.stage.run": ("ابدأ البرنامج من قائمة الماكينة. يتدفق المحلول على دفعات. لا تحرك الوعاء.", "Start the programme from the machine's menu. The solution runs out in bursts. Leave the bowl in place."),
        "descale.stage.run.title": ("إزالة الترسبات", "Descaling"),
        "descale.stageDone": ("انتهت مرحلة: %@", "Stage finished: %@"),
        "descale.stageOf": ("المرحلة %1$d من %2$d", "Stage %1$d of %2$d"),
        "descale.stageReady": ("انتهى الوقت. تحقق من الماكينة ثم تابع.", "Time is up. Check the machine, then continue."),
        "descale.startTimer": ("ابدأ مؤقت %d دقيقة", "Start a %d-minute timer"),
        "descale.timerStarted": ("بدأ المؤقت لمدة %d دقيقة. سأنبهك عند انتهائه.", "Timer started for %d minutes. I'll let you know when it ends."),
        "drink.americano.origin": ("الولايات المتحدة. إسبريسو مخفف بماء ساخن؛ يُروى أن الجنود الأمريكيين في إيطاليا أحبوه هكذا.", "United States. Espresso topped up with hot water; said to be how American soldiers in Italy liked it."),
        "drink.babyccino.origin": ("أستراليا. رغوة حليب دافئة للأطفال في فنجان صغير.", "Australia. Warm milk froth for children in a small cup."),
        "drink.blackEye.origin": ("الولايات المتحدة. قهوة طويلة مع جرعتي إسبريسو، أقوى من الريد آي.", "United States. A long coffee with two espresso shots, stronger than a Red Eye."),
        "drink.blackTea.origin": ("الهند وسريلانكا. يُنقع بماء شديد الحرارة.", "India and Sri Lanka. Steeped in very hot water."),
        "drink.cafeAuLait.origin": ("فرنسا. قهوة طويلة مع حليب ساخن بنسب متقاربة، تُشرب صباحًا.", "France. Long coffee with hot milk in similar amounts, a breakfast drink."),
        "drink.cafeConLeche.origin": ("إسبانيا. إسبريسو قوي مع حليب ساخن، مشروب الإفطار المعتاد.", "Spain. Strong espresso with hot milk, the everyday breakfast drink."),
        "drink.caffeLatte.origin": ("إيطاليا. إسبريسو مع كثير من الحليب الساخن ورغوة قليلة.", "Italy. Espresso with plenty of hot milk and a little foam."),
        "drink.cappuccino.origin": ("إيطاليا. إسبريسو مع حليب ساخن ورغوة كثيفة، سُمي على لون رداء رهبان الكبوشيين.", "Italy. Espresso with hot milk and thick foam, named after the colour of Capuchin friars' robes."),
        "drink.cappuccinoMix.origin": ("كابتشينو تُصب فيه القهوة فوق الحليب لطبقات ممزوجة.", "A cappuccino with the coffee poured over the milk for blended layers."),
        "drink.cappuccinoPlus.origin": ("إيطاليا. كابتشينو بجرعة قهوة أكبر.", "Italy. A cappuccino with more coffee."),
        "drink.coffee.origin": ("أوروبا. قهوة طويلة تُحضّر كالإسبريسو بماء أكثر، تُشرب في كوب.", "Europe. A long coffee made like espresso with more water, drunk from a cup."),
        "drink.coffeePot.origin": ("قهوة للمشاركة في إبريق واحد للعائلة أو الضيوف.", "Coffee to share: one pot for the family or guests."),
        "drink.coldBrew.origin": ("قهوة تُستخلص بالماء البارد، ناعمة قليلة الحموضة.", "Coffee extracted with cold water, smooth and low in acidity."),
        "drink.coldBrewCappuccino.origin": ("كولد برو مع رغوة حليب باردة.", "Cold brew with cold milk foam."),
        "drink.coldBrewLatte.origin": ("كولد برو مع حليب بارد في كأس طويل.", "Cold brew with cold milk in a tall glass."),
        "drink.coldBrewPot.origin": ("كولد برو في إبريق للمشاركة.", "Cold brew in a pot to share."),
        "drink.coldBrewToMix.origin": ("كولد برو مركز يُمزج مع الحليب أو الماء أو الثلج.", "Concentrated cold brew to mix with milk, water or ice."),
        "drink.coldMilk.origin": ("حليب بارد برغوة، يُضاف للمشروبات الباردة.", "Cold frothed milk, to add to cold drinks."),
        "drink.cortado.origin": ("إسبانيا. إسبريسو «مقطوع» بكمية مماثلة من الحليب الساخن.", "Spain. Espresso 'cut' with about the same amount of warm milk."),
        "drink.doppioPlus.origin": ("إيطاليا. إسبريسو مزدوج قوي جدًا، من ابتكار ماكينات De'Longhi.", "Italy. An extra-strong double espresso, a De'Longhi machine speciality."),
        "drink.espresso.origin": ("إيطاليا. قهوة مركزة تُحضّر بضغط الماء الساخن عبر بن مطحون ناعمًا، وأساس معظم المشروبات.", "Italy. Concentrated coffee made by forcing hot water through fine grounds; the base of most drinks."),
        "drink.espressoDouble.origin": ("إيطاليا. جرعتا إسبريسو في فنجان واحد، يُعرف بالدوبيو.", "Italy. Two shots in one cup, known as a doppio."),
        "drink.espressoIntenso.origin": ("إيطاليا. إسبريسو بجرعة بن أكبر لطعم أعمق.", "Italy. Espresso with more coffee for a deeper taste."),
        "drink.espressoLungo.origin": ("إيطاليا. إسبريسو «طويل» بماء أكثر، أخف وأطول.", "Italy. A 'long' espresso with more water, lighter and longer."),
        "drink.espressoMacchiato.origin": ("إيطاليا. إسبريسو «مبقّع» بقليل من رغوة الحليب.", "Italy. Espresso 'stained' with a little milk foam."),
        "drink.filterCoffee.origin": ("ألمانيا وأمريكا الشمالية. قهوة مقطّرة ببطء، صافية وخفيفة القوام.", "Germany and North America. Slowly dripped coffee, clean and light-bodied."),
        "drink.flatWhite.origin": ("أستراليا ونيوزيلندا. إسبريسو مع حليب ناعم الرغوة رقيقها.", "Australia and New Zealand. Espresso with smooth, thin micro-foam milk."),
        "drink.galao.origin": ("البرتغال. إسبريسو مع كثير من رغوة الحليب في كأس طويل.", "Portugal. Espresso with lots of milk foam in a tall glass."),
        "drink.greenTea.origin": ("الصين واليابان. يُنقع بماء أقل حرارة ليبقى لطيفًا.", "China and Japan. Steeped in cooler water so it stays gentle."),
        "drink.herbalTea.origin": ("نقيع أعشاب دون كافيين، بماء شديد الحرارة.", "A caffeine-free herbal infusion, with very hot water."),
        "drink.hotMilk.origin": ("حليب ساخن برغوة، للأطفال أو مع الشاي.", "Hot frothed milk, for children or with tea."),
        "drink.hotWater.origin": ("ماء ساخن للشاي أو الأعشاب أو تدفئة الكوب.", "Hot water for tea, herbs or warming a cup."),
        "drink.icedAmericano.origin": ("أمريكانو بارد: إسبريسو وماء على الثلج.", "A cold Americano: espresso and water over ice."),
        "drink.icedCaffeLatte.origin": ("لاتيه على الثلج بحليب بارد.", "A latte over ice with cold milk."),
        "drink.icedCappuccino.origin": ("كابتشينو بارد برغوة حليب باردة.", "A cold cappuccino with cold milk foam."),
        "drink.icedCappuccinoMix.origin": ("كابتشينو ميكس على الثلج.", "A cappuccino mix over ice."),
        "drink.icedCoffee.origin": ("قهوة تُصب على الثلج مباشرة.", "Coffee poured straight over ice."),
        "drink.icedEspresso.origin": ("إسبريسو على الثلج، قوي وبارد.", "Espresso over ice, strong and cold."),
        "drink.icedFlatWhite.origin": ("فلات وايت على الثلج.", "A flat white over ice."),
        "drink.icedLatteMacchiato.origin": ("لاتيه ماكياتو بطبقات على الثلج.", "A layered latte macchiato over ice."),
        "drink.koffieVerkeerd.origin": ("هولندا. «القهوة المعكوسة»: حليب أكثر من القهوة.", "Netherlands. 'Wrong coffee': more milk than coffee."),
        "drink.latteMacchiato.origin": ("إيطاليا. حليب «مبقّع» بالإسبريسو، في كأس طويل بطبقات واضحة.", "Italy. Milk 'stained' with espresso, in a tall glass with clear layers."),
        "drink.milchkaffee.origin": ("ألمانيا. قهوة طويلة مع الحليب الساخن في كوب كبير.", "Germany. Long coffee with hot milk in a big cup."),
        "drink.mildFilter.origin": ("أمريكا الشمالية. قهوة مقطّرة بنكهة ألطف.", "North America. Filter coffee with a gentler taste."),
        "drink.redEye.origin": ("الولايات المتحدة. قهوة طويلة مع جرعة إسبريسو لمن سهر الليل.", "United States. A long coffee with a shot of espresso, for those up all night."),
        "drink.ristretto.origin": ("إيطاليا. إسبريسو «مقيّد» بماء أقل، أقوى وأحلى.", "Italy. A 'restricted' espresso with less water, stronger and sweeter."),
        "drink.verlaengerter.origin": ("النمسا. إسبريسو «ممدد» بالماء الساخن، قريب من الأمريكانو، من مقاهي فيينا.", "Austria. An espresso 'lengthened' with hot water, close to an Americano, from Vienna's cafés."),
        "family.add": ("أضف فردًا", "Add a person"),
        "family.edit": ("فرد من العائلة", "Household member"),
        "family.empty.body": ("أضف اسم كل فرد ومشروبه المعتاد لتحضيره بلمسة.", "Add each person's name and usual drink to make it in one tap."),
        "family.empty.title": ("أضف العائلة", "Add your household"),
        "family.footer": ("يُحفظ مشروب كل فرد على هذا الجهاز. يمكنك تحضير أكثر من مشروب متتالٍ من «دور العائلة».", "Each person's drink is kept on this device. Make several in a row from the household queue."),
        "family.member": ("%1$@: %2$@", "%1$@: %2$@"),
        "family.name": ("الاسم", "Name"),
        "family.saved": ("حُفظ مشروب %@.", "Saved %@'s drink."),
        "family.title": ("العائلة", "Household"),
        "fill.overflow": ("الكمية أكبر من الكوب المعتاد لهذا المشروب. استخدم كوبًا أكبر.", "That is more than this drink's usual cup holds. Use a bigger cup."),
        "fill.spoken": ("نحو %1$d مل في كوب يتسع %2$d مل، أي %3$d بالمئة", "About %1$d ml in a %2$d ml cup, %3$d percent"),
        "fill.title": ("امتلاء الكوب", "Cup fill"),
        "forecast.basis": ("بناءً على نحو %@ كوب يوميًا وقساوة الماء. التقدير لا يغني عن تنبيهات الماكينة.", "Based on about %@ cups a day and the water hardness. The machine's own alerts always come first."),
        "forecast.filter": ("ركّبت فلتر ماء في الخزان", "A water filter is fitted"),
        "forecast.inDays": ("بعد نحو %1$d يومًا (%2$@)", "In about %1$d days (%2$@)"),
        "forecast.notify.body": ("حسب استخدامك، اقترب الموعد. افتح قهوتي لترى الدليل.", "Based on your use, it is nearly due. Open Coffee for the guide."),
        "forecast.notify.title": ("اقترب موعد: %@", "Due soon: %@"),
        "forecast.now": ("الآن", "Now"),
        "forecast.remind": ("ذكّرني قبل الموعد", "Remind me when due"),
        "forecast.title": ("مواعيد العناية القادمة", "Upcoming care"),
        "goal.coldBrew.detail": ("حضّر أي مشروب كولد برو.", "Make any cold brew drink."),
        "goal.coldBrew.title": ("أول كولد برو", "First cold brew"),
        "goal.done": ("مكتمل", "Done"),
        "goal.mildWeek.detail": ("سبعة أيام دون قوة «قوية جدًا» ودون جرعة إضافية.", "Seven days without extra strong or an extra shot."),
        "goal.mildWeek.title": ("أسبوع هادئ", "A gentle week"),
        "goal.milkArtist.detail": ("جرّب ستة مشروبات مختلفة بالحليب.", "Try six different milk drinks."),
        "goal.milkArtist.title": ("فنان الحليب", "Milk artist"),
        "goal.progress": ("%1$d من %2$d", "%1$d of %2$d"),
        "goal.recipeMaker.detail": ("احفظ ثلاث وصفات باسمك.", "Save three recipes with your own name."),
        "goal.recipeMaker.title": ("صانع الوصفات", "Recipe maker"),
        "goal.signature3.detail": ("حضّر ثلاث وصفات من «وصفات من العالم».", "Make three recipes from Recipes from around the world."),
        "goal.signature3.title": ("ذوّاق الوصفات", "Recipe explorer"),
        "goal.streak7.detail": ("حضّر قهوة كل يوم لسبعة أيام متتالية.", "Make coffee every day for seven days in a row."),
        "goal.streak7.title": ("أسبوع متواصل", "A week in a row"),
        "goal.world5.detail": ("جرّب خمسة مشروبات من مجموعة «اكتشف العالم».", "Try five drinks from the Discover the world collection."),
        "goal.world5.title": ("جولة حول العالم", "Around the world"),
        "goals.title": ("التحديات", "Challenges"),
        "hardness.apply": ("أرسل الدرجة إلى الماكينة", "Send the level to the machine"),
        "hardness.current": ("الدرجة الحالية: %d", "Current level: %d"),
        "hardness.dipped": ("غمست الشريط، ابدأ العد", "I dipped the strip, start counting"),
        "hardness.footer": ("عدد المربعات الحمراء على الشريط يحدد درجة القساوة. تُرسل الدرجة إلى الماكينة عند الاتصال، وتُحفظ في التطبيق دائمًا.", "The number of red squares on the strip gives the hardness level. It is sent to the machine when connected and always kept in the app."),
        "hardness.level": ("درجة القساوة", "Hardness level"),
        "hardness.readNow": ("مرّت دقيقة. اقرأ الشريط الآن.", "A minute has passed. Read the strip now."),
        "hardness.redSquares": ("المربعات الحمراء", "Red squares"),
        "hardness.saved": ("حُفظت قساوة الماء: %@", "Water hardness saved: %@"),
        "hardness.savedNote": ("حُفظت الدرجة وسُجّلت في سجل العناية.", "Saved and added to the care log."),
        "hardness.squares": ("%d مربعات", "%d squares"),
        "hardness.started": ("بدأ العد. سأخبرك عند مرور دقيقة.", "Counting. I'll tell you when a minute has passed."),
        "hardness.step1": ("١. اغمس شريط الاختبار المرفق بالماكينة في ماء الصنبور ثانية واحدة.", "1. Dip the test strip that came with the machine in tap water for one second."),
        "hardness.step2": ("٢. أخرجه وانتظر دقيقة، ثم عدّ المربعات التي صارت حمراء.", "2. Take it out, wait one minute, then count the squares that turned red."),
        "hardness.subtitle": ("بشريط الاختبار ومؤقت ناطق", "With the test strip and a spoken timer"),
        "hardness.title": ("اختبار قساوة الماء", "Water hardness test"),
        "hardness.waiting": ("باقٍ %d ثانية", "%d seconds left"),
        "homeLayout.footer": ("اسحب لإعادة الترتيب، أو استخدم قائمة الإجراءات مع VoiceOver. أوقف قسمًا لإخفائه.", "Drag to reorder, or use the Actions rotor with VoiceOver. Turn a section off to hide it."),
        "homeLayout.open": ("رتّب الرئيسية", "Arrange home"),
        "homeLayout.reset": ("أعد الترتيب الأصلي", "Restore the original order"),
        "homeLayout.resetDone": ("عادت الرئيسية إلى ترتيبها الأصلي.", "Home is back to its original order."),
        "homeLayout.title": ("ترتيب الرئيسية", "Arrange home"),
        "homeSection.caffeine": ("الكافيين اليوم", "Caffeine today"),
        "homeSection.collections": ("المجموعات", "Collections"),
        "homeSection.family": ("العائلة", "Household"),
        "homeSection.favorites": ("مفضلتي", "My favorites"),
        "homeSection.frequent": ("الأكثر تحضيرًا", "Most made"),
        "homeSection.journey": ("رحلتي مع القهوة", "My coffee journey"),
        "homeSection.moment": ("الآن", "Right now"),
        "homeSection.ready": ("جاهز للتحضير", "Ready to brew"),
        "homeSection.recommended": ("قريب من ذوقك", "Close to your taste"),
        "homeSection.seasonal": ("وصفات الموسم", "Seasonal recipes"),
        "homeSection.signature": ("وصفات من العالم", "Recipes from around the world"),
        "homeSection.today": ("مشروب اليوم", "Drink of the day"),
        "journal.beans": ("ملاحظات البن", "Bean notes"),
        "journal.cups": ("الأكواب", "Cups"),
        "journal.empty": ("لا ملاحظات بعد. بعد أي مشروب قيّمه أو أضف ملاحظة.", "No notes yet. After any drink, rate it or add a note."),
        "journal.title": ("دفتر التذوق", "Tasting journal"),
        "knowledge.bigger": ("%1$@ أكبر بنحو %2$d مل", "%1$@ is about %2$d ml bigger"),
        "knowledge.cup": ("الكوب المناسب", "The right cup"),
        "knowledge.milkOnly": ("%@ فقط فيه حليب", "Only %@ has milk"),
        "knowledge.moreCaffeine": ("في %1$@ كافيين أكثر بنحو %2$d ملغ", "%1$@ has about %2$d mg more caffeine"),
        "knowledge.origin": ("الأصل", "Origin"),
        "knowledge.ratio": ("القهوة إلى الحليب", "Coffee to milk"),
        "knowledge.ratio.coffee": ("القهوة أكثر: %d إلى 1", "More coffee: %d to 1"),
        "knowledge.ratio.milk": ("1 قهوة إلى %d حليب", "1 coffee to %d milk"),
        "knowledge.similar": ("المشروبان متقاربان في الحجم والكافيين.", "The two are close in size and caffeine."),
        "knowledge.title": ("اعرف مشروبك", "Know your drink"),
        "library.origin.brazil.notes": ("شوكولاتة ومكسرات بقوام ثقيل وحموضة قليلة.", "Chocolate and nuts, heavy body, low acidity."),
        "library.origin.brazil.title": ("البرازيل", "Brazil"),
        "library.origin.colombia.notes": ("متوازن ناعم بطعم الكراميل والمكسرات.", "Balanced and smooth with caramel and nuts."),
        "library.origin.colombia.title": ("كولومبيا", "Colombia"),
        "library.origin.ethiopia.notes": ("زهري وفاكهي بحموضة مشرقة، مثل التوت والليمون.", "Floral and fruity with bright acidity, like berries and lemon."),
        "library.origin.ethiopia.title": ("إثيوبيا", "Ethiopia"),
        "library.origin.guatemala.notes": ("شوكولاتة وبهارات مع حلاوة واضحة.", "Chocolate and spice with clear sweetness."),
        "library.origin.guatemala.title": ("غواتيمالا", "Guatemala"),
        "library.origin.india.notes": ("ناعم قوي القوام مع بهارات خفيفة، يحب الحليب.", "Smooth with a full body and light spice; good with milk."),
        "library.origin.india.title": ("الهند", "India"),
        "library.origin.indonesia.notes": ("ثقيل ترابي بطعم الأعشاب، حموضة منخفضة.", "Heavy and earthy with herbal notes, low acidity."),
        "library.origin.indonesia.title": ("إندونيسيا", "Indonesia"),
        "library.origin.kenya.notes": ("حموضة قوية بطعم الكشمش والطماطم الحلوة.", "Strong acidity with blackcurrant and sweet tomato."),
        "library.origin.kenya.title": ("كينيا", "Kenya"),
        "library.origin.yemen.notes": ("عميق وترابي مع بهارات ونكهة فواكه مجففة.", "Deep and earthy with spice and dried fruit."),
        "library.origin.yemen.title": ("اليمن", "Yemen"),
        "library.origins": ("بلدان المنشأ", "Origins"),
        "library.roast.dark": ("تحميص داكن: مرارة لطيفة وشوكولاتة، قوام ثقيل. يناسب الإسبريسو بالحليب. اطحنه أخشن قليلًا.", "Dark roast: gentle bitterness and chocolate, heavy body. Suits espresso with milk. Grind a little coarser."),
        "library.roast.light": ("تحميص فاتح: حموضة ونكهات فاكهة، قوام أخف. يناسب القهوة الطويلة والمقطّرة. اطحنه أنعم قليلًا.", "Light roast: acidity and fruit, lighter body. Suits long and filter coffee. Grind a little finer."),
        "library.roast.medium": ("تحميص متوسط: توازن بين الحلاوة والحموضة. يناسب كل المشروبات تقريبًا.", "Medium roast: balanced sweetness and acidity. Suits almost every drink."),
        "library.roasts": ("درجات التحميص", "Roasts"),
        "library.subtitle": ("المناشئ والتحميص وما يناسبها", "Origins, roasts and what suits them"),
        "library.suits": ("يناسب: %@", "Suits: %@"),
        "library.title": ("مكتبة البن", "Bean library"),
        "log.add": ("سجّل عناية", "Log care"),
        "log.addNow": ("سجّلها الآن", "Log it now"),
        "log.empty": ("السجل فارغ. يُضاف ما تنهيه من أدلة العناية تلقائيًا.", "The log is empty. Care guides you finish are added automatically."),
        "log.history": ("السجل", "History"),
        "log.saved": ("سُجّل: %@", "Logged: %@"),
        "log.subtitle": ("متى أزلت الترسبات وغيّرت الفلتر", "When you descaled and changed the filter"),
        "log.task": ("المهمة", "Task"),
        "log.title": ("سجل العناية", "Care log"),
        "machineInfo.copied": ("نُسخ الرقم التسلسلي.", "Serial number copied."),
        "machineInfo.copySerial": ("انسخ الرقم التسلسلي", "Copy serial number"),
        "machineInfo.outOfWarranty": ("انتهى الضمان حسب التاريخ المسجل.", "Out of warranty by the recorded date."),
        "machineInfo.purchased": ("تاريخ الشراء", "Purchase date"),
        "machineInfo.serial": ("الرقم التسلسلي", "Serial number"),
        "machineInfo.title": ("بيانات الماكينة", "Machine details"),
        "machineInfo.underWarranty": ("الماكينة ما زالت في الضمان حسب التاريخ المسجل.", "Still under warranty by the recorded date."),
        "machineInfo.warranty": ("مدة الضمان", "Warranty"),
        "machineInfo.warrantyEnds": ("ينتهي الضمان", "Warranty ends"),
        "machineInfo.years": ("%d سنوات", "%d years"),
        "machines.add": ("أضف ماكينة", "Add a machine"),
        "machines.current": ("الماكينة الحالية. لديك %d ماكينة مسجلة.", "Current machine. %d machines saved."),
        "machines.footer": ("لكل ماكينة اسمها واتصالها بالبلوتوث. اختر ماكينة للاتصال بها.", "Each machine keeps its name and Bluetooth link. Choose one to connect to it."),
        "machines.hint": ("البيت والمكتب وغيرهما", "Home, office and more"),
        "machines.switched": ("تبدلت الماكينة إلى %@.", "Switched to %@."),
        "machines.title": ("ماكيناتي", "My machines"),
        "picker.drink": ("المشروب", "Drink"),
        "prebrew.carafe": ("ركّب إبريق الحليب وفيه حليب بارد.", "Fit the milk carafe with cold milk in it."),
        "prebrew.coldCarafe": ("ركّب إبريق الحليب البارد.", "Fit the cold milk carafe."),
        "prebrew.cup": ("ضع كوبًا تحت الصنبور.", "Put a cup under the spout."),
        "prebrew.froth": ("أدر مقبض الرغوة إلى: %@.", "Turn the froth dial to: %@."),
        "prebrew.mug": ("ضع كوب السفر وارفع الصنبور.", "Put the travel mug in place and raise the spout."),
        "prebrew.pot": ("ضع الإبريق تحت الصنبور.", "Put the pot under the spout."),
        "prebrew.title": ("قبل البدء:", "Before it starts:"),
        "query.cold": ("بارد", "cold"),
        "queue.cancel": ("أوقف الدور", "Stop the queue"),
        "queue.cupReady": ("الكوب في مكانه، حضّر", "The cup is in place, make it"),
        "queue.done": ("انتهت كل المشروبات. بالعافية!", "All drinks are ready. Enjoy!"),
        "queue.intro": ("اختر من يريد قهوة. يحضّر التطبيق مشروبًا بعد مشروب، وينتظر أن تضع الكوب التالي.", "Choose who wants coffee. The app makes one drink after another and waits for the next cup."),
        "queue.making": ("جارٍ التحضير…", "Making…"),
        "queue.next": ("التالي: %1$@ لـ %2$@. ضع الكوب ثم اضغط «الكوب في مكانه».", "Next: %1$@ for %2$@. Put the cup in place, then tap The cup is in place."),
        "queue.nowFor": ("%1$@ لـ %2$@", "%1$@ for %2$@"),
        "queue.progress": ("المشروب %1$d من %2$d", "Drink %1$d of %2$d"),
        "queue.retry": ("لم يكتمل المشروب. ضع الكوب وحاول مرة أخرى.", "The drink did not finish. Put the cup back and try again."),
        "queue.start": ("ابدأ الدور (%d)", "Start the queue (%d)"),
        "queue.title": ("دور العائلة", "Household queue"),
        "rating.adjusted": ("سيُحضّر %1$@ لاحقًا بقوة: %2$@.", "Next time %1$@ will be: %2$@."),
        "rating.disliked": ("لم يعجبني", "Didn't like it"),
        "rating.liked": ("أعجبني", "Liked it"),
        "rating.note.add": ("أضف ملاحظة تذوق", "Add a tasting note"),
        "rating.note.placeholder": ("اكتب أو أملِ ملاحظتك", "Type or dictate your note"),
        "rating.note.saved": ("حُفظت الملاحظة في دفتر التذوق.", "Note saved to the tasting journal."),
        "rating.question": ("كيف كان الكوب؟", "How was it?"),
        "rating.strength.right": ("مضبوطة", "Just right"),
        "rating.strength.stronger": ("أقوى", "Stronger"),
        "rating.strength.weaker": ("أخف", "Milder"),
        "rating.thanks": ("شكرًا، حُفظ تقييمك.", "Thanks, your rating is saved."),
        "ready.last": ("أعد طلبك الأخير: %@", "Again: %@"),
        "ready.usual": ("حضّر %@", "Make %@"),
        "recommended.body": ("مشروبات لم تجرّبها، قريبة مما تحب.", "Drinks you haven't tried, close to what you like."),
        "recommended.title": ("قريب من ذوقك", "Close to your taste"),
        "routine.brewing": ("جارٍ تحضير %@", "Making %@"),
        "routine.connecting": ("جارٍ الاتصال بالماكينة…", "Connecting to the machine…"),
        "routine.heating": ("جارٍ تشغيل الماكينة وتسخينها. تشطف نفسها عند التشغيل.", "Turning the machine on and heating. It rinses itself as it starts."),
        "routine.hint": ("يشغّل الماكينة وينتظر جاهزيتها ثم يحضّر المشروب", "Turns the machine on, waits until it is ready, then makes the drink"),
        "routine.notStarted": ("لم يبدأ المشروب. افتح قهوتي لمعرفة السبب.", "The drink did not start. Open Coffee to see why."),
        "routine.start": ("روتين الصباح: شغّل ثم حضّر %@", "Morning routine: turn on, then make %@"),
        "schedule.add": ("أضف موعدًا", "Add a time"),
        "schedule.days": ("الأيام", "Days"),
        "schedule.drink": ("المشروب", "Drink"),
        "schedule.edit": ("موعد القهوة", "Coffee time"),
        "schedule.enabled": ("مفعّل", "On"),
        "schedule.everyDay": ("كل يوم", "Every day"),
        "schedule.footer": ("في الموعد يصلك تنبيه فيه زر «حضّر الآن». الماكينة لا تبدأ وحدها والهاتف مقفل؛ يحتاج التحضير لمستك.", "At the time you get a reminder with a Make it now button. The machine never starts by itself while the phone is locked; it needs your tap."),
        "schedule.fromFavorites": ("اختر من المفضلة", "Choose from favorites"),
        "schedule.honest": ("لا تُحضّر القهوة دون تأكيد منك، حرصًا على ألا تُصب دون كوب.", "Coffee is never made without your tap, so it never pours without a cup."),
        "schedule.notify.action": ("حضّر الآن", "Make it now"),
        "schedule.notify.body": ("ضع الكوب ثم اضغط «حضّر الآن».", "Put the cup in place, then tap Make it now."),
        "schedule.notify.bodyFor": ("مشروب %@. ضع الكوب ثم اضغط «حضّر الآن».", "%@'s drink. Put the cup in place, then tap Make it now."),
        "schedule.notify.title": ("وقت %@", "Time for %@"),
        "schedule.off": ("موقوف", "Off"),
        "schedule.once": ("مرة واحدة", "Once"),
        "schedule.owner": ("لمن؟ (اختياري)", "For whom? (optional)"),
        "schedule.row": ("%1$@ — %2$@", "%1$@ — %2$@"),
        "schedule.saved": ("حُفظ الموعد %@.", "Saved for %@."),
        "schedule.time": ("الوقت", "Time"),
        "schedule.title": ("مواعيد القهوة", "Coffee times"),
        "schedule.turnOn": ("شغّل الماكينة أولًا", "Turn the machine on first"),
        "schedule.workdays": ("من الأحد إلى الخميس", "Sunday to Thursday"),
        "search.adjust": ("عدّل قبل التحضير", "Adjust before making"),
        "search.drinks": ("مشروبات بهذا الاسم", "Drinks with this name"),
        "search.examples": ("أمثلة: «لاتيه بارد قوي»، «أمريكانو كبير سفري»، «كابتشينو الحليب أولًا». يمكنك الإملاء بزر الميكروفون في لوحة المفاتيح.", "Examples: «strong iced latte», «large americano to go». You can dictate with the keyboard microphone."),
        "search.field.hint": ("اكتب أو أملِ المشروب وصفاته", "Type or dictate the drink and how you want it"),
        "search.found": ("فهمت: %@", "Understood: %@"),
        "search.noMatch": ("لم أعرف المشروب. جرّب اسمًا من القائمة.", "I didn't recognise the drink. Try a name from the menu."),
        "search.open": ("ابحث أو اطلب بصوتك", "Search or order by voice"),
        "search.open.hint": ("مثل: لاتيه بارد قوي", "For example: strong iced latte"),
        "search.placeholder": ("ماذا تريد أن تشرب؟", "What would you like?"),
        "search.title": ("اطلب بكلماتك", "Order in your words"),
        "search.understood": ("فهمت طلبك:", "Here is what I understood:"),
        "season.ramadan": ("رمضان", "Ramadan"),
        "season.summer": ("الصيف", "Summer"),
        "season.winter": ("الشتاء", "Winter"),
        "seasonal.title": ("وصفات الموسم: %@", "Seasonal: %@"),
        "settings.carafe": ("ذكّرني بتنظيف إبريق الحليب", "Remind me to clean the milk carafe"),
        "settings.experience": ("التجربة", "Experience"),
        "settings.experience.footer": ("الوضع البسيط يعرض ثلاثة أزرار كبيرة فقط. أصوات المراحل نغمات قصيرة مختلفة للطحن والصب والجاهزية.", "Simple mode shows only three big buttons. Phase sounds are short, different tones for grinding, pouring and ready."),
        "settings.icloud": ("مزامنة عبر iCloud", "Sync with iCloud"),
        "settings.icloud.footer": ("تُزامن المفضلة والوصفات والبن والعائلة والمواعيد بين أجهزتك. تعمل فقط إذا وُقّعت النسخة بصلاحية iCloud. السجل يبقى على كل جهاز.", "Syncs favorites, recipes, beans, household and times across your devices. Works only when this copy is signed with iCloud. History stays on each device."),
        "settings.icloud.header": ("أجهزتك", "Your devices"),
        "settings.icloud.last": ("آخر مزامنة", "Last sync"),
        "settings.liveActivities": ("التحضير على شاشة القفل", "Show brewing on the Lock Screen"),
        "settings.prebrew": ("ذكّرني بالكوب ومقبض الرغوة قبل التحضير", "Remind me about the cup and froth dial"),
        "settings.quantityTones": ("نغمة ترتفع مع الكمية", "A tone that rises with the amount"),
        "settings.simpleMode": ("الوضع البسيط", "Simple mode"),
        "settings.soundCues": ("أصوات مراحل التحضير", "Sounds for each brewing phase"),
        "settings.timeTheme": ("ألوان الرئيسية حسب وقت اليوم", "Home colours follow the time of day"),
        "setup.connectBluetooth": ("اتصل عبر البلوتوث", "Connect over Bluetooth"),
        "setup.defaultName": ("ماكينة المنزل", "Home machine"),
        "setup.done": ("اكتمل إعداد %@.", "%@ is set up."),
        "setup.filter": ("ركّبت فلتر الماء", "A water filter is fitted"),
        "setup.finish": ("أنهِ الإعداد", "Finish setup"),
        "setup.model": ("الطراز", "Model"),
        "setup.name": ("اسم الماكينة", "Machine name"),
        "setup.step1.body": ("سنجهّز الماكينة معًا في ست خطوات قصيرة. يمكنك العودة لأي خطوة.", "We will set the machine up together in six short steps. You can go back to any step."),
        "setup.step1.title": ("مرحبًا بماكينتك", "Welcome to your machine"),
        "setup.step2.body": ("اسم يميزها إن كان لديك أكثر من ماكينة، مثل «المطبخ» أو «المكتب». الرقم التسلسلي على ملصق تحت صينية التقطير.", "A name that tells it apart if you have more than one, such as Kitchen or Office. The serial number is on a label under the drip tray."),
        "setup.step2.title": ("سمِّ ماكينتك", "Name your machine"),
        "setup.step3.body": ("املأ خزان الماء وحاوية البن، وتأكد أن الحاويات في مكانها. كل دليل خطوة بخطوة.", "Fill the water tank and bean container, and check the containers are in place. Each guide goes step by step."),
        "setup.step3.title": ("جهّز الماكينة", "Prepare the machine"),
        "setup.step4.body": ("اختبار قساوة الماء بالشريط المرفق يضبط موعد إزالة الترسبات بدقة.", "The hardness test with the supplied strip sets the descaling reminder correctly."),
        "setup.step4.title": ("اختبر الماء", "Test the water"),
        "setup.step5.body": ("إن ركّبت فلتر الماء فستطول المدة بين إزالة الترسبات، وسيذكّرك التطبيق بتغييره.", "With a water filter fitted, descaling is needed less often, and the app reminds you to change it."),
        "setup.step5.title": ("فلتر الماء", "Water filter"),
        "setup.step6.body": ("اتصل بالماكينة عبر البلوتوث، أو جرّب التطبيق بالماكينة الافتراضية. أداة «فحص الماكينة» تخبرك إن كانت ماكينتك تدعم الاتصال.", "Connect to the machine over Bluetooth, or try the app with the demo machine. The Machine check tool tells you whether your machine supports the connection."),
        "setup.step6.title": ("الاتصال", "Connect"),
        "setup.stepOf": ("الخطوة %1$d من %2$d", "Step %1$d of %2$d"),
        "setup.subtitle": ("خطوة بخطوة: التسمية والتجهيز والماء والاتصال", "Step by step: name, prepare, water and connect"),
        "setup.title": ("إعداد الماكينة", "Set up the machine"),
        "setup.useDemo": ("جرّب بالماكينة الافتراضية", "Try with the demo machine"),
        "share.import.add": ("أضفها إلى مفضلتي", "Add to my favorites"),
        "share.import.title": ("وصفة مشاركة", "A shared recipe"),
        "share.message": ("وصفتي في قهوتي: %@", "My recipe in Coffee: %@"),
        "share.qr": ("رمز QR", "QR code"),
        "share.qr.hint": ("يمسحه صديقك بكاميرا هاتفه فيفتح الوصفة في قهوتي.", "A friend scans it with their camera to open the recipe in Coffee."),
        "share.qr.label": ("رمز QR لوصفة %@", "QR code for %@"),
        "share.recipe": ("شارك الوصفة", "Share recipe"),
        "shopping.added": ("أُضيف %d إلى «التذكيرات».", "%d added to Reminders."),
        "shopping.beans": ("بن: %@", "Beans: %@"),
        "shopping.cupsLeft": ("يكفي لنحو %d كوب", "Enough for about %d cups"),
        "shopping.denied": ("لم يُسمح بالوصول إلى «التذكيرات».", "Access to Reminders was not allowed."),
        "shopping.descaler": ("محلول إزالة الترسبات", "Descaler"),
        "shopping.dueIn": ("الموعد بعد نحو %d يومًا", "Due in about %d days"),
        "shopping.empty": ("لا شيء تحتاجه الآن.", "Nothing needed right now."),
        "shopping.filter": ("فلتر ماء", "Water filter"),
        "shopping.reminders": ("أضف إلى «التذكيرات»", "Add to Reminders"),
        "shopping.share": ("شارك القائمة", "Share the list"),
        "shopping.subtitle": ("المستلزمات التي ستحتاجها قريبًا", "Supplies you'll need soon"),
        "shopping.title": ("قائمة المشتريات", "Shopping list"),
        "signal.alarm.beanHopperMissing.words": ("حاوية البن غطاء", "bean container lid"),
        "signal.alarm.beansEmpty.words": ("بن نفد حبوب تعبئة", "beans empty refill"),
        "signal.alarm.descaleNeeded.words": ("ترسبات كلس تنظيف ضوء", "descale limescale calc light"),
        "signal.alarm.doorOpen.words": ("باب جانبي مفتوح وحدة التحضير", "side door open brewing unit"),
        "signal.alarm.dripTrayMissing.words": ("صينية تقطير مفقودة", "drip tray missing"),
        "signal.alarm.groundTooFine.words": ("طحن ناعم بطيء قطرات", "grind too fine slow dripping"),
        "signal.alarm.hardwareFault.words": ("عطل خطأ رمز ضوء احمر وميض", "fault error code red light blinking"),
        "signal.alarm.milkCarafeNeedsCleaning.words": ("حليب ابريق تنظيف clean", "milk carafe clean"),
        "signal.alarm.replaceFilter.words": ("فلتر تغيير ماء", "filter replace water"),
        "signal.alarm.serviceNeeded.words": ("صيانة خدمة", "service maintenance"),
        "signal.alarm.wasteContainerFull.words": ("حاوية ممتلئة افراغ بن مستعمل", "grounds full empty container"),
        "signal.alarm.wasteContainerMissing.words": ("حاوية بن مستعمل مفقودة صينية", "grounds container missing tray"),
        "signal.alarm.waterTankEmpty.words": ("ماء فارغ تعبئة خزان صوت تنبيه", "water empty fill tank beep"),
        "signal.alarm.waterTankMissing.words": ("خزان ماء مفقود لا يوجد", "tank missing no tank"),
        "signal.extra.1.advice": ("الماكينة تسخن بعد التشغيل. انتظر دقيقة حتى تنتهي.", "The machine is heating after switching on. Wait a minute for it to finish."),
        "signal.extra.1.title": ("تسخين", "Heating up"),
        "signal.extra.1.words": ("تسخين انتظار heating warming", "تسخين انتظار heating warming"),
        "signal.extra.2.advice": ("يخرج قليل من الماء الساخن من الصنبور لشطف الدوائر. هذا طبيعي؛ ضع وعاءً تحته.", "A little hot water comes from the spout to rinse the circuits. This is normal; put a bowl under it."),
        "signal.extra.2.title": ("شطف عند التشغيل أو الإطفاء", "Rinsing at start or stop"),
        "signal.extra.2.words": ("شطف ماء يخرج rinse water", "شطف ماء يخرج rinse water"),
        "signal.extra.3.advice": ("الشاشة خافتة لتوفير الطاقة. المس الشاشة أو حضّر مشروبًا لتعود.", "The display is dimmed to save energy. Touch it or make a drink to wake it."),
        "signal.extra.3.title": ("وضع توفير الطاقة", "Energy saving"),
        "signal.extra.3.words": ("توفير طاقة شاشة مطفأة energy saving dim", "توفير طاقة شاشة مطفأة energy saving dim"),
        "signal.extra.4.advice": ("الطحن ناعم جدًا أو البن كثير. اجعل الطحن أخشن درجة أثناء عمل المطحنة.", "The grind is too fine or there is too much coffee. Grind one step coarser while the grinder runs."),
        "signal.extra.4.title": ("القهوة تخرج قطرات", "Coffee comes out in drips"),
        "signal.extra.4.words": ("قطرات بطيء drip slow", "قطرات بطيء drip slow"),
        "signal.extra.5.advice": ("الطحن خشن أو القوة منخفضة. اجعل الطحن أنعم درجة أو زد القوة.", "The grind is too coarse or the strength is low. Grind one step finer or raise the strength."),
        "signal.extra.5.title": ("القهوة مائية", "Coffee tastes watery"),
        "signal.extra.5.words": ("مائي خفيف watery weak", "مائي خفيف watery weak"),
        "signal.extra.6.advice": ("استخدم حليبًا باردًا من الثلاجة، ونظّف الإبريق، وأدر المقبض نحو رغوة أكثر.", "Use cold milk from the fridge, clean the carafe and turn the dial toward more froth."),
        "signal.extra.6.title": ("الحليب لا يرغو", "The milk does not froth"),
        "signal.extra.6.words": ("رغوه حليب لا يرغو froth milk foam", "رغوه حليب لا يرغو froth milk foam"),
        "signal.extra.7.advice": ("قد يكون البن عالقًا. حرّك الحبوب في الحاوية بملعقة خشبية وحاول مجددًا.", "Beans may be stuck. Stir the beans in the container with a wooden spoon and try again."),
        "signal.extra.7.title": ("صوت المطحنة ولا قهوة", "The grinder runs but no coffee"),
        "signal.extra.7.words": ("مطحنه صوت لا قهوة grinder noise no coffee", "مطحنه صوت لا قهوة grinder noise no coffee"),
        "signal.extra.8.advice": ("أطفئها من المفتاح الرئيسي وانتظر دقيقة ثم شغّلها. إن تكرر فتواصل مع الصيانة.", "Turn it off at the main switch, wait a minute and turn it on. If it happens again, contact service."),
        "signal.extra.8.title": ("الماكينة لا تستجيب", "The machine does not respond"),
        "signal.extra.8.words": ("لا تستجيب متجمدة frozen not responding", "لا تستجيب متجمدة frozen not responding"),
        "signal.hint": ("ابحث بما تراه على الشاشة أو تسمعه", "Search by what you see or hear"),
        "signal.none": ("لا نتائج. جرّب كلمة أخرى، أو اقرأ الشاشة بالكاميرا.", "No results. Try another word, or read the display with the camera."),
        "signal.search": ("مثل: ماء، ضوء أحمر، صوت تنبيه", "e.g. water, red light, beeping"),
        "signal.title": ("ماذا تعني هذه الإشارة؟", "What does this signal mean?"),
        "signature.affogato.after.1": ("قدّمه فورًا مع ملعقة قبل أن يذوب الآيس كريم.", "Serve at once with a spoon, before the ice cream melts."),
        "signature.affogato.before.1": ("ضع كرة آيس كريم الفانيليا في الكأس.", "Put the scoop of vanilla ice cream in the glass."),
        "signature.affogato.before.2": ("ضع الكأس تحت الصنبور واخفضه قريبًا منه.", "Put the glass under the spout and lower the spout close to it."),
        "signature.affogato.ingredient.1": ("كرة آيس كريم فانيليا", "A scoop of vanilla ice cream"),
        "signature.affogato.ingredient.2": ("كأس صغير أو فنجان واسع", "A small glass or wide cup"),
        "signature.affogato.summary": ("إسبريسو ساخن فوق كرة آيس كريم فانيليا، حلوى إيطالية سريعة.", "Hot espresso poured over vanilla ice cream, a quick Italian dessert."),
        "signature.affogato.title": ("أفوغاتو", "Affogato"),
        "signature.base": ("دور الماكينة: %@", "The machine's part: %@"),
        "signature.cafeBombon.after.1": ("قدّمه بطبقتين، وقلّبه قبل الشرب.", "Serve it in two layers and stir before drinking."),
        "signature.cafeBombon.before.1": ("صب الحليب المكثف في كأس صغير شفاف.", "Pour the condensed milk into a small clear glass."),
        "signature.cafeBombon.before.2": ("ضع الكأس تحت الصنبور.", "Put the glass under the spout."),
        "signature.cafeBombon.ingredient.1": ("حليب مكثف محلى، ملعقة كبيرة", "Sweetened condensed milk, one tablespoon"),
        "signature.cafeBombon.summary": ("إسبريسو فوق طبقة من الحليب المكثف، من إسبانيا.", "Espresso over a layer of condensed milk, from Spain."),
        "signature.cafeBombon.title": ("كافيه بومبون", "Café bombón"),
        "signature.cardamomLatte.after.1": ("قلّب، ورشّ قليلًا من الهيل على الرغوة.", "Stir, and dust a little cardamom on the foam."),
        "signature.cardamomLatte.before.1": ("ضع رشة الهيل والسكر إن أردت في الكوب، ثم ضعه تحت الصنبور.", "Put the cardamom, and sugar if you like, in the cup, then put it under the spout."),
        "signature.cardamomLatte.ingredient.1": ("هيل مطحون، رشة", "Ground cardamom, a pinch"),
        "signature.cardamomLatte.ingredient.2": ("سكر أو عسل (اختياري)", "Sugar or honey (optional)"),
        "signature.cardamomLatte.summary": ("لاتيه دافئ برائحة الهيل، يذكّر بالقهوة العربية.", "A warm latte scented with cardamom, a nod to Arabic coffee."),
        "signature.cardamomLatte.title": ("لاتيه بالهيل", "Cardamom latte"),
        "signature.enjoy": ("بالعافية", "Enjoy"),
        "signature.enjoy.spoken": ("بالعافية! حُسب هذا المشروب في تحدياتك.", "Enjoy! This drink counts toward your challenges."),
        "signature.espressoTonic.after.1": ("أضف شريحة البرتقال إن رغبت.", "Add the orange slice if you like."),
        "signature.espressoTonic.after.2": ("اشربه مباشرة دون تقليب للحفاظ على الطبقات.", "Drink it straight away without stirring, to keep the layers."),
        "signature.espressoTonic.before.1": ("املأ كأسًا طويلًا بالثلج.", "Fill a tall glass with ice."),
        "signature.espressoTonic.before.2": ("صب ماء التونك ببطء حتى ثلثي الكأس، وضعه تحت الصنبور.", "Pour the tonic slowly to two thirds and put the glass under the spout."),
        "signature.espressoTonic.ingredient.1": ("ماء تونك بارد، نحو 150 مل", "Cold tonic water, about 150 ml"),
        "signature.espressoTonic.ingredient.2": ("مكعبات ثلج", "Ice cubes"),
        "signature.espressoTonic.ingredient.3": ("شريحة برتقال (اختياري)", "An orange slice (optional)"),
        "signature.espressoTonic.summary": ("ماء تونك فوار مع الثلج وإسبريسو فوقه، منعش ومرّ قليلًا.", "Sparkling tonic over ice with espresso on top: fresh and lightly bitter."),
        "signature.espressoTonic.title": ("إسبريسو تونك", "Espresso tonic"),
        "signature.honeyCinnamonLatte.after.1": ("قلّب حتى يذوب العسل.", "Stir until the honey dissolves."),
        "signature.honeyCinnamonLatte.after.2": ("رشّ القرفة على الرغوة.", "Dust cinnamon over the foam."),
        "signature.honeyCinnamonLatte.before.1": ("ضع العسل في الكوب ثم ضعه تحت الصنبور.", "Put the honey in the cup, then put it under the spout."),
        "signature.honeyCinnamonLatte.ingredient.1": ("عسل، ملعقة صغيرة", "Honey, one teaspoon"),
        "signature.honeyCinnamonLatte.ingredient.2": ("قرفة مطحونة", "Ground cinnamon"),
        "signature.honeyCinnamonLatte.summary": ("لاتيه خفيف محلى بالعسل مع لمسة قرفة للشتاء.", "A mild latte sweetened with honey and a touch of cinnamon for winter."),
        "signature.honeyCinnamonLatte.title": ("لاتيه بالعسل والقرفة", "Honey cinnamon latte"),
        "signature.icedDateLatte.after.1": ("قلّب جيدًا حتى يمتزج الدبس.", "Stir well until the syrup blends in."),
        "signature.icedDateLatte.before.1": ("ضع دبس التمر في قاع الكأس.", "Put the date syrup in the bottom of the glass."),
        "signature.icedDateLatte.before.2": ("أضف الثلج وضع الكأس تحت الصنبور.", "Add the ice and put the glass under the spout."),
        "signature.icedDateLatte.ingredient.1": ("دبس تمر، ملعقتان كبيرتان", "Date syrup, two tablespoons"),
        "signature.icedDateLatte.ingredient.2": ("مكعبات ثلج", "Ice cubes"),
        "signature.icedDateLatte.summary": ("لاتيه بارد محلى بدبس التمر، مناسب بعد الإفطار.", "An iced latte sweetened with date syrup, nice after iftar."),
        "signature.icedDateLatte.title": ("لاتيه مثلج بالتمر", "Iced date latte"),
        "signature.ingredient.hint": ("اضغط مرتين لتحديده كجاهز", "Double-tap to mark it ready"),
        "signature.ingredients": ("المكونات", "Ingredients"),
        "signature.machineStep": ("الماكينة تحضّر الآن: %@.", "The machine now makes: %@."),
        "signature.mocha.after.1": ("قلّب جيدًا من القاع.", "Stir well from the bottom."),
        "signature.mocha.after.2": ("رشّ الكاكاو على الرغوة إن رغبت.", "Dust cocoa on the foam if you like."),
        "signature.mocha.before.1": ("ضع صلصة الشوكولاتة في الكوب ثم ضعه تحت الصنبور.", "Put the chocolate sauce in the cup, then put it under the spout."),
        "signature.mocha.ingredient.1": ("صلصة شوكولاتة، ملعقة إلى ملعقتين", "Chocolate sauce, one to two tablespoons"),
        "signature.mocha.ingredient.2": ("كاكاو للتزيين (اختياري)", "Cocoa for dusting (optional)"),
        "signature.mocha.summary": ("كابتشينو بصلصة الشوكولاتة، دافئ وغني.", "A cappuccino with chocolate sauce: warm and rich."),
        "signature.mocha.title": ("موكا", "Mocha"),
        "signature.orangeEspresso.after.1": ("قلّب برفق قبل الشرب.", "Stir gently before drinking."),
        "signature.orangeEspresso.before.1": ("املأ الكأس بالثلج.", "Fill the glass with ice."),
        "signature.orangeEspresso.before.2": ("صب عصير البرتقال وضع الكأس تحت الصنبور.", "Pour in the orange juice and put the glass under the spout."),
        "signature.orangeEspresso.ingredient.1": ("عصير برتقال طازج بارد، نحو 100 مل", "Fresh cold orange juice, about 100 ml"),
        "signature.orangeEspresso.ingredient.2": ("مكعبات ثلج", "Ice cubes"),
        "signature.orangeEspresso.summary": ("عصير برتقال بارد مع الثلج وإسبريسو فوقه، منعش للصيف.", "Cold orange juice over ice with espresso on top, a summer refresher."),
        "signature.orangeEspresso.title": ("إسبريسو بالبرتقال", "Orange espresso"),
        "signature.saffronCappuccino.after.1": ("قلّب برفق ليظهر لون الزعفران.", "Stir gently to bring out the saffron colour."),
        "signature.saffronCappuccino.before.1": ("انقع الزعفران في الماء الدافئ خمس دقائق.", "Soak the saffron in the warm water for five minutes."),
        "signature.saffronCappuccino.before.2": ("صبه في الكوب مع السكر إن أردت، وضع الكوب تحت الصنبور.", "Pour it into the cup, with sugar if you like, and put the cup under the spout."),
        "signature.saffronCappuccino.ingredient.1": ("بضع خيوط زعفران في ملعقة ماء دافئ", "A few saffron threads in a spoon of warm water"),
        "signature.saffronCappuccino.ingredient.2": ("سكر (اختياري)", "Sugar (optional)"),
        "signature.saffronCappuccino.summary": ("كابتشينو بخيوط الزعفران المنقوعة، لسهرات رمضان والشتاء.", "A cappuccino with soaked saffron threads, for Ramadan and winter evenings."),
        "signature.saffronCappuccino.title": ("كابتشينو بالزعفران", "Saffron cappuccino"),
        "signature.section": ("وصفات من العالم", "Recipes from around the world"),
        "signature.shakerato.after.1": ("صب الإسبريسو في المرطبان مع الشراب إن أردت.", "Pour the espresso into the jar, with syrup if you like."),
        "signature.shakerato.after.2": ("أغلقه ورجّه بقوة نحو 15 ثانية.", "Close it and shake hard for about 15 seconds."),
        "signature.shakerato.after.3": ("صفّه في كأس دون الثلج.", "Strain it into a glass, leaving the ice behind."),
        "signature.shakerato.before.1": ("ضع فنجانًا تحت الصنبور، وجهّز المرطبان نصفه ثلج.", "Put a cup under the spout and half fill the jar with ice."),
        "signature.shakerato.ingredient.1": ("مكعبات ثلج", "Ice cubes"),
        "signature.shakerato.ingredient.2": ("شراب سكر (اختياري)", "Sugar syrup (optional)"),
        "signature.shakerato.ingredient.3": ("مرطبان بغطاء أو شيكر", "A jar with a lid or a shaker"),
        "signature.shakerato.summary": ("إسبريسو مزدوج يُرج مع الثلج حتى يصير رغويًا باردًا.", "A double espresso shaken with ice until cold and frothy."),
        "signature.shakerato.title": ("شيكيراتو", "Shakerato"),
        "signature.spanishLatte.after.1": ("قلّب جيدًا حتى يذوب الحليب المكثف.", "Stir well until the condensed milk dissolves."),
        "signature.spanishLatte.before.1": ("ضع الحليب المكثف في قاع الكأس ثم ضعه تحت الصنبور.", "Put the condensed milk in the bottom of the glass, then put it under the spout."),
        "signature.spanishLatte.ingredient.1": ("حليب مكثف محلى، ملعقتان كبيرتان", "Sweetened condensed milk, two tablespoons"),
        "signature.spanishLatte.summary": ("لاتيه بالحليب المكثف المحلى، ناعم وحلو.", "A latte with sweetened condensed milk: smooth and sweet."),
        "signature.spanishLatte.title": ("سبانش لاتيه", "Spanish latte"),
        "signature.stepOf": ("الخطوة %1$d من %2$d", "Step %1$d of %2$d"),
        "signature.vietnameseIced.after.1": ("قلّب جيدًا حتى يمتزج الحليب بالقهوة.", "Stir well until the milk and coffee blend."),
        "signature.vietnameseIced.before.1": ("ضع الحليب المكثف في قاع الكأس.", "Put the condensed milk in the bottom of the glass."),
        "signature.vietnameseIced.before.2": ("أضف الثلج وضع الكأس تحت الصنبور.", "Add the ice and put the glass under the spout."),
        "signature.vietnameseIced.ingredient.1": ("حليب مكثف محلى، ملعقتان كبيرتان", "Sweetened condensed milk, two tablespoons"),
        "signature.vietnameseIced.ingredient.2": ("مكعبات ثلج", "Ice cubes"),
        "signature.vietnameseIced.summary": ("قهوة قوية جدًا مع الحليب المكثف والثلج.", "Very strong coffee with condensed milk over ice."),
        "signature.vietnameseIced.title": ("قهوة فيتنامية مثلجة", "Vietnamese iced coffee"),
        "simple.exit": ("اخرج من الوضع البسيط", "Leave simple mode"),
        "simple.exitHint": ("للخروج من الوضع البسيط اضغط هنا مطوّلًا", "Press and hold here to leave simple mode"),
        "simple.last": ("مرة أخرى: %@", "Again: %@"),
        "simple.status": ("حالة الماكينة", "Machine status"),
        "simple.title": ("قهوتي", "My coffee"),
        "simple.usual": ("حضّر %@", "Make %@"),
        "stock.cups": ("يكفي لنحو %d كوب", "Enough for about %d cups"),
        "stock.grams": ("%d غ", "%d g"),
        "stock.low": ("البن يوشك على النفاد: نحو %d كوب. أُضيف إلى قائمة المشتريات.", "Beans nearly gone: about %d cups. Added to the shopping list."),
        "stock.spoken": ("نحو %1$d غرامًا، تكفي لنحو %2$d كوب", "About %1$d grams, enough for about %2$d cups"),
        "stock.title": ("المتبقي في الكيس", "Left in the bag"),
        "stock.unknown": ("أدخل وزن الكيس وتاريخ فتحه لمعرفة المتبقي.", "Enter the bag weight and opening date to see what is left."),
        "summary.notify.title": ("أسبوعك مع القهوة", "Your coffee week"),
        "today.brew": ("حضّر مشروب اليوم: %@", "Make today's drink: %@"),
        "today.open": ("اعرف المزيد", "Learn more"),
        "today.title": ("مشروب اليوم", "Drink of the day"),
        "tour.beans.body": ("في أعلى الماكينة تحت غطاء. بجانبها مقبض درجة الطحن، لا يُدار إلا والمطحنة تعمل.", "On top of the machine, under a lid. The grind dial is beside it and must only be turned while the grinder runs."),
        "tour.beans.title": ("حاوية البن", "The bean container"),
        "tour.display.body": ("في أعلى الواجهة. تختار منها المشروب وتظهر عليها التنبيهات. يقرؤها التطبيق بالكاميرا عند الحاجة.", "At the top of the front. You pick drinks there and alerts appear there. The app can read it with the camera."),
        "tour.display.title": ("الشاشة اللمسية", "The touch display"),
        "tour.front.body": ("قف أمام الماكينة. الشاشة واللوحة في الأعلى، والصنبور في الوسط، وصينية التقطير في الأسفل.", "Stand facing the machine. The display and panel are at the top, the spout in the middle, the drip tray at the bottom."),
        "tour.front.title": ("الواجهة", "The front"),
        "tour.grounds.body": ("خلف صينية التقطير أو فوقها، تخرج معها. أفرغها عند طلب الماكينة.", "Behind or on top of the drip tray and comes out with it. Empty it when the machine asks."),
        "tour.grounds.title": ("حاوية البن المستعمل", "The grounds container"),
        "tour.hint": ("أين كل جزء في الماكينة، بالكلمات", "Where each part of the machine is, in words"),
        "tour.hotWater.body": ("بجانب صنبور القهوة؛ يُركّب عليها إبريق الحليب أو فوهة الماء.", "Next to the coffee spout; the milk carafe or the water spout fits here."),
        "tour.hotWater.title": ("فوهة الماء الساخن", "The hot water outlet"),
        "tour.milk.body": ("في الواجهة قرب الصنبور. يُدفع الإبريق فيه حتى يثبت، ومقبض الإبريق يضبط الرغوة وعلامة CLEAN للتنظيف.", "On the front near the spout. Push the carafe in until it sits firmly; its dial sets the froth and has a CLEAN mark."),
        "tour.milk.title": ("موصل إبريق الحليب", "The milk carafe connector"),
        "tour.note": ("المواضع وصف عام لماكينات De'Longhi الأوتوماتيكية، وقد تختلف قليلًا في طرازك. الدليل الورقي هو المرجع.", "Positions describe De'Longhi bean-to-cup machines in general and may differ slightly on your model. The printed manual is the reference."),
        "tour.power.body": ("في الواجهة قرب الشاشة. والمفتاح الرئيسي، إن وجد، في الخلف.", "On the front near the display. The main switch, if there is one, is at the back."),
        "tour.power.title": ("زر التشغيل", "The power button"),
        "tour.spout.body": ("تحت الشاشة في الوسط. يتحرك لأعلى ولأسفل؛ اخفضه قرب الفنجان وارفعه لكوب السفر.", "Below the display, in the middle. It slides up and down; lower it near the cup and raise it for a travel mug."),
        "tour.spout.title": ("صنبور القهوة", "The coffee spout"),
        "tour.stepOf": ("الجزء %1$d من %2$d", "Part %1$d of %2$d"),
        "tour.tank.body": ("يُسحب من الماكينة لتعبئته، وعليه علامة MAX. موضعه يختلف حسب الطراز، وغالبًا في الجانب أو الخلف.", "Slides out to be filled and has a MAX mark. Its position varies by model, often at the side or back."),
        "tour.tank.title": ("خزان الماء", "The water tank"),
        "tour.title": ("جولة مسموعة في الماكينة", "Audio tour of the machine"),
        "tour.tray.body": ("في أسفل الواجهة، تُسحب إلى الأمام. فيها عوّامة ترتفع حين تمتلئ.", "At the bottom of the front; pull it forward. A float rises when it is full."),
        "tour.tray.title": ("صينية التقطير", "The drip tray"),
        "tour.unit.body": ("خلف باب جانبي، غالبًا على اليمين. تُخرج بالضغط على زريها وتُغسل بالماء فقط.", "Behind a side door, usually on the right. Press its two buttons to remove it, and rinse it with water only."),
        "tour.unit.title": ("وحدة التحضير", "The brewing unit"),
        "vessel.cup": ("فنجان قهوة (نحو 220 مل)", "Coffee cup (about 220 ml)"),
        "vessel.espressoCup": ("فنجان إسبريسو صغير (نحو 90 مل)", "Small espresso cup (about 90 ml)"),
        "vessel.iceGlass": ("كأس بارد مع ثلج (نحو 400 مل)", "Glass with ice (about 400 ml)"),
        "vessel.mug": ("كوب كبير (نحو 350 مل)", "Mug (about 350 ml)"),
        "vessel.pot": ("إبريق (حتى لتر)", "Pot (up to a litre)"),
        "vessel.tallGlass": ("كأس طويل (نحو 330 مل)", "Tall glass (about 330 ml)"),
        "vessel.teaCup": ("كوب شاي (نحو 300 مل)", "Tea cup (about 300 ml)"),
        "vessel.travelMug": ("كوب سفر (نحو 450 مل)", "Travel mug (about 450 ml)"),
        "weekly.caffeine": ("متوسط الكافيين نحو %d ملغ يوميًا", "About %d mg of caffeine a day"),
        "weekly.caffeineLabel": ("الكافيين يوميًا", "Caffeine a day"),
        "weekly.cups": ("حضّرت %d كوبًا هذا الأسبوع", "You made %d cups this week"),
        "weekly.cupsLabel": ("الأكواب", "Cups"),
        "weekly.fewer": ("أقل بـ %d من الأسبوع الماضي", "%d fewer than last week"),
        "weekly.hour": ("وقتك المعتاد نحو الساعة %d", "Your usual time is around %d:00"),
        "weekly.hourLabel": ("الوقت المعتاد", "Usual time"),
        "weekly.more": ("أكثر بـ %d من الأسبوع الماضي", "%d more than last week"),
        "weekly.new": ("جرّبت %d مشروبات جديدة", "You tried %d new drinks"),
        "weekly.none": ("لم تحضّر قهوة هذا الأسبوع بعد.", "No coffee this week yet."),
        "weekly.notify": ("ملخص كل أحد مساءً", "A summary every Sunday evening"),
        "weekly.notify.footer": ("يصلك ملخص قصير في الثامنة مساء كل أحد. يُحدّث كلما فتحت التطبيق.", "A short summary arrives at 8 pm every Sunday. It updates whenever you open the app."),
        "weekly.title": ("ملخص الأسبوع", "Weekly summary"),
        "weekly.top": ("الأكثر: %@", "Top drink: %@"),
        "weekly.topLabel": ("المشروب الأكثر", "Top drink"),
    ]
}
